// The whole game world, in one place. Data-oriented: every subsystem owns a
// sub-struct here, and systems are free functions over (GameState&, GameContext&).
// This is what lets the five zones be built in parallel without sharing files.
//
// SHARED CONTRACT — owned by the orchestrator. Agents extend their *own*
// sub-struct (in their own header); they do not edit this file.
#pragma once

#include <vector>

#include "game/areas.hpp"
#include "game/dayloop.hpp"
#include "game/enemies.hpp"
#include "game/player.hpp"
#include "game/ritual.hpp"
#include "game/spawner.hpp"
#include "game/types.hpp"
#include "game/weapons.hpp"

namespace rv_3dmppc {

struct GameState {
    PlayerState player;
    WeaponState weapons;
    EnemyWorld enemies;
    SpawnerState spawner;
    RitualState ritual;
    AreaWorld world;
    DayLoopState loop;

    std::vector<Projectile> projectiles;

    float time = 0.0f;  // seconds since boot (accumulated dt)

    // Cross-system, one-frame scratch:
    const char* prompt = nullptr;  // interact prompt text ("Hold E: assemble")
    bool playerHitThisFrame = false;  // set by combat, read for ritual interrupt
};

}  // namespace rv_3dmppc
