// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — quad-based text drawing: atlas, palette, string layout.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

#include "pdk/cv/rv_primitives.hpp"
#include "pdk/cv/rv_texture.hpp"
#include "pdk/cv/rv_vertex.hpp"
#include "pdklib/rv_text/rv_font_data.hpp"

namespace rv_pdklib {

// Text, drawn by a disc, out of the primitives the console already has.
//
// The console has NO text primitive and is not getting one. On the machine this
// imitates, a font was an asset the game shipped and drew with the ordinary
// textured primitives; a "draw string" opcode would be a piece of the standard
// library soldered onto a GPU. So this header lives in pdklib/, above the contract,
// and produces nothing but rv_pdk::rv_primitive values the disc files with
// frame_put.
//
// WHY A QUAD AND NOT A SPRITE. rv_pdk::rv_sprite is the cheaper entity and looks
// like the obvious answer — an axis-aligned rectangle is exactly what a character
// is. It cannot be used: rv_sprite carries NO uv (pdk/cv/rv_primitives.hpp), so a
// textured sprite always lays the texture down from its UPPER-LEFT CORNER. It can
// therefore show the whole atlas, or the atlas tiled, but never one chosen cell
// out of it. Selecting a glyph means naming texture coordinates, and the only
// entity with per-vertex uv is rv_pdk::rv_polygon. Hence one four-vertex polygon
// per character, in the PDK's Z order (v0 top-left, v1 top-right, v2 bottom-left,
// v3 bottom-right) so the console's (1,2,3)/(2,3,4) split lands on the two halves
// of the rectangle instead of folding it into an hourglass.
//
// WHY ONE PRIMITIVE PER CHARACTER, and not per pixel. A 1x1 sprite per lit pixel
// is the other way to get text without uv, and it costs a 5x7 glyph up to 35
// primitives: a 40-column line would spend 1400 of a frame budget that is in the
// low thousands, to draw one line of a HUD. One quad per character spends 40.
//
// PATTERN: THE COLOUR OF TEXT COMES FROM THE PALETTE, NOT FROM VERTEX COLOURS.
// This is the part that surprises people, so it is stated here rather than
// discovered later. The obvious modern move — draw a white glyph and tint it with
// the vertex colour — needs texture-combine (modulate), and the contract marks
// that DEFERRED (rv_pdk::rv_polygon: "DEFERRED: blending ... and texture-combine
// (raw/modulation) flags"). Today a SAMPLE_TEXTURE primitive shows the texel and
// nothing else; the vertex colours it carries are ignored. Setting
// rv_pdk::rv_vertex colours here would change exactly nothing on screen.
//
// The era's own answer, and ours: the atlas is uploaded ONCE as RV_TEXFMT_IDX4
// with only two indices in use — 0 for the background, 1 for the ink — and the
// colour lives in the PALETTE. To draw the same string in a second colour, upload
// a second 16-entry palette and point the primitive's addr_palette at it. Nothing
// is re-rasterised, nothing is duplicated: the same 3 KiB of texels serves every
// colour of text the disc ever shows, which is precisely why PSX games recoloured
// fonts and menus this way. When texture-combine lands, vertex modulation becomes
// an ADDITION to this, not a replacement — a per-glyph fade over a palette that
// already picked the hue.
//
// TRANSPARENCY FALLS OUT OF THE SAME PALETTE. Per pdk/cv/rv_texture.hpp the value
// 0000h is fully transparent and, for the indexed formats, transparency is decided
// AFTER the palette lookup. So palette entry 0 is written as 0000h and the glyph
// background is a hole: text lands on top of the picture instead of inside a
// rectangle of its own. The trap this creates is real and is guarded below — an
// INK colour that packs to 0000h (pure black) would make the text itself the hole
// and the string would vanish. See rv_text_pack_rgb555.

// --- the atlas ----------------------------------------------------------------

// 16 cells across, 6 down = 96 cells for the font's 96 glyphs (95 printable plus
// the notdef block, which is the last cell). 16 across is not arbitrary: a power
// of two makes the cell arithmetic a shift and a mask, and it makes the atlas 128
// texels wide, which is a size any plausible texture limit accepts.
inline constexpr int rv_text_atlas_columns = 16;
inline constexpr int rv_text_atlas_rows = 6;

inline constexpr int rv_text_atlas_width = rv_text_atlas_columns * rv_font_cell_width;  // 128
inline constexpr int rv_text_atlas_height = rv_text_atlas_rows * rv_font_cell_height;   // 48

// IDX4 stores two texels per byte, so a row of 128 texels is 64 bytes.
inline constexpr std::size_t rv_text_atlas_stride =
    static_cast<std::size_t>(rv_text_atlas_width) / 2;
inline constexpr std::size_t rv_text_atlas_size =
    rv_text_atlas_stride * static_cast<std::size_t>(rv_text_atlas_height);  // 3072 bytes

// The two palette indices the atlas uses. Everything else in the 16-entry palette
// stays 0000h, i.e. transparent, so a corrupted index draws nothing rather than a
// stray colour.
inline constexpr uint8_t rv_text_index_background = 0;
inline constexpr uint8_t rv_text_index_ink = 1;

inline constexpr std::size_t rv_text_palette_entries = 16;                        // IDX4 palette
inline constexpr std::size_t rv_text_palette_size = rv_text_palette_entries * 2;  // bytes

// Map a byte to a cell index. Anything outside the printable ASCII range — a
// control byte, a stray 0x0D from CRLF line endings, the lead byte of a UTF-8
// sequence — lands on the notdef block on purpose: broken encoding must look
// broken, not empty.
inline int rv_text_glyph_index(char c) {
    const unsigned int code = static_cast<unsigned char>(c);
    if (code < static_cast<unsigned int>(rv_font_first_code) ||
        code > static_cast<unsigned int>(rv_font_last_code)) {
        return rv_font_notdef_index;
    }
    return static_cast<int>(code) - rv_font_first_code;
}

// THEOREM: character -> cell -> texel coordinates. A glyph's index is `code - 32`
// (the notdef block is index 95), the atlas is filled left to right and top to
// bottom, so index i sits in column i % 16 and row i / 16, and its upper-left
// texel is
//
//     u0 = (i % 16) * 8        v0 = (i / 16) * 8
//
// The cell then covers the HALF-OPEN texel range [u0, u0 + 8) x [v0, v0 + 8).
// Half-open is the load-bearing word, and it is what the quad's uv are built from
// below: the right and bottom edges belong to the NEXT cell and are never
// sampled, which is what stops a glyph from smearing one column of its neighbour
// along its edge. Cell width 8 also keeps u0 EVEN, so every cell begins on a whole
// byte in the IDX4 packing — a glyph never straddles a nibble boundary.
inline int rv_text_cell_u(int glyph_index) {
    return (glyph_index % rv_text_atlas_columns) * rv_font_cell_width;
}

inline int rv_text_cell_v(int glyph_index) {
    return (glyph_index / rv_text_atlas_columns) * rv_font_cell_height;
}

// Expand the bitmap font into IDX4 texels, ready for rv_cv::video_asset_write.
//
// The buffer belongs to the CALLER — this header never allocates and never talks
// to the console. pdklib/ has no rv_cv to talk to: it is built over the contract, and
// the disc is the one holding the machine. Typical use is a 3 KiB array the disc
// keeps on the stack for the length of disc_initialize and drops afterwards; the
// bytes are copied during the upload.
//
// Returns false if `out` is null or `size` is under rv_text_atlas_size.
//
// THEOREM: IDX4 packing. Two texels share a byte and the LOW nibble is the LEFT
// one — the PSX order, fixed by the console (docs/platform/specs.md, and the
// sampler in src/.../rv_pctexel.cpp reads it as `(u & 1) ? packed >> 4 : packed &
// 0x0F`). A converter has to agree with exactly one convention and this is it.
// Rows are padded to a whole byte, so the row stride is (width + 1) / 2 rather
// than width / 2; at width 128 the two agree, but the formula is what the console
// uses and copying it here keeps an odd-width atlas from shearing if these numbers
// are ever changed. Texel (u, v) therefore lives at byte v * stride + u / 2, in
// the low nibble when u is even and the high nibble when u is odd.
inline bool rv_text_build_atlas(uint8_t* out, std::size_t size) {
    if (out == nullptr || size < rv_text_atlas_size) return false;

    // Index 0 everywhere: the background, which the palette makes transparent.
    for (std::size_t i = 0; i < rv_text_atlas_size; ++i) out[i] = 0;

    for (int glyph = 0; glyph < rv_font_glyph_count; ++glyph) {
        const int cell_u = rv_text_cell_u(glyph);
        const int cell_v = rv_text_cell_v(glyph);

        for (int row = 0; row < rv_font_cell_height; ++row) {
            const unsigned int bits = rv_font_bits[glyph * rv_font_cell_height + row];
            if (bits == 0) continue;  // a blank row touches no byte

            const std::size_t base = static_cast<std::size_t>(cell_v + row) * rv_text_atlas_stride;

            for (int col = 0; col < rv_font_cell_width; ++col) {
                // The font's high bit is the leftmost pixel (rv_font_data.hpp).
                if ((bits & (0x80U >> col)) == 0) continue;

                const int u = cell_u + col;
                uint8_t& packed = out[base + static_cast<std::size_t>(u / 2)];
                const unsigned int nibble = (u & 1) != 0
                                                ? static_cast<unsigned int>(rv_text_index_ink) << 4
                                                : static_cast<unsigned int>(rv_text_index_ink);
                packed = static_cast<uint8_t>(packed | nibble);
            }
        }
    }
    return true;
}

// Describe an atlas buffer for rv_cv::video_asset_write. The rv_pdk::rv_texture
// only BORROWS the bytes (pdk/cv/rv_texture.hpp), so `data` must outlive the call.
inline rv_pdk::rv_texture rv_text_atlas_texture(const uint8_t* data) {
    rv_pdk::rv_texture texture{};
    texture.format = rv_pdk::RV_TEXFMT_IDX4;
    texture.data = data;
    texture.size = rv_text_atlas_size;
    texture.width = static_cast<uint64_t>(rv_text_atlas_width);
    texture.height = static_cast<uint64_t>(rv_text_atlas_height);
    return texture;
}

// --- the palette --------------------------------------------------------------

// Pack an rv_pdk::rv_color into one palette entry: the 16-bit layout of a
// DIRECT15 texel, bits 0-4 red, 5-9 green, 10-14 blue, bit 15 the (deferred)
// semi-transparency flag. Eight bits per channel become five by dropping the low
// three — the same truncation the framebuffer performs, so what a disc asks for
// is what it gets.
//
// THE BLACK TRAP: 0000h is not black, it is FULLY TRANSPARENT (rv_texture.hpp).
// An ink colour of pure black would therefore punch the glyph out of the picture
// and the string would silently disappear — the exact failure this whole header
// exists to make impossible. So a packed 0000h is nudged to 0001h, the darkest
// representable red, which is the substitution the hardware's own documentation
// recommends and is indistinguishable from black on screen.
inline uint16_t rv_text_pack_rgb555(rv_pdk::rv_color c) {
    const unsigned int r = static_cast<unsigned int>(c.r) >> 3;
    const unsigned int g = static_cast<unsigned int>(c.g) >> 3;
    const unsigned int b = static_cast<unsigned int>(c.b) >> 3;
    const unsigned int value = r | (g << 5) | (b << 10);
    return static_cast<uint16_t>(value != 0 ? value : 0x0001U);
}

// Build the 16-entry palette a text atlas is drawn with: entry 0 transparent
// (the glyph background), entry 1 the ink, the remaining 14 transparent.
//
// One colour of text = one of these, uploaded once. A disc that wants white body
// text, a yellow highlight and a red warning uploads three palettes of 32 bytes
// each and switches rv_pdk::rv_polygon::addr_palette — see the PATTERN at the top.
//
// Returns false if `out` is null or `count` is under rv_text_palette_entries.
inline bool rv_text_build_palette(rv_pdk::rv_color ink, uint16_t* out, std::size_t count) {
    if (out == nullptr || count < rv_text_palette_entries) return false;
    for (std::size_t i = 0; i < rv_text_palette_entries; ++i) out[i] = 0x0000;
    out[rv_text_index_ink] = rv_text_pack_rgb555(ink);
    return true;
}

// Describe a palette buffer for rv_cv::video_asset_write. A palette is uploaded as
// a DIRECT15 texture of `entries` x 1 — the contract says so explicitly, because a
// palette entry and a DIRECT15 texel are the same 16-bit value.
inline rv_pdk::rv_texture rv_text_palette_texture(const uint16_t* entries) {
    rv_pdk::rv_texture texture{};
    texture.format = rv_pdk::RV_TEXFMT_DIRECT15;
    texture.data = entries;
    texture.size = rv_text_palette_size;
    texture.width = static_cast<uint64_t>(rv_text_palette_entries);
    texture.height = 1;
    return texture;
}

// --- measuring ----------------------------------------------------------------

// Cell advance in screen pixels. `scale` is an INTEGER multiplier — 1 draws the
// 8x8 cell over 8x8 pixels, 2 over 16x16 — because a non-integer scale under
// nearest-neighbour sampling gives a glyph whose stems are two pixels wide in
// some columns and one in others, which is exactly how bad retro text looks. A
// scale of 0 or less is treated as 1 rather than drawing nothing.
inline int rv_text_scale_clamp(int scale) { return scale > 0 ? scale : 1; }

inline int rv_text_advance(int scale) { return rv_font_cell_width * rv_text_scale_clamp(scale); }

// The step '\n' takes, in pixels: one whole cell, so consecutive lines touch. The
// cell's single blank bottom row is the ONLY leading, which is tight — a descender
// on one line sits one pixel above the capitals of the next. That is the 8x8 grid
// being honest about itself, and it is what a caller wants for a dense HUD or a
// character grid. A caller who wants air draws each line with its own call and its
// own y step rather than putting '\n' in the string.
inline int rv_text_line_height(int scale) {
    return rv_font_cell_height * rv_text_scale_clamp(scale);
}

// Width of the longest line, in pixels. This is the ADVANCE width: it includes the
// three blank ink columns that trail the last character of the line (they are the
// letter spacing, see rv_font_data.hpp). A caller centring a label and wanting it
// optically centred may subtract (rv_font_cell_width - rv_font_ink_width) * scale;
// most callers should not bother, because doing so makes a right-aligned column of
// numbers jitter.
inline int rv_text_measure_width(std::string_view text, int scale) {
    int longest = 0;
    int current = 0;
    for (const char c : text) {
        if (c == '\n') {
            if (current > longest) longest = current;
            current = 0;
            continue;
        }
        ++current;
    }
    if (current > longest) longest = current;
    return longest * rv_text_advance(scale);
}

// Number of lines: one, plus one per '\n'. A trailing newline therefore counts a
// final empty line, which is what a caller stacking blocks of text wants.
inline int rv_text_line_count(std::string_view text) {
    int lines = 1;
    for (const char c : text) {
        if (c == '\n') ++lines;
    }
    return lines;
}

inline int rv_text_measure_height(std::string_view text, int scale) {
    return rv_text_line_count(text) * rv_text_line_height(scale);
}

// How many primitives rv_text_draw will produce. Newlines cost nothing, and so
// does the SPACE: its cell is empty, and an empty cell of a transparent-background
// atlas draws not one pixel. Filing it would spend a slot of rv_cv::frame_capacity
// on nothing, so it is skipped — which makes indented or column-aligned text much
// cheaper than its character count suggests.
inline std::size_t rv_text_primitive_count(std::string_view text) {
    std::size_t count = 0;
    for (const char c : text) {
        if (c == '\n' || c == ' ') continue;
        ++count;
    }
    return count;
}

// --- drawing ------------------------------------------------------------------

// Everything a run of text needs beyond its position and its characters. The two
// addresses are what rv_cv::video_asset_malloc returned for the atlas and for the
// palette; `depth` is the ordering-table key, and for a HUD it should sit at the
// near end of whatever range the disc chose (larger = nearer = on top, per the
// contract) so text is not eaten by the scenery.
struct rv_text_style {
    int64_t addr_texture;  // the IDX4 atlas in video RAM
    int64_t addr_palette;  // the 16-entry palette that gives it its colour
    int32_t depth;         // ordering-table key: larger = nearer
    int32_t scale;         // integer pixel multiplier; 1 = an 8x8 cell
};

inline rv_text_style rv_text_style_make(int64_t addr_texture, int64_t addr_palette, int32_t depth,
                                        int32_t scale) {
    rv_text_style style{};
    style.addr_texture = addr_texture;
    style.addr_palette = addr_palette;
    style.depth = depth;
    style.scale = scale;
    return style;
}

namespace rv_text_detail {

// rv_pdk::rv_vertex coordinates are int16 and a caller may legitimately place text
// off the left edge (a scrolling credits crawl), so out-of-range values SATURATE
// instead of wrapping — the same rule pdklib/rv_math/rv_xform.hpp applies to projected
// geometry. A wrap would teleport a glyph to the opposite edge of the screen.
inline int16_t to_int16(int value) {
    if (value < -32768) return static_cast<int16_t>(-32768);
    if (value > 32767) return static_cast<int16_t>(32767);
    return static_cast<int16_t>(value);
}

inline rv_pdk::rv_vertex corner(int x, int y, int u, int v) {
    rv_pdk::rv_vertex vertex{};
    vertex.x = to_int16(x);
    vertex.y = to_int16(y);
    // Ignored by a SAMPLE_TEXTURE primitive today (see the PATTERN at the top of
    // this file); set to white so that the day texture-combine lands, a modulating
    // console multiplies by 1 and the text keeps the colour its palette gave it.
    vertex.color = rv_pdk::rv_color{255, 255, 255};
    vertex.uv = rv_pdk::rv_uv{static_cast<uint16_t>(u), static_cast<uint16_t>(v)};
    return vertex;
}

}  // namespace rv_text_detail

// Build the quad for one glyph at (x, y) — the cell's upper-left pixel.
//
// The quad spans [x, x + 8 * scale) x [y, y + 8 * scale) and its uv span the cell's
// half-open [u0, u0 + 8) x [v0, v0 + 8). Both spans being half-open is what makes
// the mapping exact: the rasterizer fills pixels under a top-left rule (a rectangle
// from x to x + w covers x .. x + w - 1) and interpolates uv affinely from the
// vertex values, so at scale 1 pixel x + i samples texel u0 + i for every i in
// 0..7 — one texel per pixel, no rounding, no bleed into the next cell. At scale s
// the step is 1/s and each texel is a clean s x s block.
//
// CLAMP is the mapping because it can never be reached: nothing here generates a
// coordinate outside the atlas. It is the honest choice anyway — TILE would hide a
// future arithmetic mistake by wrapping it into a plausible-looking glyph.
inline void rv_text_glyph_quad(const rv_text_style& style, int glyph_index, int x, int y,
                               rv_pdk::rv_primitive& out) {
    const int scale = rv_text_scale_clamp(style.scale);
    const int size_x = rv_font_cell_width * scale;
    const int size_y = rv_font_cell_height * scale;

    const int u0 = rv_text_cell_u(glyph_index);
    const int v0 = rv_text_cell_v(glyph_index);
    const int u1 = u0 + rv_font_cell_width;
    const int v1 = v0 + rv_font_cell_height;

    out = rv_pdk::rv_primitive{};
    out.type = rv_pdk::RV_PRIMITIVE_POLYGON;
    out.depth = style.depth;

    rv_pdk::rv_polygon& polygon = out.data.polygon;
    polygon.fill_mode = rv_pdk::RV_PRIMITIVE_FILL_MODE_SAMPLE_TEXTURE;
    polygon.addr_texture = style.addr_texture;
    polygon.addr_palette = style.addr_palette;
    polygon.mapping = rv_pdk::RV_TEXWRAP_CLAMP;
    polygon.vertex_count = 4;

    // Z order, not rim order: the console splits a quad into (1,2,3) and (2,3,4).
    polygon.vertexes[0] = rv_text_detail::corner(x, y, u0, v0);                    // top-left
    polygon.vertexes[1] = rv_text_detail::corner(x + size_x, y, u1, v0);           // top-right
    polygon.vertexes[2] = rv_text_detail::corner(x, y + size_y, u0, v1);           // bottom-left
    polygon.vertexes[3] = rv_text_detail::corner(x + size_x, y + size_y, u1, v1);  // bottom-right
}

// Lay out `text` starting at (x, y) — the upper-left pixel of the first cell — and
// hand every glyph's primitive to `sink`, which is called as sink(const
// rv_pdk::rv_primitive&). Returns how many primitives were produced.
//
// NOTHING IS ALLOCATED. This runs once per string per frame; a std::vector here
// would put a heap allocation in the frame loop of a machine that is pretending to
// be a 1994 console. The caller either files each primitive straight into
// rv_cv::frame_put from the sink, or writes into a buffer it already owns (see the
// overload below).
//
// '\n' returns the pen to `x` and drops it one line. Spaces advance without
// producing a primitive. Every other byte draws, including the notdef block for
// anything outside printable ASCII — a stray '\r' from CRLF text prints a solid
// slab, which is the file telling you about its line endings.
template <typename Sink>
inline std::size_t rv_text_draw(const rv_text_style& style, int x, int y, std::string_view text,
                                Sink&& sink) {
    const int scale = rv_text_scale_clamp(style.scale);
    const int advance = rv_font_cell_width * scale;
    const int line_height = rv_font_cell_height * scale;

    int pen_x = x;
    int pen_y = y;
    std::size_t emitted = 0;

    for (const char c : text) {
        if (c == '\n') {
            pen_x = x;
            pen_y += line_height;
            continue;
        }
        if (c == ' ') {
            pen_x += advance;
            continue;
        }

        rv_pdk::rv_primitive primitive{};
        rv_text_glyph_quad(style, rv_text_glyph_index(c), pen_x, pen_y, primitive);
        sink(static_cast<const rv_pdk::rv_primitive&>(primitive));
        ++emitted;

        pen_x += advance;
    }
    return emitted;
}

// The same, into a caller-provided array. Writes at most `capacity` primitives and
// returns how many it wrote; ask rv_text_primitive_count first if you need to know
// whether the whole string fits. Truncation is silent by design — a HUD that runs
// out of buffer should lose its tail, not stop the frame.
inline std::size_t rv_text_draw(const rv_text_style& style, int x, int y, std::string_view text,
                                rv_pdk::rv_primitive* out, std::size_t capacity) {
    if (out == nullptr) return 0;
    std::size_t written = 0;
    rv_text_draw(style, x, y, text, [&](const rv_pdk::rv_primitive& primitive) {
        if (written < capacity) out[written++] = primitive;
    });
    return written;
}

}  // namespace rv_pdklib
