// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 0 — reserve/commit memory arena.
// ──────────────────────────────────────────────────────────────────────────────
//
// A single mmap reservation whose pages become usable a piece at a time.
// Reserving up front (PROT_NONE, no physical pages) and committing on demand
// (mprotect + MADV_POPULATE_WRITE) lets a caller size an arena for its worst
// case without paying for it until it is actually touched.
#pragma once

#include <cstdint>

namespace rv_3dmppc {

// Reserved address space, made usable a piece at a time.
class rv_pcarena {
   public:
    // Reserves `reserve_bytes` of address space, PROT_NONE. Nothing is usable
    // yet. A zero or negative size reserves nothing and stays valid().
    explicit rv_pcarena(int64_t reserve_bytes);
    ~rv_pcarena();

    rv_pcarena(const rv_pcarena &) = delete;
    rv_pcarena &operator=(const rv_pcarena &) = delete;

    // False when the reservation itself failed.
    bool valid() const;

    int64_t reserved() const;
    int64_t committed() const;

    // Base of the reservation. Only the first committed() bytes may be touched.
    uint8_t *base() const;

    // Make sure the first `bytes` of the reservation are readable and writable
    // and their pages are populated. Monotonic: a request below committed() is
    // a no-op returning RV_OK. Returns RV_OK, RV_ERR_INVAL when `bytes` is
    // negative or above reserved(), or RV_ERR_NOMEM when the pages cannot be
    // prepared. On failure committed() is unchanged and NOTHING new is handed
    // out, even if madvise populated part of the range.
    int64_t commit(int64_t bytes);

   private:
    uint8_t *base_ = nullptr;
    int64_t reserved_ = 0;
    int64_t committed_ = 0;
    bool valid_ = true;
};

// Does this kernel actually implement MADV_POPULATE_WRITE? The constant being
// present in the headers is not enough. Performs a real one-page probe.
// Returns RV_OK, or RV_ERR_NOENT when the kernel rejects it.
int64_t rv_pcarena_probe_populate_write();

// Self-check for rv_pcarena. Uses assert; aborts on first violation. Nothing
// in the tree calls this yet.
bool rv_pcarena_selfcheck();

}  // namespace rv_3dmppc
