// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — zip central directory parsing and entry reads.
// ──────────────────────────────────────────────────────────────────────────────
#include "rv_pconsole/cd/rv_pczip.hpp"

#include <algorithm>
#include <array>
#include <cstring>
#include <format>

#include "pdklib/rv_logs.hpp"

namespace rv_3dmppc {

namespace {

// Signatures, as the 32-bit little-endian values they decode to.
constexpr uint32_t kSigEocd = 0x06054b50u;   // PK\x05\x06
constexpr uint32_t kSigCdir = 0x02014b50u;   // PK\x01\x02
constexpr uint32_t kSigLocal = 0x04034b50u;  // PK\x03\x04

// Fixed parts of the three records, ahead of their variable-length tails.
constexpr int64_t kEocdSize = 22;
constexpr int64_t kCdirSize = 46;
constexpr int64_t kLocalSize = 30;

// The archive comment length is a uint16, so the EOCD record can sit at most
// this many bytes away from the end of the file.
constexpr int64_t kMaxComment = 65535;

// The only compression method this container admits. See the header for why.
constexpr uint16_t kMethodStore = 0;

// An all-ones field is zip's "the real value is in a zip64 extra record"
// sentinel. This reader has no zip64 support, so the sentinel is refused rather
// than used as a number — using it would mean seeking to 4 GiB - 1 and reading
// whatever is there.
constexpr uint32_t kZip64Sentinel = 0xffffffffu;
constexpr uint16_t kZip64Sentinel16 = 0xffffu;

// Sanity ceilings. Neither is a format limit; both exist so that a lying header
// costs a rejection rather than an allocation. The central directory is already
// bounded by the file size, but a 2 GiB "directory" inside a 2 GiB file is still
// a 2 GiB allocation, and no real disc index comes close to 32 MiB.
constexpr int64_t kMaxDirectoryBytes = 32 * 1024 * 1024;
constexpr std::size_t kMaxEntries = 65536;

// Chunk used when streaming an entry's bytes through the CRC. Bounded so that
// verifying a large entry never doubles its memory cost.
constexpr int64_t kCrcChunk = 64 * 1024;

uint16_t rd16(const unsigned char* p) {
    return static_cast<uint16_t>(static_cast<unsigned>(p[0]) | (static_cast<unsigned>(p[1]) << 8));
}

uint32_t rd32(const unsigned char* p) {
    return static_cast<uint32_t>(p[0]) | (static_cast<uint32_t>(p[1]) << 8) |
           (static_cast<uint32_t>(p[2]) << 16) | (static_cast<uint32_t>(p[3]) << 24);
}

// THEOREM: CRC-32/ISO-HDLC — the checksum zip stores. Reflected input and
// output, polynomial 0xedb88320, pre- and post-inverted. It is written out here
// instead of being pulled from zlib because the whole point of the store-only
// container is that the console links no compression library at all; a 256-entry
// table is a cheaper dependency than any of them.
const std::array<uint32_t, 256>& crc_table() {
    static const std::array<uint32_t, 256> table = [] {
        std::array<uint32_t, 256> t{};
        for (uint32_t i = 0; i < 256; ++i) {
            uint32_t c = i;
            for (int k = 0; k < 8; ++k) c = (c & 1u) ? (0xedb88320u ^ (c >> 1)) : (c >> 1);
            t[i] = c;
        }
        return t;
    }();
    return table;
}

// Running CRC: `state` is the value carried between chunks, starting at 0.
uint32_t crc32_update(uint32_t state, const void* data, std::size_t size) {
    const auto& table = crc_table();
    uint32_t c = state ^ 0xffffffffu;
    const unsigned char* p = static_cast<const unsigned char*>(data);
    for (std::size_t i = 0; i < size; ++i) c = table[(c ^ p[i]) & 0xffu] ^ (c >> 8);
    return c ^ 0xffffffffu;
}

}  // namespace

bool rv_zipreader::open(const std::string& path, std::string& error) {
    ok_ = false;
    entries_.clear();
    by_name_.clear();
    file_.close();
    file_.clear();
    path_ = path;
    file_size_ = 0;

    file_.open(path, std::ios::binary);
    if (!file_) {
        error = "cannot open archive";
        return false;
    }

    file_.seekg(0, std::ios::end);
    const std::streamoff end = file_.tellg();
    if (!file_ || end < 0) {
        error = "cannot measure archive";
        file_.close();
        return false;
    }
    file_size_ = static_cast<int64_t>(end);

    if (file_size_ < kEocdSize) {
        error = "file is smaller than an empty zip archive";
        file_.close();
        return false;
    }

    if (!parse_directory(error)) {
        entries_.clear();
        by_name_.clear();
        file_.close();
        file_.clear();
        return false;
    }

    ok_ = true;
    return true;
}

bool rv_zipreader::read_at(int64_t offset, void* dst, int64_t count) const {
    if (count == 0) return true;
    file_.clear();
    file_.seekg(static_cast<std::streamoff>(offset), std::ios::beg);
    if (!file_) return false;
    file_.read(static_cast<char*>(dst), static_cast<std::streamsize>(count));
    return file_.gcount() == static_cast<std::streamsize>(count);
}

// THEOREM: backward search for the End Of Central Directory record — the EOCD is
// the only way into a zip (it says where the central directory starts), and it is
// NOT simply the last 22 bytes. The record ends with a variable-length archive
// comment of up to 65535 bytes, so an archive with any comment at all puts the
// record further from the end, and "read the last 22 bytes" then finds nothing
// and declares a perfectly good archive corrupt. The signature must therefore be
// searched for, backwards, across the last kEocdSize + kMaxComment bytes.
//
// Backwards, and not forwards, for a second reason: `PK\x05\x06` is four ordinary
// bytes that can also occur inside stored file data or inside the comment itself.
// A forward scan can stop on such an impostor; the real record is the LAST
// plausible one, so scanning from the end and taking the first hit is what makes
// the search deterministic. "Plausible" is then checked properly — the comment
// length field must account for exactly the bytes that follow the record, which
// is what tells a real EOCD from four coincidental bytes of a texture.
bool rv_zipreader::find_eocd(const std::vector<unsigned char>& tail, std::size_t& pos) {
    if (tail.size() < static_cast<std::size_t>(kEocdSize)) return false;

    for (std::size_t i = tail.size() - static_cast<std::size_t>(kEocdSize) + 1; i-- > 0;) {
        if (rd32(tail.data() + i) != kSigEocd) continue;

        const std::size_t comment_len = rd16(tail.data() + i + 20);
        const std::size_t after = tail.size() - i - static_cast<std::size_t>(kEocdSize);
        if (comment_len != after) continue;  // impostor: the tail does not add up

        pos = i;
        return true;
    }
    return false;
}

bool rv_zipreader::parse_directory(std::string& error) {
    const int64_t tail_size = std::min<int64_t>(file_size_, kEocdSize + kMaxComment);
    std::vector<unsigned char> tail(static_cast<std::size_t>(tail_size));
    if (!read_at(file_size_ - tail_size, tail.data(), tail_size)) {
        error = "cannot read the end of the archive";
        return false;
    }

    std::size_t eocd_pos = 0;
    if (!find_eocd(tail, eocd_pos)) {
        error = "no end-of-central-directory record: this is not a zip archive";
        return false;
    }

    const unsigned char* eocd = tail.data() + eocd_pos;
    const uint16_t disk = rd16(eocd + 4);
    const uint16_t cd_disk = rd16(eocd + 6);
    const uint16_t entries_here = rd16(eocd + 8);
    const uint16_t entries_total = rd16(eocd + 10);
    const uint32_t cd_size = rd32(eocd + 12);
    const uint32_t cd_offset = rd32(eocd + 16);

    if (disk != 0 || cd_disk != 0 || entries_here != entries_total) {
        error = "split archives are not supported";
        return false;
    }
    if (entries_total == kZip64Sentinel16 || cd_size == kZip64Sentinel ||
        cd_offset == kZip64Sentinel) {
        error = "zip64 archives are not supported";
        return false;
    }

    // Every offset from here on is checked against the REAL file size before it
    // is used, and the subtraction form avoids the overflow that `a + b > size`
    // invites on 32-bit fields promoted to 64-bit arithmetic.
    if (static_cast<int64_t>(cd_offset) > file_size_ ||
        static_cast<int64_t>(cd_size) > file_size_ - static_cast<int64_t>(cd_offset)) {
        error = "central directory lies outside the file";
        return false;
    }
    if (static_cast<int64_t>(cd_size) > kMaxDirectoryBytes) {
        error = "central directory is implausibly large";
        return false;
    }

    std::vector<unsigned char> cdir(static_cast<std::size_t>(cd_size));
    if (!read_at(static_cast<int64_t>(cd_offset), cdir.data(), static_cast<int64_t>(cd_size))) {
        error = "cannot read the central directory (archive is truncated)";
        return false;
    }

    std::size_t p = 0;
    while (p + static_cast<std::size_t>(kCdirSize) <= cdir.size()) {
        const unsigned char* h = cdir.data() + p;
        if (rd32(h) != kSigCdir) {
            // The directory is a chain of records; anything else in the chain
            // means the archive's own index is damaged, and guessing where the
            // next record might start is how a parser reads someone else's bytes.
            error = "damaged central directory record";
            return false;
        }

        const uint16_t method = rd16(h + 10);
        const uint32_t crc = rd32(h + 16);
        const uint32_t csize = rd32(h + 20);
        const uint32_t usize = rd32(h + 24);
        const std::size_t name_len = rd16(h + 28);
        const std::size_t extra_len = rd16(h + 30);
        const std::size_t comment_len = rd16(h + 32);
        const uint32_t lho = rd32(h + 42);

        const std::size_t record =
            static_cast<std::size_t>(kCdirSize) + name_len + extra_len + comment_len;
        if (record > cdir.size() - p) {
            error = "central directory record runs past the directory";
            return false;
        }

        const std::string name(reinterpret_cast<const char*>(h + kCdirSize), name_len);
        p += record;

        if (name.empty()) {
            RV_LOG_WARN("pczip", "archive '{}' has an entry with an empty name; ignored", path_);
            continue;
        }

        if (method != kMethodStore) {
            // The container is store-only by design (see the header). Refusing
            // the whole archive — rather than skipping the entry — is deliberate:
            // a disc whose assets are compressed was not burned for this console,
            // and letting it half-mount would turn one clear message into a
            // scattering of RV_ERR_NOENT during play.
            //
            // TODO(rv_log_escape): 12 calls in this file. The console is its only
            // caller, so it does not belong in pdklib — find it a console-side home.
            error = std::format(
                "entry '{}' uses compression method {}; this container is "
                "store-only (no decompressor on the console)",
                rv_pdklib::rv_log_escape(name.c_str()), method);
            return false;
        }
        if (csize == kZip64Sentinel || usize == kZip64Sentinel || lho == kZip64Sentinel) {
            error = std::format("entry '{}' needs zip64, which is not supported",
                                rv_pdklib::rv_log_escape(name.c_str()));
            return false;
        }
        if (csize != usize) {
            error = std::format("entry '{}' is stored but its sizes disagree ({} vs {})",
                                rv_pdklib::rv_log_escape(name.c_str()), csize, usize);
            return false;
        }
        // The local header must at least FIT before its offset is ever seeked to.
        // The data bounds cannot be settled here — they depend on the local
        // header's own name/extra lengths — and are re-checked in read().
        if (static_cast<int64_t>(lho) > file_size_ - kLocalSize) {
            error =
                std::format("entry '{}' points outside the archive", rv_pdklib::rv_log_escape(name.c_str()));
            return false;
        }

        if (entries_.size() >= kMaxEntries) {
            error = "archive declares implausibly many entries";
            return false;
        }

        if (by_name_.find(name) != by_name_.end()) {
            // Duplicate names are legal zip and ambiguous data. First one wins,
            // loudly: the alternative is a disc where which texture you get
            // depends on parse order.
            RV_LOG_WARN("pczip", "archive '{}' repeats entry '{}'; the later copy is ignored",
                        path_, rv_pdklib::rv_log_escape(name.c_str()));
            continue;
        }

        rv_zipentry entry;
        entry.name = name;
        entry.local_header_offset = static_cast<int64_t>(lho);
        entry.size = static_cast<int64_t>(usize);
        entry.crc32 = crc;
        by_name_.emplace(entry.name, entries_.size());
        entries_.push_back(std::move(entry));
    }

    if (entries_.size() != static_cast<std::size_t>(entries_total)) {
        // Not fatal: what was actually parsed is what exists. Worth saying,
        // because it is the fingerprint of a truncated or hand-edited archive.
        RV_LOG_WARN("pczip", "archive '{}' declares {} entries but {} were parsed", path_,
                    entries_total, entries_.size());
    }
    return true;
}

const rv_zipentry* rv_zipreader::find(const char* name) const {
    if (!ok_ || name == nullptr || name[0] == '\0') return nullptr;
    const auto it = by_name_.find(std::string(name));
    if (it == by_name_.end()) return nullptr;
    return &entries_[it->second];
}

int64_t rv_zipreader::size(const char* name) const {
    const rv_zipentry* entry = find(name);
    return entry == nullptr ? -1 : entry->size;
}

rv_zipread rv_zipreader::read(const char* name, void* baddr, int64_t cap, int64_t& nread) const {
    nread = 0;
    if (!ok_) return rv_zipread::io_error;
    if (cap < 0 || (baddr == nullptr && cap > 0)) return rv_zipread::short_buffer;

    const rv_zipentry* entry = find(name);
    if (entry == nullptr) return rv_zipread::not_found;

    // The directory record is COPIED out before a single byte lands in `baddr`.
    // `baddr` is a void* the caller owns, and nothing stops it from overlapping
    // this reader's own storage; re-reading `entry->size` after the transfer
    // would then mean re-reading a field the transfer just rewrote, and every
    // bound checked above would be a bound about the past. The locals are also
    // what makes each cast to size_t provably in range.
    const int64_t lho = entry->local_header_offset;
    const int64_t size = entry->size;
    const uint32_t want_crc = entry->crc32;
    // Unreachable by construction — a size comes from a uint32 field — but the
    // check is what turns "by construction" into something the compiler and the
    // next reader can both see.
    if (size < 0 || lho < 0) return rv_zipread::corrupt;
    if (cap < size) return rv_zipread::short_buffer;
    if (size > 0 && baddr == nullptr) return rv_zipread::short_buffer;

    // THEOREM: the data offset comes from the LOCAL header, never from the
    // central directory. The two headers describe the same entry twice, and the
    // lengths of their `name` and `extra` fields are INDEPENDENT: writers
    // routinely put a zip64/timestamp/unix-uid extra field in one and not the
    // other, so `local_header_offset + 46 + cdir_name_len + cdir_extra_len` is
    // not where the bytes are. The only correct route is to seek to
    // local_header_offset, read the 30-byte fixed local header, and take ITS
    // name/extra lengths: data begins at lho + 30 + local_name_len +
    // local_extra_len. Computing it from the central directory instead is the
    // classic zip-reader bug — it lands a few bytes off and yields plausible
    // garbage rather than an error, which is the worst possible failure mode for
    // a texture or a model.
    unsigned char lh[kLocalSize];
    if (!read_at(lho, lh, kLocalSize)) {
        RV_LOG_ERR("pczip", "entry '{}': local header unreadable", rv_pdklib::rv_log_escape(name));
        return rv_zipread::corrupt;
    }
    if (rd32(lh) != kSigLocal) {
        RV_LOG_ERR("pczip", "entry '{}': no local header at its offset", rv_pdklib::rv_log_escape(name));
        return rv_zipread::corrupt;
    }
    if (rd16(lh + 8) != kMethodStore) {
        RV_LOG_ERR("pczip", "entry '{}': local header claims compression method {}",
                   rv_pdklib::rv_log_escape(name), rd16(lh + 8));
        return rv_zipread::corrupt;
    }

    const int64_t local_name_len = rd16(lh + 26);
    const int64_t local_extra_len = rd16(lh + 28);
    const int64_t data_offset = lho + kLocalSize + local_name_len + local_extra_len;

    // Bounds first, seek second — always in that order, and phrased as
    // subtraction so nothing can wrap.
    if (data_offset > file_size_ || size > file_size_ - data_offset) {
        RV_LOG_ERR("pczip", "entry '{}': data lies outside the archive", rv_pdklib::rv_log_escape(name));
        return rv_zipread::corrupt;
    }

    if (size == 0) {
        // An empty entry is a legal entry. Its CRC is 0 by definition; anything
        // else means the directory is lying about it.
        if (want_crc != 0) {
            RV_LOG_ERR("pczip", "entry '{}': empty but claims a checksum", rv_pdklib::rv_log_escape(name));
            return rv_zipread::crc_mismatch;
        }
        return rv_zipread::ok;
    }

    if (!read_at(data_offset, baddr, size)) {
        std::memset(baddr, 0, static_cast<std::size_t>(size));
        RV_LOG_ERR("pczip", "entry '{}': short read of {} bytes", rv_pdklib::rv_log_escape(name), size);
        return rv_zipread::io_error;
    }

    // Verify what was just delivered. This is the cheap half of "the disc may be
    // rotten": the structure checks above catch an archive that lies about WHERE
    // the bytes are, and the CRC catches one that is honest about the location
    // and wrong about the contents — a flipped bit in storage, a truncated
    // download, a half-finished burn. Without it such a disc renders as noise and
    // gets reported as a game bug.
    uint32_t crc = 0;
    const unsigned char* p = static_cast<const unsigned char*>(baddr);
    for (int64_t done = 0; done < size; done += kCrcChunk) {
        const int64_t chunk = std::min<int64_t>(kCrcChunk, size - done);
        crc = crc32_update(crc, p + done, static_cast<std::size_t>(chunk));
    }
    if (crc != want_crc) {
        std::memset(baddr, 0, static_cast<std::size_t>(size));
        RV_LOG_ERR("pczip", "entry '{}': checksum mismatch (have {:08x}, expected {:08x})",
                   rv_pdklib::rv_log_escape(name), crc, want_crc);
        return rv_zipread::crc_mismatch;
    }

    nread = size;
    return rv_zipread::ok;
}

}  // namespace rv_3dmppc
