// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — medium implementation on top of a .mppcdisc archive.
// ──────────────────────────────────────────────────────────────────────────────
#include "rv_pconsole/cd/rv_pczipmedium.hpp"

#include "pdk/rv_err.hpp"
#include "rv_infra/rv_log.hpp"

namespace rv_3dmppc {

// The contract's vocabulary, unqualified for the bodies below only. Never in a
// header: a using-directive there would leak into every translation unit that
// includes it.
using namespace rv_pdk;

namespace {

bool has_separator(const std::string& name) {
    return name.find('/') != std::string::npos || name.find('\\') != std::string::npos;
}

bool is_service_entry(const std::string& name) {
    return name == kDiscManifestEntry || name == kDiscCodeEntry;
}

}  // namespace

rv_pczipmedium::rv_pczipmedium(const std::string& archive_path) {
    if (archive_path.empty()) {
        // No disc in the drive. Quiet on purpose: a console booted with no game
        // is a legal machine, exactly as with the directory medium.
        RV_LOG_INFO("pczipmedium", "no archive path configured; drive is empty");
        return;
    }

    std::string error;
    if (!zip_.open(archive_path, error)) {
        // Worth shouting about — someone inserted something that is not a disc —
        // but the machine stays usable, just empty. `error` is the reader's own
        // wording and may quote an entry name from the archive, which is why the
        // reader escapes those before they get here.
        RV_LOG_ERR("pczipmedium", "cannot mount archive '{}': {}; drive stays empty", archive_path,
                   error);
        return;
    }

    // Build the asset namespace: everything in the archive except the service
    // entries and the names a resource name cannot legally be.
    int64_t nested = 0;
    for (const rv_zipentry& entry : zip_.entries()) {
        if (is_service_entry(entry.name)) continue;

        if (has_separator(entry.name)) {
            // Counted, not announced one by one: a foreign zip can hold thousands
            // of nested names and the log is not the place to enumerate them.
            ++nested;
            continue;
        }
        if (!rv_pcresname_valid(entry.name.c_str())) {
            RV_LOG_WARN("pczipmedium", "archive entry '{}' is not a legal resource name; ignored",
                        rv_log_escape(entry.name.c_str()));
            continue;
        }
        if (!assets_.insert(entry.name).second) continue;
        asset_names_.push_back(entry.name);
    }

    if (nested > 0) {
        // Said ONCE, and said plainly: a nested name is either a zip that was
        // never burned by mppcburner or a packaging bug. Guessing a flat name out
        // of it would be worse than not seeing it, because the guess collides
        // silently.
        RV_LOG_WARN("pczipmedium",
                    "archive '{}' holds {} entr{} with path separators; a disc's asset names are "
                    "flat, so they are not visible to the game",
                    archive_path, nested, nested == 1 ? "y" : "ies");
    }

    mounted_ = true;
    RV_LOG_INFO("pczipmedium", "mounted archive medium '{}' ({} asset(s))", archive_path,
                asset_names_.size());
}

bool rv_pczipmedium::visible(const char* resname) const {
    // The name gate runs BEFORE the lookup, for the same reason as in the
    // directory medium: a name is a name, not a path, and a name that tries to be
    // a path is refused rather than resolved. Here it cannot escape anywhere
    // (there is no filesystem below), but the two media must agree on what exists
    // — a disc that behaves differently unpacked than burned is the worst kind of
    // bug to chase.
    if (!mounted_ || !rv_pcresname_valid(resname)) return false;
    return assets_.find(std::string(resname)) != assets_.end();
}

int64_t rv_pczipmedium::entry_size(const char* resname) const {
    if (!visible(resname)) return RV_ERR_NOENT;

    const int64_t size = zip_.size(resname);
    if (size < 0) return RV_ERR_NOENT;
    return size;
}

int64_t rv_pczipmedium::entry_read(const char* resname, void* baddr, int64_t cap) const {
    if (baddr == nullptr || cap < 0) return RV_ERR_INVAL;
    if (!visible(resname)) return RV_ERR_NOENT;

    int64_t nread = 0;
    const rv_zipread rc = zip_.read(resname, baddr, cap, nread);
    switch (rc) {
        case rv_zipread::ok:
            return nread;
        case rv_zipread::not_found:
            // The namespace said it was there, the archive says it is not: the
            // two views can only disagree if the table was built from a different
            // archive, so answer the honest RV_ERR_NOENT.
            return RV_ERR_NOENT;
        case rv_zipread::short_buffer:
            RV_LOG_WARN("pczipmedium", "entry '{}' needs {} bytes, buffer holds {}",
                        rv_log_escape(resname), zip_.size(resname), cap);
            return RV_ERR_INVAL;
        case rv_zipread::corrupt:
        case rv_zipread::crc_mismatch:
        case rv_zipread::io_error:
            // All three are "the device failed a well-formed call". The drive's
            // vocabulary has one code for that; the reader has already logged
            // which of the three it actually was, and the distinction matters to
            // whoever burned the disc, not to the game.
            return RV_ERR_IO;
    }
    return RV_ERR_IO;
}

}  // namespace rv_3dmppc
