// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — reading the .mppcdisc zip container (store method only).
// ──────────────────────────────────────────────────────────────────────────────
//
// Reads the `.mppcdisc` container: a plain zip in which EVERY entry is STORED
// (method 0, no compression). The writer on the other side is
// pdk/tools/mppcburner/rv_zipwrite.*.
//
// WHY STORE-ONLY. A stored entry is served with one seek and one read at an
// offset the archive itself hands us. That is the whole reason the format was
// frozen this way: the console then needs no zlib, no decompressor and no
// streaming state machine — the component that eats files downloaded from the
// internet stays small enough to audit. An entry announcing any other method is
// therefore REFUSED with a plain diagnostic instead of being decoded on a wing
// and a prayer; supporting compression, if it ever earns its place, is a bump of
// the container version and not a quiet branch in here.
//
// This reader is deliberately ignorant of the PDK: no rv_err, no rv_cd, no
// notion of a "resource". It knows files, entries and bytes. The PDK verdicts
// are added one layer up, in rv_pczipmedium.*, and the loader can reuse this
// class as-is to fetch the service entries (disc.toml, disc.so) that never
// belong to the asset namespace.
//
// ROBUSTNESS IS THE POINT. Every field read out of the archive is attacker-
// controlled: sizes, offsets and name lengths may lie. Nothing here indexes,
// seeks or allocates on such a field before it has been checked against the real
// file size, and no failure mode is worse than "open() returns false with a
// reason".
#pragma once

#include <cstddef>
#include <cstdint>
#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace rv_3dmppc {

// One entry, as described by the central directory. `size` is both the stored
// and the uncompressed size, because the two are equal by construction for
// method 0 — an archive claiming otherwise is refused at parse time.
struct rv_zipentry {
    std::string name;
    int64_t local_header_offset = 0;
    int64_t size = 0;
    uint32_t crc32 = 0;
};

// Outcome of reading one entry. Deliberately finer-grained than rv_err: the
// medium collapses these onto the drive's vocabulary, and the extra detail is
// what makes a corrupt disc diagnosable from a log line.
enum class rv_zipread : int {
    ok = 0,
    not_found,     // no entry by that name
    short_buffer,  // the caller's buffer is smaller than the entry
    corrupt,       // the archive's own bookkeeping does not hold up
    crc_mismatch,  // the bytes are there but are not the bytes that were written
    io_error,      // the host file failed a well-formed request
};

// A mounted archive. The file stays OPEN for the object's whole life and is read
// on demand: a disc is mounted for the length of a game, and slurping it into
// RAM up front would mean holding every model and texture resident at once for
// the sake of the few that are in use.
class rv_zipreader {
   public:
    rv_zipreader() = default;
    ~rv_zipreader() = default;

    rv_zipreader(const rv_zipreader&) = delete;
    rv_zipreader& operator=(const rv_zipreader&) = delete;

    // Open `path` and parse its central directory. Returns false and fills
    // `error` with a human-readable reason on any failure — a missing file, a
    // file that is not a zip, a truncated one, a compressed one, or one whose
    // fields point outside itself. A failed open leaves the object closed and
    // empty; it is never half-usable.
    bool open(const std::string& path, std::string& error);

    // True once open() has succeeded.
    bool ok() const { return ok_; }

    // Path the archive was opened from (empty when never opened).
    const std::string& path() const { return path_; }

    bool has(const char* name) const { return find(name) != nullptr; }

    // Size in bytes of `name`, or -1 when there is no such entry.
    int64_t size(const char* name) const;

    // Copy the WHOLE entry into `baddr` (capacity `cap` bytes) and verify its
    // CRC32. `nread` receives the byte count on success and 0 otherwise. The
    // reader never allocates the destination and never writes past `cap`; on any
    // failure the region it may have touched is zeroed, so a caller cannot
    // mistake half an entry for a whole one.
    rv_zipread read(const char* name, void* baddr, int64_t cap, int64_t& nread) const;

    // Every entry, in central-directory order. The loader enumerates to find the
    // service entries, the medium enumerates to build the asset namespace, and a
    // human enumerates to find out why a disc is empty.
    const std::vector<rv_zipentry>& entries() const { return entries_; }

   private:
    // Parse the central directory into `entries_`/`by_name_`.
    bool parse_directory(std::string& error);

    // Locate the End Of Central Directory record inside `tail`, which is the
    // last bytes of the file. Returns false when there is none.
    static bool find_eocd(const std::vector<unsigned char>& tail, std::size_t& pos);

    const rv_zipentry* find(const char* name) const;

    // Seek + read exactly `count` bytes at `offset`. False on any short read;
    // the caller has already bounds-checked `offset`/`count` against file_size_.
    bool read_at(int64_t offset, void* dst, int64_t count) const;

    // The archive is read through a const interface (the medium is const), but
    // reading moves a file position: the stream is mutable state behind a
    // logically const query, exactly like a cache.
    mutable std::ifstream file_;
    std::string path_;
    int64_t file_size_ = 0;

    std::vector<rv_zipentry> entries_;
    std::unordered_map<std::string, std::size_t> by_name_;
    bool ok_ = false;
};

}  // namespace rv_3dmppc
