// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — medium backed by a .mppcdisc archive.
// ──────────────────────────────────────────────────────────────────────────────
//
// The disc as it actually ships: one `.mppcdisc` file instead of a directory.
//
// PATTERN: strategy (second implementation) — this is the payoff promised in
// rv_pcmedium.hpp. rv_pccd owns the CONTRACT (legal names, handles, which rv_err
// a situation deserves) and an rv_pcmedium owns the STORAGE, so a whole new kind
// of storage arrives here without a single line changing in rv_pccd: the drive
// never learns whether the bytes it forwards came out of a directory or out of a
// zip, and cannot be made to care. The only thing that picks between them is
// whoever constructs the medium.
//
// The asset namespace this medium exposes is deliberately NARROWER than the
// archive's contents:
//   * entries whose name contains a path separator are dropped, because a
//     resource name is flat by contract (rv_cd::asset_open) and the burner writes
//     flat names — a nested name is either a foreign zip or a packaging bug, and
//     inventing a mapping ("use the basename") would silently merge
//     `hud/font.tex` with `ui/font.tex`;
//   * the service entries disc.toml and disc.so are hidden, because they are how
//     the console loads the disc, not data the disc reads back. The loader gets
//     them from an rv_zipreader directly.
#pragma once

#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>

#include "rv_pconsole/cd/rv_pcmedium.hpp"
#include "rv_pconsole/cd/rv_pczip.hpp"

namespace rv_3dmppc {

// Entries the console owns. They live in the same archive as the assets but not
// in the same namespace: a disc does not read itself as data.
inline constexpr const char* kDiscManifestEntry = "disc.toml";
inline constexpr const char* kDiscCodeEntry = "disc.so";

class rv_pczipmedium : public rv_pcmedium {  // PATTERN: strategy
   public:
    // An empty `archive_path` means "no disc inserted" and is not a failure. A
    // path that is not a readable store-only zip IS reported (loudly) but still
    // leaves the drive merely empty rather than broken — a bad disc must not take
    // the console down with it.
    explicit rv_pczipmedium(const std::string& archive_path);

    bool mounted() const override { return mounted_; }

    int64_t entry_size(const char* resname) const override;
    int64_t entry_read(const char* resname, void* baddr, int64_t cap) const override;

    // The asset names the game can see, in archive order. Not part of the medium
    // contract (rv_cd has no enumeration): this is for the loader and for the
    // answer to "why does my disc say RV_ERR_NOENT".
    const std::vector<std::string>& asset_names() const { return asset_names_; }

    // The underlying archive, for the loader that must fetch disc.toml/disc.so —
    // the entries this medium deliberately hides.
    const rv_zipreader& archive() const { return zip_; }

   private:
    // True when `resname` is a legal resource name AND names a visible asset.
    bool visible(const char* resname) const;

    rv_zipreader zip_;
    std::vector<std::string> asset_names_;
    std::unordered_set<std::string> assets_;
    bool mounted_ = false;
};

}  // namespace rv_3dmppc
