#include "rv_pconsole/cl/rv_pccl_luajit.hpp"

#include <cstdlib>
#include <cstring>

// lua.hpp is confined to src/rv_pconsole/cl/rv_pccl_luajit* - the five .cpp
// files of this one class and their detail header. Anywhere else and the PDK
// boundary has leaked.
#include "lua.hpp"

#include "pdklib/rv_logs/rv_logs.hpp"

// Generated by cmake/rv_cdef_gen.cmake into build/rv_pdk_cdef.cpp, compiled
// straight into this executable (see that file for what these two strings
// hold: ffi.cdef-ready C declarations, and a "return { NAME = value, ... }"
// Lua chunk). Declared here at GLOBAL scope on purpose - the generated file
// defines them outside any namespace, so a declaration inside
// rv_3dmppc below would name a different, unlinkable symbol.
extern const char rv_pdk_cdef[];
extern const char rv_pdk_consts[];

namespace rv_3dmppc
{
namespace
{
// luaL_openlibs' own recipe (lib_init.c): only what this console allows.
void open_lib(lua_State *L, const char *name, lua_CFunction f)
{
    lua_pushcfunction(L, f);
    lua_pushstring(L, name);
    lua_call(L, 1, 0); // nresults = 0 drops the module table it returns
}

// The rest of bootstrap_pdk() below (cast/new entries, the lazy __index,
// the boot-time resolve-probe) is written as Lua source and run through
// luaL_loadbuffer, not as raw lua_* stack calls: a closure over `ffi` and a
// setmetatable() are exactly what Lua syntax is for, hand-building both
// through the C API would be far harder to read for no benefit, and running
// it as ONE chunk keeps the whole thing inside a single pcall - so a missing
// PDK symbol (ffi.C raises on an unresolved one) is caught right here
// instead of escaping unprotected into the console's first draw call.
//
// `ffi` and the constants table (about to become `pdk`) arrive as this
// chunk's two varargs. cast/new are assigned directly because they are not
// PDK symbols - ffi.C would never resolve "rv_cast" or "rv_new" - everything
// else reaches ffi.C through the metatable, which has to try TWO shapes: a
// contract FUNCTION is always lowercase-"rv_"-prefixed (rv_cv_frame_put), but
// a cdef'd enum member keeps its full declared name, uppercase "RV_"-prefixed
// (RV_TEXWRAP_CLAMP, pdk/include/pdk/cv/rv_primitives.h) - ffi.cdef already
// taught ffi.C that name verbatim, it is just not the "rv_"+k shape the first
// attempt tries. Either hit is memoised (rawset) so a script writes
// pdk.cv_frame_put(cv, prim) or pdk.TEXWRAP_CLAMP and never says ffi. A key
// that matches NEITHER shape re-raises: an unresolved hardware name must
// fail loudly, not read back as nil (silently "this field is optional").
constexpr const char *RV_PCCL_PDK_BOOTSTRAP_SRC = R"lua(
local ffi, pdk = ...
pdk.cast = ffi.cast
pdk.new = ffi.new

-- ffi.C raises on a symbol it cannot resolve, so trying a shape means
-- catching that raise, not checking a return value.
local function try_symbol(name)
    local ok, v = pcall(function() return ffi.C[name] end)
    if ok then return v end
    return nil
end

setmetatable(pdk, {
    __index = function(t, k)
        local v = try_symbol("rv_" .. k) or try_symbol("RV_" .. k)
        if v == nil then
            error("pdk: no hardware symbol for '" .. k .. "' (tried rv_" .. k ..
                " and RV_" .. k .. ")", 2)
        end
        rawset(t, k, v)
        return v
    end,
})
-- Every hook is handed the organizer as an untyped pointer, so reaching a
-- controller used to cost a script three steps: cast to rv_pdko*, call
-- rv_pdko_<slot>, keep the result. That is the console's plumbing, not the
-- game's, and writing it out in every hook is what PR comment #1 asked to
-- stop. `pdk.cv(o)` does all three. The cast is free (ffi.cast on a pointer
-- is not an allocation) and the accessor is the same exported function the
-- long form called, so this is a shorter spelling of the identical path, not
-- a layer in front of it.
for _, slot in ipairs({ "ca", "cd", "cio", "cl", "cm", "cv" }) do
    local accessor = pdk["pdko_" .. slot]
    pdk[slot] = function(o) return accessor(pdk.cast("rv_pdko*", o)) end
end
local _ = pdk.cv_screen_width -- boot-time proof the wiring actually resolves
)lua";
} // namespace

rv_pcbudget_cost rv_pccl_luajit::evaluate(const rv_pdklib::rv_manifest_budget &budget)
{
    // budget_ (this class's own lua_Alloc ceiling): exactly script_memory_size.
    return { budget.pccl.script_memory_size, {} };
}

rv_pccl_luajit::rv_pccl_luajit(const rv_pccl_conf &conf, rv_pccd &cd)
    : conf_(conf)
    , cd_(cd)
    , budget_(conf.script_memory_size)
{
    L_ = lua_newstate(rv_alloc, this);
    if (L_ == nullptr) {
        RV_LOG_ERR("pccl", "failed to bring up the lua machine ({} byte(s) budgeted)", budget_);
        return; // survive it: no VM is what valid() checks for below
    }
    lua_atpanic(L_, panic);
    // ffi is not a sandbox: a script holding it can read and write any memory
    // of this process. Opening only base/string/math/table keeps io/os out of
    // reach, but that closes accidental doors, not a hostile script's.
    //
    // ONE AT A TIME, never luaL_openlibs: io/os is a hole a disc must not get.
    open_lib(L_, "", luaopen_base);
    open_lib(L_, LUA_STRLIBNAME, luaopen_string);
    open_lib(L_, LUA_MATHLIBNAME, luaopen_math);
    open_lib(L_, LUA_TABLIBNAME, luaopen_table);
    // print() must not reach stdout: that stream carries the development
    // channel's answers, and a chunk printing there would splice its text into
    // a reply the editor is parsing. Replaced unconditionally rather than only
    // under --dev, so a script behaves the same way in both runs and nobody
    // debugs a difference that exists only when the channel is open.
    lua_pushcfunction(L_, print_to_log);
    lua_setglobal(L_, "print");
    if (!bootstrap_pdk()) {
        RV_LOG_ERR("pccl", "pdk bootstrap failed, lua machine going down");
        lua_close(L_);
        L_ = nullptr; // same shape as a failed lua_newstate: valid() below goes false
        return;
    }
    // The persistent state table. Created here, before any chunk exists, and
    // held in the registry until the machine goes down - that lifetime IS the
    // "code != state" guarantee, and it is the reason a reload cannot take the
    // game's data with it.
    lua_newtable(L_);
    state_ref_ = luaL_ref(L_, LUA_REGISTRYINDEX);
    // The entry chunk's own environment, built once and reused for every
    // raise of the entry from here on: a plain table whose metatable falls
    // reads through to the real globals table (so `pdk`, `print`, `require`
    // and the opened stdlib still resolve) but declares no __newindex, so a
    // write the script never made `local` lands in this table and never
    // touches _G. `state` is set into it right here, once - the same table
    // state_ref_ names for the whole run, handed to every future candidate
    // by nothing more than pointing its closure at this one environment.
    lua_newtable(L_); // the environment
    lua_newtable(L_); // its metatable
    lua_pushvalue(L_, LUA_GLOBALSINDEX);
    lua_setfield(L_, -2, "__index");
    lua_setmetatable(L_, -2);
    lua_rawgeti(L_, LUA_REGISTRYINDEX, state_ref_);
    lua_setfield(L_, -2, "state");
    entry_env_ref_ = luaL_ref(L_, LUA_REGISTRYINDEX);
    // require()'s loaded-module table and the global itself. A game feature,
    // not a dev tool: installed in both builds.
    lua_newtable(L_);
    loaded_ref_ = luaL_ref(L_, LUA_REGISTRYINDEX);
    lua_pushcfunction(L_, require_);
    lua_setglobal(L_, "require");
    // Made now, while there is heap to make it: every protected console call
    // (protected_call_) enters through this one closure afterwards.
    lua_pushcfunction(L_, protected_invoke_);
    invoke_ref_ = luaL_ref(L_, LUA_REGISTRYINDEX);
    RV_LOG_INFO("pccl", "lua machine up, {} byte(s) budgeted", budget_);
}
// No VM to close is not a failure: the ctor already logged why L_ is null.
rv_pccl_luajit::~rv_pccl_luajit()
{
    if (L_ != nullptr) {
        lua_close(L_);
    }
}
// L_ null is the only FALSE - the ctor already logged why. Every method
// below skips the "is a VM up" guard the old rv_pccl.cpp had: a factory
// upstream only ever builds this class for a disc that declared a lua
// machine, and the console refuses to boot when valid() answers false, so no
// contract method is ever reached with L_ null.
bool rv_pccl_luajit::valid() const
{
    return L_ != nullptr;
}
// lua_Alloc: refuses to push used_ past budget_. ptr==nullptr means a fresh
// block, so osize is then a type tag, not a size (lua_Alloc contract).
void *rv_pccl_luajit::rv_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
{
    rv_pccl_luajit *self = static_cast<rv_pccl_luajit *>(ud);
    if (nsize == 0) {
        if (ptr != nullptr) {
            self->used_ -= static_cast<int64_t>(osize);
        }
        std::free(ptr);
        return nullptr;
    }
    const int64_t old_size = ptr != nullptr ? static_cast<int64_t>(osize) : 0;
    const int64_t delta = static_cast<int64_t>(nsize) - old_size;
    // Only growth is checked; NULL is not a crash - Lua turns it into a
    // catchable "not enough memory" error, a ceiling the script hits.
    if (delta > 0 && self->used_ + delta > self->budget_) {
        // Remembered, because Lua turns this null into an ordinary catchable
        // error: without the flag, "out of script memory" and "your chunk threw"
        // arrive as the same failed pcall and the report would have to guess
        // from the message text.
        self->oom_ = true;
        return nullptr;
    }
    void *out = std::realloc(ptr, nsize);
    if (out == nullptr) {
        return nullptr; // real failure; used_ untouched
    }
    self->used_ += delta;
    return out;
}
// Installed via lua_atpanic: an error outside pcall would otherwise abort() silently.
int rv_pccl_luajit::panic(lua_State *L)
{
    const char *msg = lua_tostring(L, -1);
    RV_LOG_EMERG("pccl", "unprotected lua error, console going down: {}", msg ? msg : "(no message)");
    return 0;
}
// See the RV_PCCL_PDK_BOOTSTRAP_SRC comment above for why most of this is
// Lua source rather than lua_* calls. This C++ half only does what Lua
// itself cannot: reach luaopen_ffi (the stock package library stays closed,
// matching the io/os policy above; the global `require` a script sees is the
// console's own, installed by the constructor and reading modules off the
// drive - see rv_pccl_luajit_require.cpp), and glue rv_pdk_cdef /
// rv_pdk_consts into the pieces that Lua chunk needs.
bool rv_pccl_luajit::bootstrap_pdk()
{
    const int top = lua_gettop(L_);
    // A failed lua_pcall leaves its error string on top; log and unwind to it.
    auto fail_err = [&](const char *what) {
        RV_LOG_ERR("pccl", "pdk bootstrap: {}: {}", what, lua_tostring(L_, -1));
        lua_settop(L_, top);
        return false;
    };
    auto fail = [&](const char *why) {
        RV_LOG_ERR("pccl", "pdk bootstrap: {}", why);
        lua_settop(L_, top);
        return false;
    };

    // Unlike open_lib() above, this keeps luaopen_ffi's return value
    // (nresults = 1): luaopen_ffi is the one stock library that does NOT
    // install a global of its own (LuaJIT's lib_ffi.c literally comments
    // "Note: no global "ffi" created!" on this call), so dropping its return
    // the way open_lib() drops base/string/math/table's would lose the only
    // handle back to ffi.cdef/ffi.C/ffi.cast - there would be no other way
    // to reach them again.
    lua_pushcfunction(L_, luaopen_ffi);
    lua_pushstring(L_, LUA_FFILIBNAME);
    if (lua_pcall(L_, 1, 1, 0) != 0) {
        return fail_err("luaopen_ffi");
    }
    const int ffi_idx = lua_gettop(L_);

    lua_getfield(L_, ffi_idx, "cdef");
    lua_pushstring(L_, rv_pdk_cdef);
    if (lua_pcall(L_, 1, 0, 0) != 0) {
        return fail_err("ffi.cdef(rv_pdk_cdef)");
    }

    // rv_pdk_consts is itself Lua source ("return { NAME = value, ... }");
    // compile then call it - the same two-step shape script_load() uses on
    // every chunk it raises.
    if (luaL_loadbuffer(L_, rv_pdk_consts, std::strlen(rv_pdk_consts), "rv_pdk_consts") != 0) {
        return fail_err("rv_pdk_consts (compile)");
    }
    if (lua_pcall(L_, 0, 1, 0) != 0) {
        return fail_err("rv_pdk_consts (run)");
    }
    if (!lua_istable(L_, -1)) {
        return fail("rv_pdk_consts did not return a table");
    }
    const int pdk_idx = lua_gettop(L_); // this table becomes `pdk` itself

    if (luaL_loadbuffer(L_, RV_PCCL_PDK_BOOTSTRAP_SRC, std::strlen(RV_PCCL_PDK_BOOTSTRAP_SRC),
            "pdk_bootstrap") != 0) {
        return fail_err("pdk bootstrap chunk (compile)");
    }
    lua_pushvalue(L_, ffi_idx);
    lua_pushvalue(L_, pdk_idx);
    if (lua_pcall(L_, 2, 0, 0) != 0) {
        return fail_err("pdk bootstrap chunk (run)");
    }

    // pdk is the ONLY thing this console puts into _G beyond the stock
    // libraries base/string/math/table: _G is the console<->script
    // vocabulary and nothing else. ffi itself never becomes reachable from
    // Lua - a script can only ever get at it through pdk.
    lua_pushvalue(L_, pdk_idx);
    lua_setglobal(L_, "pdk");
    lua_settop(L_, top);
    return true;
}

int rv_pccl_luajit::protected_invoke_(lua_State *L)
{
    const auto fn = reinterpret_cast<lua_CFunction>(lua_touserdata(L, 1));
    lua_remove(L, 1);
    return fn(L);
}

int rv_pccl_luajit::protected_call_(int (*fn)(lua_State *), void *args)
{
    lua_rawgeti(L_, LUA_REGISTRYINDEX, invoke_ref_);
    lua_pushlightuserdata(L_, reinterpret_cast<void *>(fn));
    lua_pushlightuserdata(L_, args);
    return lua_pcall(L_, 2, 0, 0);
}

} // namespace rv_3dmppc
