#include "rv_pconsole/cl/rv_pccl_luajit.hpp"

#include <cassert>
#include <cstdlib>
#include <cstring>
#include <vector>

// THE ONLY file in the whole project that includes lua.hpp — if it shows up
// anywhere else, the PDK boundary has leaked.
#include "lua.hpp"

#include "pdk/cl/rv_cl.h"
#include "pdk/rv_err.h"
#include "pdklib/rv_logs/rv_logs.hpp"

// Generated by cmake/rv_cdef_gen.cmake into build/rv_pdk_cdef.cpp, compiled
// straight into this executable (see that file for what these two strings
// hold: ffi.cdef-ready C declarations, and a "return { NAME = value, ... }"
// Lua chunk). Declared here at GLOBAL scope on purpose - the generated file
// defines them outside any namespace, so a declaration inside
// rv_3dmppc below would name a different, unlinkable symbol.
extern const char rv_pdk_cdef[];
extern const char rv_pdk_consts[];

namespace rv_3dmppc
{
namespace
{
// luaL_openlibs' own recipe (lib_init.c): only what this console allows.
void open_lib(lua_State *L, const char *name, lua_CFunction f)
{
    lua_pushcfunction(L, f);
    lua_pushstring(L, name);
    lua_call(L, 1, 0); // nresults = 0 drops the module table it returns
}

// The rest of bootstrap_pdk() below (cast/new entries, the lazy __index,
// the boot-time resolve-probe) is written as Lua source and run through
// luaL_loadbuffer, not as raw lua_* stack calls: a closure over `ffi` and a
// setmetatable() are exactly what Lua syntax is for, hand-building both
// through the C API would be far harder to read for no benefit, and running
// it as ONE chunk keeps the whole thing inside a single pcall - so a missing
// PDK symbol (ffi.C raises on an unresolved one) is caught right here
// instead of escaping unprotected into the console's first draw call.
//
// `ffi` and the constants table (about to become `pdk`) arrive as this
// chunk's two varargs. cast/new are assigned directly because they are not
// PDK symbols - ffi.C would never resolve "rv_cast" or "rv_new" - everything
// else reaches ffi.C through the metatable, which has to try TWO shapes: a
// contract FUNCTION is always lowercase-"rv_"-prefixed (rv_cv_frame_put), but
// a cdef'd enum member keeps its full declared name, uppercase "RV_"-prefixed
// (RV_TEXWRAP_CLAMP, pdk/include/pdk/cv/rv_primitives.h) - ffi.cdef already
// taught ffi.C that name verbatim, it is just not the "rv_"+k shape the first
// attempt tries. Either hit is memoised (rawset) so a script writes
// pdk.cv_frame_put(cv, prim) or pdk.TEXWRAP_CLAMP and never says ffi. A key
// that matches NEITHER shape re-raises: an unresolved hardware name must
// fail loudly, not read back as nil (silently "this field is optional").
constexpr const char *RV_PCCL_PDK_BOOTSTRAP_SRC = R"lua(
local ffi, pdk = ...
pdk.cast = ffi.cast
pdk.new = ffi.new

-- ffi.C raises on a symbol it cannot resolve, so trying a shape means
-- catching that raise, not checking a return value.
local function try_symbol(name)
    local ok, v = pcall(function() return ffi.C[name] end)
    if ok then return v end
    return nil
end

setmetatable(pdk, {
    __index = function(t, k)
        local v = try_symbol("rv_" .. k) or try_symbol("RV_" .. k)
        if v == nil then
            error("pdk: no hardware symbol for '" .. k .. "' (tried rv_" .. k ..
                " and RV_" .. k .. ")", 2)
        end
        rawset(t, k, v)
        return v
    end,
})
local _ = pdk.cv_screen_width -- boot-time proof the wiring actually resolves
)lua";
} // namespace

rv_pccl_luajit::rv_pccl_luajit(const rv_pccl_conf &conf, rv_pccd &cd)
    : conf_(conf)
    , cd_(cd)
    , budget_(conf.script_memory_size)
{
    L_ = lua_newstate(rv_alloc, this);
    if (L_ == nullptr) {
        RV_LOG_ERR("pccl", "failed to bring up the lua machine ({} byte(s) budgeted)", budget_);
        return; // survive it: no VM is what valid() checks for below
    }
    lua_atpanic(L_, panic);
    // ffi is not a sandbox: a script holding it can read and write any memory
    // of this process. Opening only base/string/math/table keeps io/os out of
    // reach, but that closes accidental doors, not a hostile script's.
    //
    // ONE AT A TIME, never luaL_openlibs: io/os is a hole a disc must not get.
    open_lib(L_, "", luaopen_base);
    open_lib(L_, LUA_STRLIBNAME, luaopen_string);
    open_lib(L_, LUA_MATHLIBNAME, luaopen_math);
    open_lib(L_, LUA_TABLIBNAME, luaopen_table);
    if (!bootstrap_pdk()) {
        RV_LOG_ERR("pccl", "pdk bootstrap failed, lua machine going down");
        lua_close(L_);
        L_ = nullptr; // same shape as a failed lua_newstate: valid() below goes false
        return;
    }
    RV_LOG_INFO("pccl", "lua machine up, {} byte(s) budgeted", budget_);
}
// No VM to close is not a failure: the ctor already logged why L_ is null.
rv_pccl_luajit::~rv_pccl_luajit()
{
    if (L_ != nullptr) {
        lua_close(L_);
    }
}
// L_ null is the only FALSE — the ctor already logged why. Every method
// below skips the "is a VM up" guard the old rv_pccl.cpp had: a factory
// upstream only ever builds this class for a disc that declared a lua
// machine, and the console refuses to boot when valid() answers false, so no
// contract method is ever reached with L_ null.
bool rv_pccl_luajit::valid() const
{
    return L_ != nullptr;
}
// lua_Alloc: refuses to push used_ past budget_. ptr==nullptr means a fresh
// block, so osize is then a type tag, not a size (lua_Alloc contract).
void *rv_pccl_luajit::rv_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
{
    rv_pccl_luajit *self = static_cast<rv_pccl_luajit *>(ud);
    if (nsize == 0) {
        if (ptr != nullptr) {
            self->used_ -= static_cast<int64_t>(osize);
        }
        std::free(ptr);
        return nullptr;
    }
    const int64_t old_size = ptr != nullptr ? static_cast<int64_t>(osize) : 0;
    const int64_t delta = static_cast<int64_t>(nsize) - old_size;
    // Only growth is checked; NULL is not a crash — Lua turns it into a
    // catchable "not enough memory" error, a ceiling the script hits.
    if (delta > 0 && self->used_ + delta > self->budget_) {
        return nullptr;
    }
    void *out = std::realloc(ptr, nsize);
    if (out == nullptr) {
        return nullptr; // real failure; used_ untouched
    }
    self->used_ += delta;
    return out;
}
// Installed via lua_atpanic: an error outside pcall would otherwise abort() silently.
int rv_pccl_luajit::panic(lua_State *L)
{
    const char *msg = lua_tostring(L, -1);
    RV_LOG_EMERG("pccl", "unprotected lua error, console going down: {}", msg ? msg : "(no message)");
    return 0;
}
// See the RV_PCCL_PDK_BOOTSTRAP_SRC comment above for why most of this is
// Lua source rather than lua_* calls. This C++ half only does what Lua
// itself cannot: reach luaopen_ffi (no `require` exists - package/require is
// never opened, matching the io/os policy above), and glue rv_pdk_cdef /
// rv_pdk_consts into the pieces that Lua chunk needs.
bool rv_pccl_luajit::bootstrap_pdk()
{
    const int top = lua_gettop(L_);
    // A failed lua_pcall leaves its error string on top; log and unwind to it.
    auto fail_err = [&](const char *what) {
        RV_LOG_ERR("pccl", "pdk bootstrap: {}: {}", what, lua_tostring(L_, -1));
        lua_settop(L_, top);
        return false;
    };
    auto fail = [&](const char *why) {
        RV_LOG_ERR("pccl", "pdk bootstrap: {}", why);
        lua_settop(L_, top);
        return false;
    };

    // Unlike open_lib() above, this keeps luaopen_ffi's return value
    // (nresults = 1): luaopen_ffi is the one stock library that does NOT
    // install a global of its own (LuaJIT's lib_ffi.c literally comments
    // "Note: no global "ffi" created!" on this call), so dropping its return
    // the way open_lib() drops base/string/math/table's would lose the only
    // handle back to ffi.cdef/ffi.C/ffi.cast - there would be no other way
    // to reach them again.
    lua_pushcfunction(L_, luaopen_ffi);
    lua_pushstring(L_, LUA_FFILIBNAME);
    if (lua_pcall(L_, 1, 1, 0) != 0) {
        return fail_err("luaopen_ffi");
    }
    const int ffi_idx = lua_gettop(L_);

    lua_getfield(L_, ffi_idx, "cdef");
    lua_pushstring(L_, rv_pdk_cdef);
    if (lua_pcall(L_, 1, 0, 0) != 0) {
        return fail_err("ffi.cdef(rv_pdk_cdef)");
    }

    // rv_pdk_consts is itself Lua source ("return { NAME = value, ... }");
    // compile then call it - the same two-step shape script_load() uses on
    // every chunk it raises.
    if (luaL_loadbuffer(L_, rv_pdk_consts, std::strlen(rv_pdk_consts), "rv_pdk_consts") != 0) {
        return fail_err("rv_pdk_consts (compile)");
    }
    if (lua_pcall(L_, 0, 1, 0) != 0) {
        return fail_err("rv_pdk_consts (run)");
    }
    if (!lua_istable(L_, -1)) {
        return fail("rv_pdk_consts did not return a table");
    }
    const int pdk_idx = lua_gettop(L_); // this table becomes `pdk` itself

    if (luaL_loadbuffer(L_, RV_PCCL_PDK_BOOTSTRAP_SRC, std::strlen(RV_PCCL_PDK_BOOTSTRAP_SRC),
            "pdk_bootstrap") != 0) {
        return fail_err("pdk bootstrap chunk (compile)");
    }
    lua_pushvalue(L_, ffi_idx);
    lua_pushvalue(L_, pdk_idx);
    if (lua_pcall(L_, 2, 0, 0) != 0) {
        return fail_err("pdk bootstrap chunk (run)");
    }

    // pdk is the ONLY thing this console puts into _G beyond the stock
    // libraries base/string/math/table: _G is the console<->script
    // vocabulary and nothing else. ffi itself never becomes reachable from
    // Lua - a script can only ever get at it through pdk.
    lua_pushvalue(L_, pdk_idx);
    lua_setglobal(L_, "pdk");
    lua_settop(L_, top);
    return true;
}
int64_t rv_pccl_luajit::script_load(const void *bytecode, int64_t size, const char *name)
{
    if (bytecode == nullptr || size <= 0 || name == nullptr) {
        return RV_ERR_INVAL;
    }
    const int top = lua_gettop(L_); // balance invariant, held on every return below
    // Shared exit for a lua-level failure: log, pop, confirm the balance.
    auto fail = [&](int64_t code) {
        RV_LOG_ERR("pccl", "script_load('{}'): {}", name, lua_tostring(L_, -1));
        lua_pop(L_, 1);
        assert(lua_gettop(L_) == top);
        return code;
    };
    if (luaL_loadbuffer(L_, static_cast<const char *>(bytecode), static_cast<size_t>(size), name) != 0) {
        return fail(RV_ERR_IO);
    }
    // loadbuffer only COMPILES; the module table is the RESULT of running the body.
    if (lua_pcall(L_, 0, 1, 0) != 0) {
        return fail(RV_ERR_IO);
    }
    if (!lua_istable(L_, -1)) {
        RV_LOG_ERR("pccl", "script_load('{}'): chunk did not return a table", name);
        lua_pop(L_, 1);
        assert(lua_gettop(L_) == top);
        return RV_ERR_INVAL;
    }
    const int ref = luaL_ref(L_, LUA_REGISTRYINDEX); // pops the table
    chunks_.push_back(ref);
    assert(lua_gettop(L_) == top);
    return static_cast<int64_t>(chunks_.size() - 1);
}
int64_t rv_pccl_luajit::script_free(int64_t handle)
{
    if (handle < 0 || handle >= static_cast<int64_t>(chunks_.size())) {
        return RV_ERR_INVAL;
    }
    int &ref = chunks_[static_cast<size_t>(handle)];
    if (ref == LUA_NOREF) {
        return RV_ERR_INVAL; // already freed; the slot is never reused
    }
    luaL_unref(L_, LUA_REGISTRYINDEX, ref);
    ref = LUA_NOREF;
    return RV_OK;
}
int64_t rv_pccl_luajit::script_entry()
{
    if (entry_ >= 0) {
        return entry_; // raised once; later calls answer from memo
    }
    // The console parsed the manifest, so it — not the disc — knows the name.
    const int64_t handle = cd_.asset_open(conf_.script_entry.c_str());
    if (handle < 0) {
        return handle;
    }
    const int64_t size = cd_.asset_size(handle);
    if (size <= 0) {
        return size < 0 ? size : RV_ERR_INVAL; // an entry needs bytes
    }
    std::vector<char> bytes(static_cast<size_t>(size));
    const int64_t read = cd_.asset_read(handle, bytes.data(), size);
    if (read < 0) {
        return read;
    }
    const int64_t loaded = script_load(bytes.data(), read, conf_.script_entry.c_str());
    if (loaded < 0) {
        return loaded;
    }
    entry_ = loaded;
    return entry_;
}
// --- group B: raw stack access, direct lua_* wrappers ---
int64_t rv_pccl_luajit::stack_push_nil()
{
    lua_pushnil(L_);
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_push_boolean(bool value)
{
    lua_pushboolean(L_, value);
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_push_integer(int64_t value)
{
    lua_pushinteger(L_, static_cast<lua_Integer>(value));
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_push_number(double value)
{
    lua_pushnumber(L_, static_cast<lua_Number>(value));
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_push_string(const char *text, int64_t length)
{
    if (text == nullptr || length < 0) {
        return RV_ERR_INVAL;
    }
    lua_pushlstring(L_, text, static_cast<size_t>(length));
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_push_pointer(void *p)
{
    lua_pushlightuserdata(L_, p);
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_drop(int64_t count)
{
    if (count < 0 || count > lua_gettop(L_)) {
        return RV_ERR_INVAL;
    }
    lua_pop(L_, static_cast<int>(count));
    return RV_OK;
}
int64_t rv_pccl_luajit::stack_count()
{
    return static_cast<int64_t>(lua_gettop(L_));
}
int64_t rv_pccl_luajit::value_type(int64_t index)
{
    switch (lua_type(L_, static_cast<int>(index))) {
    case LUA_TNIL:
        return RV_CL_TYPE_NIL;
    case LUA_TBOOLEAN:
        return RV_CL_TYPE_BOOLEAN;
    case LUA_TNUMBER:
        return RV_CL_TYPE_NUMBER;
    case LUA_TSTRING:
        return RV_CL_TYPE_STRING;
    case LUA_TFUNCTION:
        return RV_CL_TYPE_FUNCTION;
    case LUA_TTABLE:
        return RV_CL_TYPE_TABLE;
    case LUA_TNONE:
        return RV_ERR_INVAL; // no value at that index
    default:
        return RV_CL_TYPE_OTHER;
    }
}
int64_t rv_pccl_luajit::value_boolean(int64_t index, bool *out)
{
    if (out == nullptr) {
        return RV_ERR_INVAL;
    }
    if (lua_type(L_, static_cast<int>(index)) != LUA_TBOOLEAN) {
        return RV_ERR_INVAL;
    }
    *out = lua_toboolean(L_, static_cast<int>(index)) != 0;
    return RV_OK;
}
int64_t rv_pccl_luajit::value_integer(int64_t index, int64_t *out)
{
    if (out == nullptr) {
        return RV_ERR_INVAL;
    }
    int isnum = 0;
    const lua_Integer v = lua_tointegerx(L_, static_cast<int>(index), &isnum);
    if (!isnum) {
        return RV_ERR_INVAL;
    }
    *out = static_cast<int64_t>(v);
    return RV_OK;
}
int64_t rv_pccl_luajit::value_number(int64_t index, double *out)
{
    if (out == nullptr) {
        return RV_ERR_INVAL;
    }
    int isnum = 0;
    const lua_Number v = lua_tonumberx(L_, static_cast<int>(index), &isnum);
    if (!isnum) {
        return RV_ERR_INVAL;
    }
    *out = static_cast<double>(v);
    return RV_OK;
}
// Typed BEFORE lua_tolstring: on a number it would convert it to a string IN
// PLACE on the stack. LUA_TSTRING-only sidesteps that.
int64_t rv_pccl_luajit::value_string(int64_t index, char *baddr, int64_t baddr_size)
{
    if (baddr_size < 0) {
        return RV_ERR_INVAL;
    }
    if (lua_type(L_, static_cast<int>(index)) != LUA_TSTRING) {
        return RV_ERR_INVAL;
    }
    size_t len = 0;
    const char *s = lua_tolstring(L_, static_cast<int>(index), &len);
    if (baddr != nullptr) { // the pointer is the collector's; copy, never hand it out
        const int64_t n = baddr_size < static_cast<int64_t>(len) ? baddr_size : static_cast<int64_t>(len);
        std::memcpy(baddr, s, static_cast<size_t>(n));
    }
    return static_cast<int64_t>(len);
}
// The caller already pushed argc arguments; the function lands UNDERNEATH them.
int64_t rv_pccl_luajit::script_call(int64_t handle, const char *fname, int64_t argc, int64_t retc)
{
    if (fname == nullptr || argc < 0 || retc < 0 || argc > lua_gettop(L_)) {
        return RV_ERR_INVAL;
    }
    if (handle < 0 || handle >= static_cast<int64_t>(chunks_.size())) {
        return RV_ERR_INVAL;
    }
    const int ref = chunks_[static_cast<size_t>(handle)];
    if (ref == LUA_NOREF) {
        return RV_ERR_INVAL; // handle names a freed chunk
    }
    const int top = lua_gettop(L_);          // invariant: top-argc on failure, top-argc+retc on success
    lua_rawgeti(L_, LUA_REGISTRYINDEX, ref); // [args..., T]
    lua_getfield(L_, -1, fname);             // [args..., T, fn?]
    const bool callable = lua_isfunction(L_, -1);
    lua_remove(L_, -2); // [args..., fn?]
    if (!callable) {    // args AND the non-function value must both leave the stack
        lua_pop(L_, static_cast<int>(argc) + 1);
        RV_LOG_ERR("pccl", "script_call: '{}' is not a function", fname);
        assert(lua_gettop(L_) == top - static_cast<int>(argc));
        return RV_ERR_INVAL;
    }
    lua_insert(L_, -static_cast<int>(argc) - 1); // [fn, args...]
    if (lua_pcall(L_, static_cast<int>(argc), static_cast<int>(retc), 0) != 0) {
        // Contract: nothing survives a failed call — logged, then popped.
        RV_LOG_ERR("pccl", "script_call('{}'): {}", fname, lua_tostring(L_, -1));
        lua_pop(L_, 1);
        assert(lua_gettop(L_) == top - static_cast<int>(argc));
        return RV_ERR_IO;
    }
    assert(lua_gettop(L_) == top - static_cast<int>(argc) + static_cast<int>(retc));
    return RV_OK;
}
} // namespace rv_3dmppc
