// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — hello sample disc: a complete minimal game.
// ──────────────────────────────────────────────────────────────────────────────
//
// The smallest complete disc, and the reference for what one looks like.
//
// It does four things, one per subsystem it has to prove:
//   * reads greeting.txt off the medium               (rv_pdk::rv_cd — the archive it
//     was itself loaded from)
//   * loads badge.mppctex and draws it three ways     (rv_pdk::rv_cv)
//   * quits on Esc / Option                           (rv_pdk::rv_cio)
//   * releases what it took                           (disc_shutdown)
//
// BOUNDARY: it includes pdk/ and the standard library, nothing else. There is
// no console header here, no logger, no SDL — and the burner does not put the
// console's include path on the generated project, so an attempt to reach for
// one does not compile.
//
// The last line of the file is what makes this a disc rather than a library:
// RV_DISC_EXPORT plants the two extern "C" symbols the console looks up after
// dlopen. Everything else is hidden (-fvisibility=hidden).
#include <cstdint>
#include <cstring>
#include <vector>

#include "pdk/cio/rv_cio.hpp"
#include "pdk/cd/rv_cd.hpp"
#include "pdk/cv/rv_cv.hpp"
#include "pdk/de/rv_de.hpp"
#include "pdk/rv_abi.hpp"
#include "pdk/rv_err.hpp"

namespace hello {
namespace {

constexpr int32_t RV_HELLO_DEPTH_BADGE = 0;
constexpr int32_t RV_HELLO_DEPTH_BAR = 400;

// The .mppctex container mppcbaker produces. Sixteen bytes, little-endian, then
// the palette, then the texels — both already in the exact shape
// video_asset_write() wants, so nothing is repacked here.
struct rv_hello_texheader {
    uint16_t version;
    uint16_t format;
    uint16_t width;
    uint16_t height;
    uint16_t palette_count;
};

uint16_t read_u16(const uint8_t* p) {
    // Byte-wise, not a cast: the file is little-endian by definition and the
    // host's byte order is not this file's business.
    return static_cast<uint16_t>(p[0] | (p[1] << 8));
}

bool parse_texheader(const std::vector<uint8_t>& bytes, rv_hello_texheader& out) {
    if (bytes.size() < 16) return false;
    if (std::memcmp(bytes.data(), "MPTX", 4) != 0) return false;

    out.version = read_u16(bytes.data() + 4);
    out.format = read_u16(bytes.data() + 6);
    out.width = read_u16(bytes.data() + 8);
    out.height = read_u16(bytes.data() + 10);
    out.palette_count = read_u16(bytes.data() + 12);
    return out.version == 1;
}

}  // namespace

class rv_dmain : public rv_pdk::rv_de {
   public:
    int64_t disc_initialize(rv_pdk::rv_pdko& pdk) override;
    void frame_update(float dt) override;
    void frame_render() override;
    bool disc_release() const override { return release_; }
    void disc_shutdown() override;
    const char* disc_title() const override { return "hello - the smallest disc"; }

   private:
    bool read_asset(const char* name, std::vector<uint8_t>& out);
    void load_badge();

    rv_pdk::rv_pdko* pdk_ = nullptr;
    int64_t screen_width_ = 0;
    int64_t screen_height_ = 0;

    int64_t addr_texels_ = 0;
    int64_t addr_palette_ = 0;

    int64_t greeting_bytes_ = 0;
    float phase_ = 0.0f;
    uint64_t prev_buttons_ = 0;
    bool release_ = false;
};

bool rv_dmain::read_asset(const char* name, std::vector<uint8_t>& out) {
    rv_pdk::rv_cd* cd = pdk_->cd();
    if (!cd) return false;

    const int64_t handle = cd->asset_open(name);
    if (handle < 0) return false;

    const int64_t size = cd->asset_size(handle);
    if (size < 0) return false;

    out.assign(static_cast<std::size_t>(size), 0);
    // The AUTHORITATIVE length is what asset_read returns; asset_size is a hint
    // that may go stale between the two calls (see rv_pdk::rv_cd.hpp).
    const int64_t read = cd->asset_read(handle, out.data(), size);
    if (read < 0) return false;

    out.resize(static_cast<std::size_t>(read));
    return true;
}

void rv_dmain::load_badge() {
    std::vector<uint8_t> bytes;
    if (!read_asset("badge.mppctex", bytes)) return;

    rv_hello_texheader header{};
    if (!parse_texheader(bytes, header)) return;

    rv_pdk::rv_cv* cv = pdk_->cv();
    const std::size_t palette_offset = 16;
    const std::size_t palette_bytes = static_cast<std::size_t>(header.palette_count) * 2;
    const std::size_t texel_offset = palette_offset + palette_bytes;
    if (bytes.size() < texel_offset) return;

    const std::size_t texel_bytes = bytes.size() - texel_offset;

    // The palette is uploaded as a texture of its own: format DIRECT15,
    // width = entry count, height = 1. That convention is in rv_pdk::rv_texture.hpp,
    // and it is why no separate palette-upload call exists.
    if (header.palette_count > 0) {
        const int64_t addr = cv->video_asset_malloc(static_cast<int64_t>(palette_bytes));
        if (addr < 0) return;

        rv_pdk::rv_texture palette{};
        palette.format = rv_pdk::RV_TEXFMT_DIRECT15;
        palette.data = bytes.data() + palette_offset;
        palette.size = palette_bytes;
        palette.width = header.palette_count;
        palette.height = 1;
        if (cv->video_asset_write(addr, palette) < 0) {
            cv->video_asset_free(addr);
            return;
        }
        addr_palette_ = addr;
    }

    const int64_t addr = cv->video_asset_malloc(static_cast<int64_t>(texel_bytes));
    if (addr < 0) return;

    rv_pdk::rv_texture texels{};
    texels.format = static_cast<rv_pdk::rv_texfmt>(header.format);
    texels.data = bytes.data() + texel_offset;
    texels.size = texel_bytes;
    texels.width = header.width;
    texels.height = header.height;
    if (cv->video_asset_write(addr, texels) < 0) {
        cv->video_asset_free(addr);
        return;
    }
    addr_texels_ = addr;
}

int64_t rv_dmain::disc_initialize(rv_pdk::rv_pdko& pdk) {
    pdk_ = &pdk;

    rv_pdk::rv_cv* cv = pdk_->cv();
    rv_pdk::rv_cio* cio = pdk_->cio();
    if (!cv || !cio) return rv_pdk::RV_ERR_INVAL;

    screen_width_ = cv->screen_width();
    screen_height_ = cv->screen_height();

    // Validate the baked assumptions against the machine that turned up. A
    // mismatch is refused HERE, on the loading screen, rather than discovered
    // as garbage half a second into play.
    if (screen_width_ < 64 || screen_height_ < 64) return rv_pdk::RV_ERR_INVAL;
    if (cv->frame_capacity() < 8) return rv_pdk::RV_ERR_INVAL;
    if (cio->iport_count() < 1) return rv_pdk::RV_ERR_INVAL;

    std::vector<uint8_t> greeting;
    if (read_asset("greeting.txt", greeting)) {
        greeting_bytes_ = static_cast<int64_t>(greeting.size());
    }

    load_badge();
    return rv_pdk::RV_OK;
}

void rv_dmain::frame_update(float dt) {
    if (dt > 0.0f) phase_ += dt;

    // THEOREM: edge detection by snapshot diff. rv_pdk::rv_cio reports the current LEVEL
    // of every source and never an event, so "pressed this frame" is
    // (now & ~was). Acting on the level would fire the quit sixty times a second
    // while the key is held — harmless here, fatal for anything that counts.
    const uint64_t now = pdk_->cio()->iport_state(0).buttons;
    if ((now & ~prev_buttons_) & rv_pdk::RV_ISOURCE_MENU_BTTN_MENU) release_ = true;
    prev_buttons_ = now;
}

void rv_dmain::frame_render() {
    rv_pdk::rv_cv* cv = pdk_->cv();

    cv->frame_configure(0, rv_pdk::rv_color{20, 24, 40});

    // The badge, three times, one per wrap mode — the same check the console's
    // built-in service test makes, done here from a texture that travelled the
    // whole pipeline: PNG in the disc directory, baked by mppcbaker, packed into
    // the archive, read back through rv_pdk::rv_cd.
    if (addr_texels_ != 0) {
        const rv_pdk::rv_texture_mapping_type modes[3] = {rv_pdk::RV_TEXWRAP_CLAMP, rv_pdk::RV_TEXWRAP_TILE,
                                                  rv_pdk::RV_TEXWRAP_STRETCH};
        const float size = 48.0f;
        const float gap = 12.0f;
        const float total = 3.0f * size + 2.0f * gap;
        const float x0 = (static_cast<float>(screen_width_) - total) * 0.5f;
        const float y0 = (static_cast<float>(screen_height_) - size) * 0.5f;

        for (int i = 0; i < 3; ++i) {
            rv_pdk::rv_primitive primitive{};
            primitive.type = rv_pdk::RV_PRIMITIVE_SPRITE;
            primitive.depth = RV_HELLO_DEPTH_BADGE;

            rv_pdk::rv_sprite& sprite = primitive.data.sprite;
            sprite.fill_mode = rv_pdk::RV_PRIMITIVE_FILL_MODE_SAMPLE_TEXTURE;
            sprite.addr_texture = addr_texels_;
            sprite.addr_palette = addr_palette_;
            sprite.color = rv_pdk::rv_color{255, 255, 255};
            sprite.mapping = modes[i];
            sprite.x = static_cast<int16_t>(x0 + static_cast<float>(i) * (size + gap));
            sprite.y = static_cast<int16_t>(y0);
            sprite.width = static_cast<uint16_t>(size);
            sprite.height = static_cast<uint16_t>(size);

            cv->frame_put(primitive);
        }
    }

    // Proof the medium answered: a bar as long as greeting.txt is. No file, no
    // bar — and that is the difference between "the archive mounted" and "the
    // archive mounted and the bytes came back".
    if (greeting_bytes_ > 0) {
        rv_pdk::rv_primitive primitive{};
        primitive.type = rv_pdk::RV_PRIMITIVE_SPRITE;
        primitive.depth = RV_HELLO_DEPTH_BAR;

        rv_pdk::rv_sprite& sprite = primitive.data.sprite;
        sprite.fill_mode = rv_pdk::RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;
        sprite.addr_texture = 0;
        sprite.addr_palette = 0;
        sprite.color = rv_pdk::rv_color{90, 210, 220};
        sprite.mapping = rv_pdk::RV_TEXWRAP_CLAMP;
        sprite.x = 8;
        sprite.y = static_cast<int16_t>(screen_height_ - 16);
        sprite.width = static_cast<uint16_t>(greeting_bytes_ * 4);
        sprite.height = 8;

        cv->frame_put(primitive);
    }

    // The console does not flush for the disc (rv_pdk::rv_de::frame_render).
    cv->frame_flush();
}

void rv_dmain::disc_shutdown() {
    // The facade is still valid here and this is the LAST moment it is: after
    // this returns the console may unload this code entirely, and a destructor
    // belonging to unmapped code cannot run. So whatever disc_initialize took
    // is given back here, not in ~rv_dmain.
    if (!pdk_) return;

    rv_pdk::rv_cv* cv = pdk_->cv();
    if (addr_texels_ != 0) cv->video_asset_free(addr_texels_);
    if (addr_palette_ != 0) cv->video_asset_free(addr_palette_);
    addr_texels_ = 0;
    addr_palette_ = 0;
}

}  // namespace hello

// This one line turns the translation unit into a disc: it plants
// mppc_disc_create / mppc_disc_destroy with default visibility, and they are
// the only symbols the console can reach. See pdk/rv_abi.hpp.
RV_DISC_EXPORT(hello::rv_dmain)
