// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 4 — video controller: resolving texture addresses into a raster view.
// ──────────────────────────────────────────────────────────────────────────────
//
// The console's rv_cv implementation: the "GPU". It owns the four pieces a frame
// needs — the video RAM pool, the ordering table, the framebuffer and the
// per-frame primitive buffer — and hands the finished page to the SDL host.
//
// PATTERN: retained-mode command buffer. frame_put() does not draw: it validates
// the primitive, COPIES it into a frame-owned vector and files its index in the
// ordering table. Nothing is rasterized until frame_flush(). That is forced by
// the contract (pdk/cv/rv_cv.hpp): the console re-orders primitives by depth, so
// it cannot know a primitive's turn to draw until every primitive has arrived.
// The copy is what makes each command self-contained — the disc may free or
// overwrite its own primitive struct the moment frame_put() returns, exactly as
// with video_asset_write().
//
// PATTERN: facade. Every method here is contract semantics (validation, error
// codes, frame lifecycle) layered over a delegation to one of the four workers;
// none of the mechanism — first-fit allocation, bucket sort, RGB555 packing,
// scanline filling — lives in this class. rv_cv is the vocabulary a disc speaks;
// rv_pcvram / rv_pcotable / rv_pcfbuf / rv_pcraster are the machine's parts, and
// they never learn about each other.
//
// PATTERN: address resolution at the boundary. This class is the ONLY one that
// knows an rv_polygon::addr_texture is a video RAM address: at flush it turns
// the addresses into an rv_pctexview (borrowed pointers plus a shape) and hands
// that down. The rasterizer and the sampler below it stay pool-free, and the
// pool's "who may hold a pointer into it, and for how long" rule stays inside
// the one class that owns the pool.
#pragma once

#include <cstdint>
#include <vector>

#include "pdk/cv/rv_cv.hpp"
#include "pdk/cv/rv_primitives.hpp"
#include "pdk/cv/rv_texture.hpp"
#include "pdk/cv/rv_vertex.hpp"
#include "rv_pconsole/cv/rv_pcfbuf.hpp"
#include "rv_pconsole/cv/rv_pcotable.hpp"
#include "rv_pconsole/cv/rv_pctexel.hpp"
#include "rv_pconsole/cv/rv_pcvram.hpp"
#include "rv_pconsole/rv_pchost.hpp"
#include "rv_pconsole/rv_pconsole_conf.hpp"

namespace rv_3dmppc {

class rv_pccv : public rv_pdk::rv_cv {
   public:
    // `host` is borrowed: the console owns it, constructs it before every
    // controller and tears it down after them (see rv_pconsole.hpp — the
    // declaration order there is load-bearing).
    rv_pccv(const rv_pccv_conf& conf, rv_pchost& host);
    ~rv_pccv() override = default;

    // The frame buffers below are screen-sized pages and the vram pool is a
    // megabyte: copying a console's GPU is never meaningful, and `host_` is a
    // reference, so let the compiler say so instead of silently slicing.
    rv_pccv(const rv_pccv&) = delete;
    rv_pccv& operator=(const rv_pccv&) = delete;

    // --- hardware geometry: straight out of the configuration ---

    int64_t screen_width() override;
    int64_t screen_height() override;
    int64_t texture_max_width() override;
    int64_t texture_max_height() override;
    int64_t video_memory_size() override;
    int64_t frame_capacity() override;

    // --- video RAM ---

    int64_t video_asset_malloc(int64_t size) override;
    int64_t video_asset_write(int64_t addr, const rv_pdk::rv_texture* texture) override;
    int64_t video_asset_free(int64_t addr) override;

    // --- the frame ---

    int64_t frame_configure(uint64_t config, rv_pdk::rv_color clear_color) override;
    int64_t frame_put(const rv_pdk::rv_primitive* primitive) override;
    int64_t frame_flush() override;

   private:
    // Contract validation of the fill attributes a polygon and a sprite share.
    // Returns RV_OK or RV_ERR_INVAL. Const because it only interrogates the
    // vram pool — filing the primitive is the caller's job.
    int64_t check_fill(uint32_t fill_mode, int64_t addr_texture, int64_t addr_palette) const;

    // Is `format` one of the rv_texfmt enumerators this console knows?
    static bool texture_format_known(rv_pdk::rv_texfmt format);

    // Resolve the addresses a primitive names into a view the rasterizer can
    // sample. Returns an INVALID view when the primitive does not sample, when
    // the region was never uploaded into, or when an indexed format's palette is
    // missing — never an error, because frame_put already reported everything
    // the disc can still act on and a flush has no error channel back to it.
    //
    // The view borrows pointers into the pool. They are valid only for the
    // duration of the draw call: the disc cannot free a region mid-flush (it is
    // not running), so the shortest possible lifetime is also a safe one.
    rv_pctexview texture_view(const rv_pdk::rv_primitive& primitive) const;

    // The texture / palette pair a primitive samples, or (0, 0) when it does not
    // sample at all. Shared by polygons and sprites, which name their assets
    // identically.
    static void texture_addresses(const rv_pdk::rv_primitive& primitive, int64_t& addr_texture,
                                  int64_t& addr_palette);

    // Drop the frame's commands and their ordering. Does NOT touch the clear
    // colour or the Z flag — frame_configure sets those and then calls this.
    void frame_reset();

    rv_pccv_conf conf_;
    rv_pchost& host_;  // borrowed, never owned

    rv_pcfbuf fbuf_;
    rv_pcvram vram_;
    rv_pcotable otable_;

    // The frame's commands, in submission order. The ordering table stores
    // indexes into this vector, so it must not be reordered mid-frame.
    std::vector<rv_pdk::rv_primitive> primitives_;

    // --- frame state, valid between frame_configure and frame_flush ---

    rv_pdk::rv_color clear_color_{0, 0, 0};  // default: a black frame
    bool z_enabled_ = false;                 // default: ordering table only
};

}  // namespace rv_3dmppc
