#include "scene/rv_editor_scene_codegen.hpp"

#include <cctype>
#include <fstream>
#include <system_error>

namespace rv_editor
{

namespace
{

// scene_name as a C identifier: anything not [A-Za-z0-9_] becomes '_', and a
// leading digit gets a '_' prefix so the generated symbols always compile.
std::string rv_editor_scene_codegen_id(std::string_view scene_name)
{
    std::string id;
    id.reserve(scene_name.size() + 1);
    if (!scene_name.empty() && std::isdigit(static_cast<unsigned char>(scene_name.front()))) {
        id.push_back('_');
    }
    for (const char c : scene_name) {
        const unsigned char uc = static_cast<unsigned char>(c);
        id.push_back((std::isalnum(uc) || c == '_') ? c : '_');
    }
    return id;
}

} // namespace

std::string rv_editor_scene_codegen_text(std::string_view scene_name)
{
    const std::string id = rv_editor_scene_codegen_id(scene_name);
    const std::string asset = std::string(scene_name) + ".scene.toml";

    std::string text;
    text += "#pragma once\n\n";
    text += "// Generated by 3dmppc-editor for scenes/" + asset + ".\n";
    text += "// Yours to edit or delete; the editor never rewrites this file.\n";
    text += "//\n";
    text += "// To use it: include \"pdklib/rv_scene/rv_scene_unit.hpp\" in exactly one\n";
    text += "// source file of the disc, then call " + id + "_scene_load from\n";
    text += "// disc_initialize with rv_pdko_cd(pdk_) as cd.\n";
    text += "//\n";
    text += "// Each object carries an id, a name, a kind (\"group\", \"camera\" or\n";
    text += "// \"mesh\"), a mesh and a texture asset name, and position/rotation/scale.\n";
    text += "// rv_pdklib::rv_scene_world(scene, i) gives object i's transform.\n\n";
    text += "#include <string>\n\n";
    text += "#include \"pdklib/rv_scene/rv_scene_disc.hpp\"\n\n";
    text += "inline constexpr const char *" + id + "_scene_asset = \"" + asset + "\";\n\n";
    text += "inline int " + id + "_scene_load(rv_cd *cd, rv_pdklib::rv_scene &scene, std::string &error)\n";
    text += "{\n";
    text += "    return rv_pdklib::rv_scene_load(cd, " + id + "_scene_asset, scene, error);\n";
    text += "}\n";
    return text;
}

bool rv_editor_scene_codegen_write(const std::filesystem::path &root, std::string_view scene_name,
    std::filesystem::path &written, std::string &error)
{
    const std::filesystem::path src_dir = root / "src";
    const std::filesystem::path path = src_dir / (rv_editor_scene_codegen_id(scene_name) + "_scene.hpp");

    std::error_code ec;
    std::filesystem::create_directories(src_dir, ec);
    if (ec) {
        error = "could not create " + src_dir.string() + ": " + ec.message();
        return false;
    }
    if (std::filesystem::exists(path, ec)) {
        error = path.string() + " already exists";
        return false;
    }

    std::ofstream out(path, std::ios::binary);
    if (!out) {
        error = "could not open " + path.string() + " for writing";
        return false;
    }
    out << rv_editor_scene_codegen_text(scene_name);
    if (!out) {
        error = "could not write " + path.string();
        return false;
    }
    written = path;
    return true;
}

} // namespace rv_editor
