// ─── NEUROSLOP
// ──────────────────────────────────────────────────────────────── Generated by
// Claude (claude-opus-5). Not reviewed by a human. Revision: stage 10 — disc
// loader implementation: manifest parsing, extracting the code to a temporary
// file, dlopen, the handshake and teardown in reverse order.
// ──────────────────────────────────────────────────────────────────────────────
#include "rv_pconsole/rv_pcloader.hpp"

#include <dlfcn.h>
#include <elf.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cerrno>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <format>
#include <new>
#include <string_view>
#include <system_error>
#include <vector>

#include "pdk/rv_err.hpp"
#include "pdk/de/rv_dv.hpp"
#include "pdklib/rv_logs/rv_logs.hpp"
#include "rv_pconsole/cd/rv_pczip.hpp"

namespace rv_3dmppc
{

// The contract's vocabulary, unqualified for the bodies below only. Never in a
// header: a using-directive there would leak into every translation unit that
// includes it.
using namespace rv_pdk;

namespace
{

// The two service entries. They live in the archive next to the assets but are
// NOT part of the disc's resource namespace: the console reads them, the game
// never asks for them.
constexpr const char *kManifestEntry = "disc.toml";
constexpr const char *kDefaultCodeEntry = "disc.so";

// Ceilings on what the console will allocate on the say-so of an archive. Every
// size below comes out of a file that may have been downloaded from anywhere,
// so none of them may become a malloc argument unchecked: a two-line header
// claiming a four-gigabyte manifest must cost a log line, not the machine's
// memory.
constexpr int64_t kManifestMaxSize = 1 << 20; // 1 MiB of text is already absurd
constexpr int64_t kCodeMaxSize = 128 << 20; // 128 MiB of code likewise

std::string_view trim(std::string_view text)
{
	const char *kSpace = " \t\r\n\f\v";
	const std::size_t first = text.find_first_not_of(kSpace);
	if (first == std::string_view::npos) {
		return std::string_view();
	}
	const std::size_t last = text.find_last_not_of(kSpace);
	return text.substr(first, last - first + 1);
}

// Value side of a `key = value` line, reduced to the string it denotes.
// Quoted: everything between the quotes, verbatim (a `#` inside quotes is
// data). Bare: everything up to a `#` comment, trimmed. Deliberately forgiving
// — the console reads four keys and has no business failing a manifest over the
// ones it ignores.
std::string manifest_value(std::string_view raw)
{
	raw = trim(raw);
	if (raw.size() >= 2 && (raw.front() == '"' || raw.front() == '\'')) {
		const char quote = raw.front();
		const std::size_t end = raw.find(quote, 1);
		if (end != std::string_view::npos) {
			return std::string(raw.substr(1, end - 1));
		}
		return std::string(raw.substr(1));
	}
	const std::size_t comment = raw.find('#');
	if (comment != std::string_view::npos) {
		raw = raw.substr(0, comment);
	}
	return std::string(trim(raw));
}

// Non-negative decimal, or false. Saturating rather than wrapping: a version
// field full of digits is garbage, and garbage must not alias a valid version.
bool manifest_int(std::string_view text, int &out)
{
	text = trim(text);
	if (text.empty()) {
		return false;
	}
	long long value = 0;
	for (const char ch : text) {
		if (ch < '0' || ch > '9') {
			return false;
		}
		value = value * 10 + (ch - '0');
		if (value > 1000000) {
			return false;
		}
	}
	out = static_cast<int>(value);
	return true;
}

// Outcome of pulling one whole entry out of the archive, as a sentence fit for
// a log line. Empty means success.
std::string read_whole_entry(const rv_zipreader &zip, const char *name,
	int64_t max_size,
	std::vector<unsigned char> &out)
{
	const int64_t size = zip.size(name);
	if (size < 0) {
		return "no such entry in the archive";
	}
	if (size > max_size) {
		return std::format("entry is {} bytes, over the {} byte ceiling", size,
			max_size);
	}

	try {
		out.assign(static_cast<std::size_t>(size), 0);
	} catch (const std::bad_alloc &) {
		return "out of memory";
	}
	if (size == 0) {
		return std::string();
	}

	int64_t nread = 0;
	switch (zip.read(name, out.data(), size, nread)) {
	case rv_zipread::ok:
		break;
	case rv_zipread::not_found:
		return "no such entry in the archive";
	case rv_zipread::short_buffer:
		return "the entry grew between measuring and reading it";
	case rv_zipread::corrupt:
		return "the archive's bookkeeping for this entry does not hold up";
	case rv_zipread::crc_mismatch:
		return "checksum mismatch — the entry is not the bytes that were written";
	case rv_zipread::io_error:
		return "the host file failed the read";
	}
	if (nread != size) {
		return "short read";
	}
	return std::string();
}

// Write `code` to a fresh private file and hand back its path.
//
// mkstemp is what makes the name unpredictable: the console must not open a
// path an attacker could have guessed and pre-created as a symlink to something
// else, which is exactly the classic /tmp race. mkstemp creates with O_EXCL and
// mode 0600, and the fchmod below adds only the execute bit the mapping needs —
// 0700 total, this user and nobody else. A group- or world-writable staging
// file would be a way to swap the disc's code out between this write and the
// dlopen a few lines later.
std::string extract_code(const std::vector<unsigned char> &code,
	std::string &out_path)
{
	const char *tmpdir = std::getenv("TMPDIR");
	std::string dir =
		(tmpdir != nullptr && *tmpdir != '\0') ? std::string(tmpdir) : "/tmp";
	while (dir.size() > 1 && dir.back() == '/') {
		dir.pop_back();
	}

	std::string tmpl = dir + "/mppcdisc-XXXXXX";
	std::vector<char> name(tmpl.begin(), tmpl.end());
	name.push_back('\0');

	const int fd = ::mkstemp(name.data());
	if (fd < 0) {
		return std::format("cannot create a staging file in '{}': {}", dir,
			std::strerror(errno));
	}

	// From here on the file exists, so every failure path must remove it.
	out_path.assign(name.data());

	std::string error;
	if (::fchmod(fd, S_IRWXU) != 0) {
		error = std::format("cannot make the staging file executable: {}",
			std::strerror(errno));
	}

	std::size_t written = 0;
	while (error.empty() && written < code.size()) {
		const ssize_t rc =
			::write(fd, code.data() + written, code.size() - written);
		if (rc < 0) {
			if (errno == EINTR) {
				continue;
			}
			error = std::format("cannot write the staging file: {}",
				std::strerror(errno));
			break;
		}
		if (rc == 0) {
			error = "the staging file accepted no bytes";
			break;
		}
		written += static_cast<std::size_t>(rc);
	}

	if (::close(fd) != 0 && error.empty()) {
		// A close() that fails is a write that did not land — the mapping the
		// loader is about to make would be of a truncated object file.
		error =
			std::format("cannot close the staging file: {}", std::strerror(errno));
	}

	if (!error.empty()) {
		::unlink(out_path.c_str());
		out_path.clear();
	}
	return error;
}

// ELF note name/desc fields are padded to a 4-byte boundary (elf(5)). The
// uint64_t parameter is the overflow guard: a 32-bit n_namesz/n_descsz widens
// at the call site, so `+ 3` can never wrap.
constexpr uint64_t align_elf_note_field_size(uint64_t size)
{
	return (size + 3ull) & ~3ull;
}

} // namespace

bool rv_pcmanifest_parse(const std::string &text, rv_pcdiscinfo &out)
{
	// Minimal by design. The full TOML subset lives in pdklib
	// (pdklib/rv_manifest/rv_manifest.hpp), where a human is watching and a
	// typo deserves a line number. Here the manifest is untrusted input and the
	// console wants four keys out of it, so this walks lines, keeps nothing it
	// was not asked for, and cannot fail in a way that matters: an unreadable
	// manifest simply leaves `out` at its defaults, and abi_version 0 then fails
	// the handshake below.
	out.entry = kDefaultCodeEntry;

	bool in_disc = false;
	std::string_view rest(text);
	while (!rest.empty()) {
		std::string_view line = rest;
		const std::size_t eol = rest.find('\n');
		if (eol == std::string_view::npos) {
			rest = std::string_view();
		} else {
			line = rest.substr(0, eol);
			rest = rest.substr(eol + 1);
		}

		line = trim(line);
		if (line.empty() || line.front() == '#') {
			continue;
		}

		if (line.front() == '[') {
			const std::size_t close = line.find(']');
			if (close == std::string_view::npos) {
				continue; // garbage; not our problem
			}
			in_disc = trim(line.substr(1, close - 1)) == "disc";
			continue;
		}

		if (!in_disc) {
			continue;
		}

		const std::size_t eq = line.find('=');
		if (eq == std::string_view::npos) {
			continue;
		}

		const std::string_view key = trim(line.substr(0, eq));
		const std::string value = manifest_value(line.substr(eq + 1));

		if (key == "id") {
			out.id = value;
		} else if (key == "title") {
			out.title = value;
		} else if (key == "entry") {
			if (!value.empty()) {
				out.entry = value;
			}
		}
	}

	return true;
}

rv_pcloader::~rv_pcloader()
{
	unload();
}

void rv_pcloader::notify_initialized(const rv_de *disc)
{
	if (disc_ != nullptr && disc == disc_) {
		initialized_ = true;
	}
}

// NEUROSLOP-END

template <typename O>
bool rv_pcloader::pod_peek(std::vector<unsigned char> &buf, int64_t off_start,
	int64_t off_end, O &out)
{
	static_assert(std::is_trivially_copyable_v<O>);

	if (off_start < 0 || off_start > (int64_t)buf.size() - (int64_t)sizeof(O)) {
		return false;
	}
	if (off_end < off_start || off_end > (int64_t)buf.size()) {
		return false;
	}

	std::memcpy(&out, buf.data() + off_start, sizeof(O));
	return true;
}

int64_t rv_pcloader::pre_dlopen_check(rv_zipreader *zip,
	const char *info_entry)
{
	int64_t size = zip->size(info_entry);
	if (size <= 0) {
		// TODO(rv_log_escape): 22 calls in this file. The console is its only
		// caller, so it does not belong in pdklib — find it a console-side home.
		RV_LOG_ERR(
			"pcloader",
			"code entry '{}' in '{}' is missing or empty; there is no binary "
			"to version-check",
			rv_pdklib::rv_log_escape(info_entry), rv_pdklib::rv_log_escape(zip->path().c_str()));
		return RV_ERR_INVAL;
	}

	// One bulk read of the whole entry: the zip reader verifies the CRC over
	// all of it, and no byte below is trusted before that verdict.
	int64_t nread;
	std::vector<unsigned char> buffer(size);
	rv_zipread zipread = zip->read(info_entry, buffer.data(), size, nread);
	if (zipread != rv_3dmppc::rv_zipread::ok || nread != size) {
		RV_LOG_ERR(
			"pcloader",
			"cannot read code entry '{}' from '{}' (zip verdict {}, {} of {} "
			"bytes); refusing a disc whose code cannot be inspected",
			rv_pdklib::rv_log_escape(info_entry), rv_pdklib::rv_log_escape(zip->path().c_str()),
			static_cast<int>(zipread), nread, size);
		return RV_ERR_INVAL;
	}

	// The ELF header lives at offset 0 by definition — elf(5), "ELF header
	// (Ehdr)". Each check below legalises exactly the fields the next step
	// relies on; until a check has passed, the fields it covers are just bytes.
	Elf64_Ehdr mppcdisc_ehdr;
	if (!pod_peek(buffer, 0, sizeof(mppcdisc_ehdr), mppcdisc_ehdr)) {
		RV_LOG_ERR(
			"pcloader",
			"code entry '{}' is only {} bytes — smaller than an ELF64 header; "
			"not a loadable binary",
			rv_pdklib::rv_log_escape(info_entry), size);
		return RV_ERR_INVAL;
	}

	if (memcmp(mppcdisc_ehdr.e_ident, ELFMAG, SELFMAG) != 0) {
		RV_LOG_ERR(
			"pcloader",
			"code entry '{}' does not start with the ELF magic; it is not an "
			"ELF object at all",
			rv_pdklib::rv_log_escape(info_entry));
		return RV_ERR_INVAL;
	}

	// Single-byte fields, so they are readable regardless of byte order — and
	// only their verdict makes the multi-byte fields of the struct meaningful:
	// everything was copied under a little-endian assumption.
	if (mppcdisc_ehdr.e_ident[EI_CLASS] != ELFCLASS64 ||
		mppcdisc_ehdr.e_ident[EI_DATA] != ELFDATA2LSB) {
		RV_LOG_ERR("pcloader",
			"code entry '{}' is not a 64-bit little-endian ELF (class {}, "
			"data {}); this console only runs ELF64 LE discs",
			rv_pdklib::rv_log_escape(info_entry), (int)mppcdisc_ehdr.e_ident[EI_CLASS],
			(int)mppcdisc_ehdr.e_ident[EI_DATA]);
		return RV_ERR_INVAL;
	}

	if (mppcdisc_ehdr.e_type != ET_DYN || mppcdisc_ehdr.e_machine != EM_X86_64) {
		RV_LOG_ERR("pcloader",
			"code entry '{}' is not an x86-64 shared object (e_type {}, "
			"e_machine {}); it cannot run on this console",
			rv_pdklib::rv_log_escape(info_entry), mppcdisc_ehdr.e_type,
			mppcdisc_ehdr.e_machine);
		return RV_ERR_INVAL;
	}

	// The program-header walk steps by e_phentsize; if the file declares a
	// different stride than the Elf64_Phdr we read with, every entry after the
	// first would be read misaligned with the table.
	if (mppcdisc_ehdr.e_phentsize != sizeof(Elf64_Phdr)) {
		RV_LOG_ERR(
			"pcloader",
			"code entry '{}' declares {}-byte program headers, elf(5) says {}; "
			"its segment table cannot be walked",
			rv_pdklib::rv_log_escape(info_entry), mppcdisc_ehdr.e_phentsize,
			sizeof(Elf64_Phdr));
		return RV_ERR_INVAL;
	}

	bool version_info_found_flag = false;
	Elf64_Phdr potential_note;
	rv_mppc_note_desc version_info;
	for (int i = 0; i < mppcdisc_ehdr.e_phnum && !version_info_found_flag; ++i) {
		if (!pod_peek(buffer, mppcdisc_ehdr.e_phoff + i * mppcdisc_ehdr.e_phentsize,
				(mppcdisc_ehdr.e_phoff + i * mppcdisc_ehdr.e_phentsize) +
					sizeof(potential_note),
				potential_note)) {
			RV_LOG_WARN("pcloader", "can not to peek elf64_phdr from disc.so ");
			continue;
		}

		if (potential_note.p_type == PT_NOTE) {
			const uint64_t segment_offset =
				static_cast<uint64_t>(potential_note.p_offset);
			const uint64_t segment_size =
				static_cast<uint64_t>(potential_note.p_filesz);
			const uint64_t buffer_size = static_cast<uint64_t>(buffer.size());

			if (segment_offset > buffer_size ||
				segment_size > buffer_size - segment_offset) {
				RV_LOG_ERR("pcloader", "ELF note segment exceeds mppcdisc bounds");
				return RV_ERR_INVAL;
			}

			const uint64_t segment_end = segment_offset + segment_size;

			constexpr uint64_t expected_owner_size =
				sizeof(rv_pdk::RV_MPPC_NOTE_OWNER);
			constexpr uint64_t expected_desc_size = sizeof(rv_pdk::rv_mppc_note_desc);

			Elf64_Nhdr note{};

			uint64_t note_offset = segment_offset;
			uint64_t note_size = 0;

			for (;; note_offset += note_size) {
				if (note_offset >= segment_end) {
					break;
				}

				const uint64_t segment_bytes_left = segment_end - note_offset;

				if (segment_bytes_left < sizeof(note)) {
					RV_LOG_WARN("pcloader",
						"ELF note header exceeds note segment bounds");
					break;
				}

				const uint64_t note_header_end = note_offset + sizeof(note);

				if (!pod_peek(buffer, note_offset, note_header_end, note)) {
					RV_LOG_ERR("pcloader", "cannot read ELF note header from mppcdisc");
					return RV_ERR_INVAL;
				}

				const uint64_t owner_size = static_cast<uint64_t>(note.n_namesz);
				const uint64_t desc_size = static_cast<uint64_t>(note.n_descsz);

				const uint64_t aligned_owner_size =
					align_elf_note_field_size(owner_size);
				const uint64_t aligned_desc_size = align_elf_note_field_size(desc_size);

				note_size = sizeof(note) + aligned_owner_size + aligned_desc_size;

				if (note_size > segment_bytes_left) {
					RV_LOG_WARN("pcloader", "ELF note exceeds note segment bounds");
					break;
				}

				const bool header_matches = owner_size == expected_owner_size &&
					desc_size == expected_desc_size &&
					note.n_type == rv_pdk::RV_MPPC_NOTE_TYPE;

				if (!header_matches) {
					RV_LOG_WARN(
						"pcloader",
						"ELF note header does not match the requested version note");
					continue;
				}

				const uint64_t owner_offset = note_offset + sizeof(note);
				const uint64_t desc_offset = owner_offset + aligned_owner_size;
				const uint64_t note_end = note_offset + note_size;

				const auto *owner = buffer.data() + owner_offset;

				if (std::memcmp(owner, rv_pdk::RV_MPPC_NOTE_OWNER,
						expected_owner_size) != 0) {
					RV_LOG_WARN(
						"pcloader",
						"ELF note owner does not match the requested version note");
					continue;
				}

				if (!pod_peek(buffer, desc_offset, note_end, version_info)) {
					RV_LOG_WARN("pcloader",
						"cannot read version descriptor from ELF note");
					continue;
				}

				if (std::memcmp(version_info.magic, RV_MPPC_NOTE_MAGIC_DEF,
						sizeof(version_info.magic)) != 0) {
					RV_LOG_WARN("pcloader",
						"ELF note descriptor does not carry the mppc magic");
					continue;
				}

				version_info_found_flag = true;
				break;
			}
		}
	}

	if (!version_info_found_flag) {
		RV_LOG_ERR("pcloader", "version did not found in mppcdisc");
		return RV_ERR_INVAL;
	}

	if (rv_pdk::RV_MPPC_VER_MAJOR != version_info.version_major ||
		rv_pdk::RV_MPPC_VER_MINOR < version_info.version_minor) {
		RV_LOG_ERR("pcloader",
			"disc version are incompatible to currect console version: "
			"disc version is: {}.{}; ",
			version_info.version_major, version_info.version_minor);
		return RV_ERR_INVAL;
	}

	return RV_OK;
}

// NEUROSLOP-BEGIN (claude-opus-5)

int64_t rv_pcloader::load(const char *archive_path)
{
	unload();

	if (archive_path == nullptr || *archive_path == '\0') {
		RV_LOG_ERR("pcloader", "no disc path was given");
		return RV_ERR_INVAL;
	}

	// Check the file.
	std::error_code ec;
	if (!std::filesystem::is_regular_file(std::filesystem::path(archive_path),
			ec)) {
		RV_LOG_ERR("pcloader",
			"no disc at '{}': the path does not name a readable file",
			rv_pdklib::rv_log_escape(archive_path));
		return RV_ERR_NOENT;
	}

	// Check the container.
	rv_zipreader zip;
	std::string zip_error;
	if (!zip.open(archive_path, zip_error)) {
		RV_LOG_ERR("pcloader", "'{}' is not a readable .mppcdisc archive: {}",
			rv_pdklib::rv_log_escape(archive_path),
			rv_pdklib::rv_log_escape(zip_error.c_str(), 160));
		return RV_ERR_IO;
	}

	// Check the manifest.
	std::vector<unsigned char> manifest_bytes;
	std::string why =
		read_whole_entry(zip, kManifestEntry, kManifestMaxSize, manifest_bytes);
	if (!why.empty()) {
		RV_LOG_ERR("pcloader", "'{}' carries no usable '{}': {}",
			rv_pdklib::rv_log_escape(archive_path), kManifestEntry, why);
		return RV_ERR_NOENT;
	}

	std::string manifest_text(
		reinterpret_cast<const char *>(manifest_bytes.data()),
		manifest_bytes.size());
	rv_pcmanifest_parse(manifest_text, info_);

	// PATTERN: version verdict from BYTES, BEFORE dlopen. A disc built against
	// a different PDK sees the console's structs at the wrong offsets, and that
	// failure does not announce itself: it is garbage geometry, a silent
	// corruption, a crash three minutes into play. dlopen would already run the
	// disc's constructors, so the verdict is read straight from the code
	// entry's ELF note (elf(5)) while it is still nothing but bytes in a buffer
	// — the mismatched code is never mapped at all. This is the ONLY version
	// check: the factory below creates the disc and decides nothing.
	if (pre_dlopen_check(&zip, info_.entry.c_str()) < 0) {
		RV_LOG_ERR("pcloader",
			"disc '{}' failed the pre-load inspection of its code entry — "
			"the exact "
			"refusal is in the log line above; its code will not be mapped",
			rv_pdklib::rv_log_escape(info_.id.c_str()));
		return RV_ERR_INVAL;
	}

	// (4) The code entry, and the extraction the OS loader forces on us — see
	// the THEOREM at the top of rv_pcloader.hpp: dlopen maps a file, so the code
	// needs an inode of its own before it can be anything but bytes in a zip.
	std::vector<unsigned char> code;
	why = read_whole_entry(zip, info_.entry.c_str(), kCodeMaxSize, code);
	if (!why.empty()) {
		RV_LOG_ERR("pcloader",
			"disc '{}' names its code entry '{}', which is unusable: {}",
			rv_pdklib::rv_log_escape(info_.id.c_str()),
			rv_pdklib::rv_log_escape(info_.entry.c_str()), why);
		return RV_ERR_NOENT;
	}

	why = extract_code(code, temp_path_);
	if (!why.empty()) {
		RV_LOG_ERR("pcloader", "cannot stage the code of disc '{}' for loading: {}",
			rv_pdklib::rv_log_escape(info_.id.c_str()), why);
		unload();
		return RV_ERR_IO;
	}

	// (5) RTLD_NOW resolves every relocation right here: a disc missing a symbol
	// must fail on the loading screen, where the message is readable, and not
	// forty minutes in when the code path that needed it finally runs. RTLD_LOCAL
	// keeps the disc's symbols out of the process-global namespace, so two discs
	// — or a disc and the console — cannot capture each other's names by
	// accident, and nothing the disc exports beyond the two ABI symbols is
	// reachable by anyone.
	handle_ = ::dlopen(temp_path_.c_str(), RTLD_NOW | RTLD_LOCAL);
	if (handle_ == nullptr) {
		const char *dl_error = ::dlerror();
		RV_LOG_ERR(
			"pcloader", "dlopen of disc '{}' failed: {}",
			rv_pdklib::rv_log_escape(info_.id.c_str()),
			rv_pdklib::rv_log_escape(dl_error != nullptr ? dl_error : "no reason given", 160));
		unload();
		return RV_ERR_IO;
	}

	// (6) Both symbols or neither. A disc that can be created but not destroyed
	// is not half-loadable, it is a leak with a vtable — and the only code that
	// may destroy the object is the code that made it (pdk/de/rv_dv.hpp).
	::dlerror(); // clear any stale error before the lookups
	auto create = reinterpret_cast<rv_mppc_disc_create_fn>(
		::dlsym(handle_, RV_MPPC_DISC_ENTRY_CREATE));
	auto destroy = reinterpret_cast<rv_mppc_disc_destroy_fn>(
		::dlsym(handle_, RV_MPPC_DISC_ENTRY_DESTROY));
	if (create == nullptr || destroy == nullptr) {
		RV_LOG_ERR("pcloader",
			"disc '{}' exports no {}(); it was not built with "
			"RV_MPPC_DISC_ENTRY_DEF",
			rv_pdklib::rv_log_escape(info_.id.c_str()),
			create == nullptr ? RV_MPPC_DISC_ENTRY_CREATE : RV_MPPC_DISC_ENTRY_DESTROY);
		unload();
		return RV_ERR_INVAL;
	}

	// Совместимость версии решена ДО этого места — pre_dlopen_check по ноте,
	// ещё до dlopen. create() в решении не участвует: это чистая фабрика, и
	// nullptr от неё — отказ диска создаться, не вердикт о версии.
	rv_de *disc = nullptr;
	try {
		disc = create();
	} catch (...) {
		// An exception escaping an extern "C" factory is not something the ABI
		// permits, so this is defence and not a contract: a badly built disc must
		// still not take the console down with it.
		disc = nullptr;
	}
	if (disc == nullptr) {
		RV_LOG_ERR("pcloader",
			"disc '{}' returned no object from {}(); refusing the disc",
			rv_pdklib::rv_log_escape(info_.id.c_str()), RV_MPPC_DISC_ENTRY_CREATE);
		unload();
		return RV_ERR_INVAL;
	}

	disc_ = disc;
	destroy_ = destroy;

	RV_LOG_INFO(
		"pcloader", "loaded disc '{}' ('{}') from '{}' at 3dmppc version {}.{}",
		rv_pdklib::rv_log_escape(info_.id.c_str()), rv_pdklib::rv_log_escape(info_.title.c_str()),
		rv_pdklib::rv_log_escape(archive_path), RV_MPPC_VER_MAJOR, RV_MPPC_VER_MINOR);
	return RV_OK;
}

// PATTERN: RAII — the teardown order lives here and nowhere else, and it is the
// exact reverse of construction:
//
//   disc_shutdown() -> mppc_disc_destroy() -> dlclose() -> unlink()
//
// dlclose AFTER destroy, never before: dlclose unmaps the library's text, and
// the destructor is IN that text. Destroying afterwards calls a function whose
// instructions are no longer mapped — the process jumps into a hole, at
// shutdown, where the crash looks like anything but its cause. The unlink comes
// last for the same shape of reason: while the code is mapped, the file is what
// the kernel pages from.
void rv_pcloader::unload()
{
	if (disc_ != nullptr) {
		// rv_de.hpp: the hook runs after the last frame and NOT for a disc that
		// refused to start. The facade is still valid at this point — that is
		// precisely why it runs before destroy and before dlclose.
		if (initialized_) {
			try {
				disc_->disc_shutdown();
			} catch (...) {
				RV_LOG_ERR("pcloader",
					"disc_shutdown() of '{}' threw; tearing down anyway",
					rv_pdklib::rv_log_escape(info_.id.c_str()));
			}
		}
		if (destroy_ != nullptr) {
			destroy_(disc_);
		}
	}
	disc_ = nullptr;
	destroy_ = nullptr;
	initialized_ = false;

	if (handle_ != nullptr) {
		::dlclose(handle_);
		handle_ = nullptr;
	}

	if (!temp_path_.empty()) {
		// The staging file has done its job the moment the code is unmapped.
		// Removing it is not tidiness: it is an executable copy of somebody's
		// game sitting in a world-readable directory.
		if (::unlink(temp_path_.c_str()) != 0 && errno != ENOENT) {
			RV_LOG_WARN("pcloader", "could not remove the staging file '{}': {}",
				temp_path_, std::strerror(errno));
		}
		temp_path_.clear();
	}
}

} // namespace rv_3dmppc
