// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — .mppcdisc loader: manifest, code extraction, dlopen.
// ──────────────────────────────────────────────────────────────────────────────
//
// The other half of pdk/rv_abi.hpp: the console side of the disc boundary. It
// turns a `.mppcdisc` file on disk into a live rv_de* and, just as importantly,
// takes it apart again in the one order that is safe.
//
// THEOREM: a `.so` cannot be loaded from inside the archive. dlopen does not
// take bytes, it takes a PATH: the dynamic loader maps the code with mmap(),
// which needs a real inode the kernel can back the mapping with, page by page,
// for as long as the code is resident. An entry inside a zip is a byte range
// belonging to another file — there is nothing to map, and the loader has no
// interface through which the console could feed it a buffer. So the code entry
// is extracted to a private temporary file first, and that file is what dlopen
// sees. It costs one write of a few hundred kilobytes at boot, once, and nothing
// per frame. (The Linux-only memfd_create + /proc/self/fd/N trick removes the
// disk round trip and is deliberately not used here: it is not portable, and the
// portable path is the one that must work.)
#pragma once

#include <cstdint>
#include <string>

#include "pdk/de/rv_de.hpp"
#include "pdk/de/rv_dv.hpp"
#include "rv_pconsole/cd/rv_pczip.hpp"

namespace rv_3dmppc {

// What the console needs to know about a disc BEFORE it agrees to run its code.
// A strict subset of the manifest the burner writes (pdk/tools/mppcburner/
// rv_burner_manifest.hpp holds the full model): the console reads only what it must,
// because every field it parses is a field an attacker-supplied archive gets to
// influence.
struct rv_pcdiscinfo {
    uint32_t disc_version_major = 0;
    uint32_t disc_version_minor = 0;
    std::string id;     // short mppcdisc name
    std::string title;  // human mppcdisc title (UNTRUSTED)
    std::string entry;  // archive entry holding the code (default "disc.so")
};

// Fill `out` from the text of a `disc.toml`, reading only the `[disc]` section
// and only the four keys above. Returns true when the text was well-formed
// enough to look at; unknown sections, unknown keys and blank lines are ignored
// rather than refused, because the burner writes more than the console reads.
//
// It never throws and never trusts a length: a manifest arrives inside the
// archive and may be arbitrary bytes.
bool rv_pcmanifest_parse(const std::string& text, rv_pcdiscinfo& out);

// PATTERN: RAII — one object owns the whole loaded-disc state (temporary file,
// dlopen handle, the disc object) and its destructor is the ONLY teardown path,
// so the order below cannot be got wrong by a caller taking an early return:
//
//   1. disc_shutdown()          the disc's last chance to touch the facade
//   2. mppc_disc_destroy(disc)  the disc's own destructor, from the disc's code
//   3. dlclose(handle)          the code is unmapped only now
//   4. unlink(temporary file)   the inode goes last, and only then
//
// Steps 2 and 3 in that order are not a preference. dlclose() may unmap the
// library's text segment; the destructor lives IN that text segment. Calling
// destroy after dlclose is calling a function whose instructions are no longer
// mapped — a jump into an unmapped page, i.e. a segfault with a stack trace
// that points nowhere, on shutdown, where nobody is looking. Same reason step 1
// precedes step 2: disc_shutdown is a virtual on an object the destructor is
// about to end.
class rv_pcloader {
   public:
    rv_pcloader() = default;
    ~rv_pcloader();

    // The handle, the disc pointer and the temporary path are one indivisible
    // ownership; copying or moving it would mean two objects racing to run the
    // teardown above.
    rv_pcloader(const rv_pcloader&) = delete;
    rv_pcloader& operator=(const rv_pcloader&) = delete;
    rv_pcloader(rv_pcloader&&) = delete;
    rv_pcloader& operator=(rv_pcloader&&) = delete;

    // NEUROSLOP-END

    // Pre-dlopen inspection of the code entry `info_entry` inside the mounted
    // archive. dlopen runs the library's constructors before returning, so any
    // compatibility verdict must come from the FILE'S BYTES, never from loaded
    // code: the entry is read whole (CRC-checked by the zip reader) and its ELF
    // structure is parsed in memory, per elf(5). Today it validates the ELF64
    // header (magic, class, byte order, e_type/e_machine, program-header
    // stride); the walk to the RV_MPPC version note (PT_NOTE segments) is the
    // part still to be written. Returns RV_OK or a negative rv_err, logging the
    // exact refusal reason.
    int64_t pre_dlopen_check(rv_zipreader* zip, const char* info_entry);

    // NEUROSLOP-BEGIN (claude-opus-5)

    // Mount `archive_path`, check the handshake and bring the disc's code up.
    // Returns RV_OK, or a negative rv_err after logging exactly what went wrong
    // — every refusal path names itself in the log, none of them throws, and
    // none of them leaves a partially loaded disc behind.
    int64_t load(const char* archive_path);

    // The live disc, or nullptr when nothing is loaded. BORROWED: it belongs to
    // this object and dies with it, and so does everything it returns — in
    // particular disc_title(), which is a literal inside the unloaded-at-
    // teardown text segment.
    rv_pdk::rv_de* disc() const { return disc_; }

    bool loaded() const { return disc_ != nullptr; }

    // What the manifest declared. Valid after a successful load.
    const rv_pcdiscinfo& info() const { return info_; }

    // Told by the console once disc_initialize() has returned success, so that
    // teardown knows whether disc_shutdown() is owed: rv_de.hpp says the hook
    // runs on every path out of the frame loop but NEVER for a disc that
    // refused to start. The pointer is compared rather than trusted — the
    // console may be running a disc this loader did not produce (the built-in
    // rv_dmain), and that one's lifecycle is none of our business.
    void notify_initialized(const rv_pdk::rv_de* disc);

    // Idempotent teardown, in the order documented above. Called by the
    // destructor; public so a caller may end a disc early and see the log lines
    // in place rather than at some indeterminate point during unwinding.
    void unload();

   private:
    rv_pcdiscinfo info_;

    // Path of the extracted code file, empty when nothing was extracted. Kept
    // as state precisely so the destructor can remove it on EVERY exit path.
    std::string temp_path_;

    // NEUROSLOP-END
    template <typename O>
    bool pod_peek(std::vector<unsigned char>& buf, int64_t off_start, int64_t off_end, O& out);
    // NEUROSLOP-BEGIN (claude-opus-5)

    void* handle_ = nullptr;
    rv_pdk::rv_de* disc_ = nullptr;
    rv_pdk::rv_mppc_disc_destroy_fn destroy_ = nullptr;

    // Whether disc_initialize() succeeded — see notify_initialized().
    bool initialized_ = false;
};

}  // namespace rv_3dmppc
