// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — console assembly: disc loading and the frame loop added.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

#include "pdk/de/rv_de.hpp"
#include "pdk/rv_pdko.hpp"
#include "rv_pconsole/ca/rv_pcca.hpp"
#include "rv_pconsole/cd/rv_pccd.hpp"
#include "rv_pconsole/cio/rv_pccio.hpp"
#include "rv_pconsole/cm/rv_pccm.hpp"
#include "rv_pconsole/cv/rv_pccv.hpp"
#include "rv_pconsole/rv_pchost.hpp"
#include "rv_pconsole/rv_pcloader.hpp"
#include "rv_pconsole/rv_pconsole_conf.hpp"

namespace rv_3dmppc {

// PATTERN: composition root. This is the single place where the concrete
// machine is assembled — the host, the five controllers, and the geometry they
// were built from. Nothing below constructs a subsystem: a controller receives
// what it needs and never reaches sideways for it.
class rv_pconsole : public rv_pdk::rv_pdko {
   private:
    rv_pconsole_params params_;

    // NEUROSLOP-BEGIN (claude-opus-5)
    // DECLARATION ORDER IS LOAD-BEARING: the host owns SDL and is borrowed by
    // cio_ and cv_, so it must be constructed before them and torn down after.
    rv_pchost host_;
    // NEUROSLOP-END

    // TODO(Claude-инструкция, код твой). Объяви здесь поле rv_pccl cl_;
    // и включи "rv_pconsole/cl/rv_pccl.hpp" наверху.
    //
    // ПОРЯДОК ОБЪЯВЛЕНИЯ ВАЖЕН, как и для host_ выше. Поля разрушаются в
    // порядке, ОБРАТНОМ объявлению, а loader_ (объявлен последним, значит
    // умирает первым) в своём teardown зовёт disc_shutdown() — а тот имеет
    // право трогать любой контроллер, включая этот. Значит cl_ обязан стоять
    // ВЫШЕ loader_. Поставь его в общий ряд контроллеров, по алфавиту.
    rv_pcca ca_;
    rv_pccd cd_;
    rv_pccio cio_;
    rv_pccm cm_;
    rv_pccv cv_;

    // NEUROSLOP-BEGIN (claude-opus-5)
    // DECLARATION ORDER IS LOAD-BEARING here too: declared LAST means destroyed
    // FIRST, and the loader's teardown runs disc_shutdown() — a hook that is
    // allowed to touch the facade, i.e. every controller above it. A disc's last
    // words must not be spoken to subsystems that are already gone.
    rv_pcloader loader_;
    // NEUROSLOP-END

   public:
    explicit rv_pconsole(const rv_pconsole_conf& conf);

    ~rv_pconsole() = default;

    rv_pdk::rv_ca* ca() override;
    rv_pdk::rv_cd* cd() override;
    rv_pdk::rv_cio* cio() override;
    rv_pdk::rv_cm* cm() override;
    rv_pdk::rv_cv* cv() override;

    // TODO(Claude-инструкция, код твой). Добавь rv_pdk::rv_cl* cl() override;
    // Тело в rv_pconsole.cpp — одна строка, возврат адреса поля. Смотри, как
    // сделаны соседи, и повтори.

    // NEUROSLOP-BEGIN (claude-opus-5)
    // Put a `.mppcdisc` in the machine: load the code it carries and mount the
    // very same archive as the drive's medium, so the running disc reads its
    // assets out of the file it was booted from and not from somewhere else.
    //
    // Returns the disc to hand to disc_run(), or nullptr when the disc was
    // refused — the reason is already in the log by then, named precisely (no
    // such file, not an archive, no manifest, wrong ABI, no code, dlopen,
    // missing symbol, refused handshake). The pointer is BORROWED: the console
    // owns the loaded disc and unloads it when it is destroyed, so it must not
    // outlive this console.
    rv_pdk::rv_de* disc_load(const char* path);
    // NEUROSLOP-END

    // NEUROSLOP-BEGIN (claude-opus-5)
    // PATTERN: inversion of control. The frame loop belongs to the console; the
    // disc lives inside the rv_de hooks and never owns a loop of its own.
    //
    // Returns RV_OK when the run ends normally (the disc asked to stop, the
    // frame budget ran out, or the user powered the machine off), or a negative
    // rv_err if the disc refused to initialize or the display would not come up.
    int64_t disc_run(rv_pdk::rv_de& disc);
    // NEUROSLOP-END
};

}  // namespace rv_3dmppc
