// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 8 — Wavefront .obj parsing from an in-memory buffer, no file I/O.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <vector>

#include "pdklib/rv_math/rv_math.hpp"

namespace rv_pdklib {

// A Wavefront .obj reader that takes BYTES, never a path.
//
// Reading is the drive's privilege: a disc calls rv_cd::asset_open / asset_size /
// asset_read into a buffer IT owns, and hands that buffer here. If this header
// took a filename it would quietly grow a second, private file system next to the
// one the console models — and a disc could then read something that is not on
// the disc at all. The whole medium abstraction would be decoration.
//
// Supported: v, vt, vn, f. Faces of any vertex count are fan-triangulated; the
// v/vt/vn reference forms (i, i/j, i//k, i/j/k) and NEGATIVE (relative) indices
// are handled. Everything else — o, g, s, usemtl, mtllib, comments — is skipped
// on purpose: materials are a second file this parser is forbidden to fetch, and
// the console has no material model anyway. Smoothing groups likewise: the file's
// own vn are used, or none are.

// One corner of a triangle: three indices into the mesh's arrays, or -1 when the
// file did not give that channel. Indices are already ZERO-based and validated.
struct rv_obj_index {
    int32_t position;
    int32_t uv;
    int32_t normal;
};

struct rv_obj_triangle {
    rv_obj_index corner[3];
};

// The parse result. Deliberately the file's own structure — separate index
// streams — rather than a de-indexed vertex soup: a disc that only needs
// positions should not pay for expanded normals, and welding is a decision with
// tolerances that belong to whoever makes it.
struct rv_obj_mesh {
    std::vector<rv_vec3> positions;
    std::vector<rv_vec2> uvs;
    std::vector<rv_vec3> normals;
    std::vector<rv_obj_triangle> triangles;
};

namespace rv_obj_detail {

inline bool is_blank(char c) { return c == ' ' || c == '\t' || c == '\r'; }

inline void skip_blanks(const char*& p, const char* end) {
    while (p < end && is_blank(*p)) ++p;
}

// std::from_chars accepts neither leading blanks nor a leading '+', both of which
// occur in the wild, so they are eaten here first.
inline bool parse_float(const char*& p, const char* end, float& out) {
    skip_blanks(p, end);
    if (p < end && *p == '+') ++p;
    const std::from_chars_result result = std::from_chars(p, end, out);
    if (result.ec != std::errc{}) return false;
    p = result.ptr;
    return true;
}

inline bool parse_int(const char*& p, const char* end, int& out) {
    skip_blanks(p, end);
    if (p < end && *p == '+') ++p;
    const std::from_chars_result result = std::from_chars(p, end, out);
    if (result.ec != std::errc{}) return false;
    p = result.ptr;
    return true;
}

// THEOREM: .obj index resolution. A POSITIVE index is 1-based and absolute; a
// NEGATIVE index counts back from the end of the list AS IT STANDS AT THIS LINE
// (-1 is the vertex declared immediately above), which is what lets generators
// emit self-contained blocks that can be concatenated. Zero is not a valid index
// in the format. Both forms are normalised to a zero-based offset here, so
// nothing downstream ever sees the file's numbering.
inline bool resolve_index(int raw, std::size_t count, int32_t& out) {
    if (raw > 0) {
        if (static_cast<std::size_t>(raw) > count) return false;
        out = static_cast<int32_t>(raw - 1);
        return true;
    }
    if (raw < 0) {
        const long long offset = static_cast<long long>(count) + raw;
        if (offset < 0) return false;
        out = static_cast<int32_t>(offset);
        return true;
    }
    return false;
}

// One "i", "i/j", "i//k" or "i/j/k" reference. Missing channels stay -1.
inline bool parse_corner(const char*& p, const char* end, const rv_obj_mesh& mesh,
                         rv_obj_index& out) {
    out = rv_obj_index{-1, -1, -1};

    int raw = 0;
    if (!parse_int(p, end, raw)) return false;
    if (!resolve_index(raw, mesh.positions.size(), out.position)) return false;

    if (p >= end || *p != '/') return true;
    ++p;
    if (p < end && *p != '/') {
        if (!parse_int(p, end, raw)) return false;
        if (!resolve_index(raw, mesh.uvs.size(), out.uv)) return false;
    }

    if (p >= end || *p != '/') return true;
    ++p;
    if (!parse_int(p, end, raw)) return false;
    if (!resolve_index(raw, mesh.normals.size(), out.normal)) return false;
    return true;
}

}  // namespace rv_obj_detail

// Parse `size` bytes of .obj text into `out`. The buffer need not be
// NUL-terminated and is only read.
//
// Returns false on malformed geometry (an unparsable number, an index naming a
// vertex that does not exist, a face with fewer than three corners). `out` then
// holds whatever was parsed up to the failure and must not be drawn — a disc
// treats this like any other content error and refuses to run.
inline bool rv_obj_parse(const void* data, std::size_t size, rv_obj_mesh& out) {
    out = rv_obj_mesh{};
    if (data == nullptr && size != 0) return false;

    const char* p = static_cast<const char*>(data);
    const char* const end = p + size;
    std::vector<rv_obj_index> corners;

    while (p < end) {
        const char* line_end = p;
        while (line_end < end && *line_end != '\n') ++line_end;

        const char* cursor = p;
        const char* const stop = line_end;
        p = (line_end < end) ? line_end + 1 : end;

        rv_obj_detail::skip_blanks(cursor, stop);
        if (cursor >= stop || *cursor == '#') continue;

        const char* keyword = cursor;
        while (cursor < stop && !rv_obj_detail::is_blank(*cursor)) ++cursor;
        const std::size_t keyword_size = static_cast<std::size_t>(cursor - keyword);

        if (keyword_size == 1 && keyword[0] == 'v') {
            rv_vec3 position{};
            if (!rv_obj_detail::parse_float(cursor, stop, position.x)) return false;
            if (!rv_obj_detail::parse_float(cursor, stop, position.y)) return false;
            if (!rv_obj_detail::parse_float(cursor, stop, position.z)) return false;
            out.positions.push_back(position);  // a trailing w is ignored
        } else if (keyword_size == 2 && keyword[0] == 'v' && keyword[1] == 't') {
            rv_vec2 uv{};
            if (!rv_obj_detail::parse_float(cursor, stop, uv.x)) return false;
            if (!rv_obj_detail::parse_float(cursor, stop, uv.y)) return false;
            out.uvs.push_back(uv);  // a trailing w is ignored
        } else if (keyword_size == 2 && keyword[0] == 'v' && keyword[1] == 'n') {
            rv_vec3 normal{};
            if (!rv_obj_detail::parse_float(cursor, stop, normal.x)) return false;
            if (!rv_obj_detail::parse_float(cursor, stop, normal.y)) return false;
            if (!rv_obj_detail::parse_float(cursor, stop, normal.z)) return false;
            out.normals.push_back(normal);
        } else if (keyword_size == 1 && keyword[0] == 'f') {
            corners.clear();
            for (;;) {
                rv_obj_detail::skip_blanks(cursor, stop);
                if (cursor >= stop) break;
                rv_obj_index corner{};
                if (!rv_obj_detail::parse_corner(cursor, stop, out, corner)) return false;
                corners.push_back(corner);
            }
            if (corners.size() < 3) return false;

            // THEOREM: fan triangulation. An n-gon becomes n-2 triangles all
            // sharing corner 0: (0,1,2), (0,2,3), ... The winding of every
            // triangle matches the polygon's, so back-face culling downstream is
            // unaffected. It is only correct for a CONVEX face — a concave one
            // grows triangles outside itself. Exporters emit convex faces (and
            // mostly quads), and the alternative, ear clipping, buys robustness
            // no disc asset needs.
            for (std::size_t i = 1; i + 1 < corners.size(); ++i) {
                rv_obj_triangle triangle{};
                triangle.corner[0] = corners[0];
                triangle.corner[1] = corners[i];
                triangle.corner[2] = corners[i + 1];
                out.triangles.push_back(triangle);
            }
        }
        // Any other keyword (o, g, s, usemtl, mtllib, ...) is skipped whole.
    }
    return true;
}

// Accessors that turn a corner into values, answering the "channel absent" case
// with a caller-supplied default instead of an out-of-range read.
inline rv_vec3 rv_obj_position(const rv_obj_mesh& mesh, rv_obj_index corner) {
    if (corner.position < 0 || static_cast<std::size_t>(corner.position) >= mesh.positions.size()) {
        return rv_vec3{0.0f, 0.0f, 0.0f};
    }
    return mesh.positions[static_cast<std::size_t>(corner.position)];
}

inline rv_vec2 rv_obj_uv(const rv_obj_mesh& mesh, rv_obj_index corner, rv_vec2 fallback) {
    if (corner.uv < 0 || static_cast<std::size_t>(corner.uv) >= mesh.uvs.size()) return fallback;
    return mesh.uvs[static_cast<std::size_t>(corner.uv)];
}

inline rv_vec3 rv_obj_normal(const rv_obj_mesh& mesh, rv_obj_index corner, rv_vec3 fallback) {
    if (corner.normal < 0 || static_cast<std::size_t>(corner.normal) >= mesh.normals.size()) {
        return fallback;
    }
    return mesh.normals[static_cast<std::size_t>(corner.normal)];
}

// The geometric normal of a triangle, for files that carry no vn. Left-handed
// cross of two edges, so it points the way a face wound counter-clockwise when
// seen from outside faces.
inline rv_vec3 rv_obj_face_normal(const rv_obj_mesh& mesh, const rv_obj_triangle& triangle) {
    const rv_vec3 a = rv_obj_position(mesh, triangle.corner[0]);
    const rv_vec3 b = rv_obj_position(mesh, triangle.corner[1]);
    const rv_vec3 c = rv_obj_position(mesh, triangle.corner[2]);
    return rv_normalize(rv_cross(b - a, c - a));
}

}  // namespace rv_pdklib
