// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 8 — geometry into rv_primitive: clipping, culling, depth key.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

#include <cmath>
#include <cstdint>

#include "pdk/cv/rv_primitives.hpp"
#include "pdk/cv/rv_vertex.hpp"
#include "pdklib/rv_camera/rv_camera.hpp"
#include "pdklib/rv_math/rv_math.hpp"

namespace rv_pdklib {

// The bridge: 3D geometry in, rv_pdk::rv_primitive out. This is the file that
// makes the rest of pdklib/ worth having, because the console's contract stops at
// int16 screen coordinates and a depth SORT KEY — every step between a
// world-space triangle and those numbers is the disc's own work.
//
// The stages, in order, and why each one exists:
//
//   1. transform  world -> clip, through one model-view-projection matrix.
//   2. reject     drop the whole triangle if any vertex is behind the near plane.
//                 BEFORE the divide — see the THEOREM on rv_xform_near_reject.
//   3. divide     clip -> ndc, x/w and y/w.
//   4. map        ndc -> framebuffer pixels, with the y flip and int16 saturation.
//   5. cull       drop back faces by the SIGN OF THE SCREEN-SPACE AREA.
//   6. key        one ordering-table depth from the polygon's average view z.
//
// Steps 2, 5 and 6 are things the console deliberately does NOT do: it draws what
// it is given, in the order the ordering table says. Doing them here is what the
// PSX asked of its programmers too.

// Which screen winding is discarded. Named after what is REMOVED, and named in
// SCREEN space (y down) rather than in world space, because that is where the
// test actually happens and where the answer is unambiguous.
//
// Rule of thumb for the usual setup — a closed model whose faces are wound
// counter-clockwise when seen from OUTSIDE: a face turned towards the camera
// still LOOKS counter-clockwise on the display (the y flip changes the SIGN of
// the signed area, not the appearance — it is what makes the picture come out
// upright in the first place), so the faces to discard are SCREEN_CW.
enum rv_cull_mode {
    RV_CULL_NONE = 0,
    RV_CULL_SCREEN_CW = 1,   // discard faces wound clockwise on screen
    RV_CULL_SCREEN_CCW = 2,  // discard faces wound counter-clockwise on screen
};

// Everything the per-triangle stage needs, built once per frame per object.
//
// depth_min / depth_max are the ordering-table range THIS DISC chose to spend;
// the console clamps out-of-range values into its nearest bucket and never tells
// the disc how many buckets there are, so the disc picks a range and stays in it.
// Remember the contract's direction: LARGER depth = NEARER = drawn on top.
struct rv_xform_conf {
    rv_mat4 mvp;          // projection * view * model
    float screen_width;   // rv_cv::screen_width(), as a float
    float screen_height;  // rv_cv::screen_height(), as a float
    float near_plane;     // the camera's near plane; w below it is rejected
    float far_plane;      // the camera's far plane; the depth key's far end
    int32_t depth_min;    // ordering-table key at the far plane
    int32_t depth_max;    // ordering-table key at the near plane
    uint32_t cull;        // rv_cull_mode
};

inline rv_xform_conf rv_xform_conf_make(const rv_mat4& mvp, const rv_camera& camera,
                                        float screen_width, float screen_height, int32_t depth_min,
                                        int32_t depth_max, uint32_t cull) {
    rv_xform_conf conf{};
    conf.mvp = mvp;
    conf.screen_width = screen_width;
    conf.screen_height = screen_height;
    conf.near_plane = camera.near_plane;
    conf.far_plane = camera.far_plane;
    conf.depth_min = depth_min;
    conf.depth_max = depth_max;
    conf.cull = cull;
    return conf;
}

// A vertex on its way through the pipeline: the clip-space position plus the
// attributes that ride along untouched.
struct rv_xform_vertex {
    rv_vec3 position;  // world space (model space if the mvp includes the model)
    rv_pdk::rv_color color;
    rv_pdk::rv_uv uv;
};

// --- stage 2: the near plane --------------------------------------------------

// THEOREM: near-plane rejection BEFORE the perspective divide. With this
// projection w equals the view-space z, so a point behind the eye carries a
// NEGATIVE w. Dividing by it flips the signs of x and y: the vertex does not
// vanish, it lands mirrored through the screen centre, and the triangle is drawn
// stretched across the whole frame — the single most recognisable artefact of a
// hand-written software pipeline. A vertex exactly at w = 0 divides by zero and
// is worse. So the test must happen while w still exists, i.e. here.
//
// HONEST LIMITATION: this rejects the WHOLE triangle if ANY vertex is behind the
// near plane. Proper near clipping would intersect the triangle with the plane
// and emit one or two NEW triangles with interpolated colour and uv; that is
// DEFERRED. The visible consequence is that a large polygon disappears entirely
// the moment one corner passes the eye — noticeable on walls and floors, which is
// why discs that use them should tessellate. Nothing here is unsound, it is
// merely conservative: everything kept is guaranteed safe to divide.
inline bool rv_xform_near_reject(const rv_vec4* clip, int count, float near_plane) {
    // A hair of slack: at exactly w == near the divide is defined but the
    // reciprocal is already the largest it will legitimately get.
    const float limit = near_plane * 0.999f;
    for (int i = 0; i < count; ++i) {
        if (!(clip[i].w > limit)) return true;  // NaN-safe: NaN fails the test
    }
    return false;
}

// --- stages 3 and 4: divide and map -------------------------------------------

// Perspective divide. The caller must have passed rv_xform_near_reject first;
// w > 0 is a precondition, not something re-checked per vertex.
inline rv_vec3 rv_xform_divide(rv_vec4 clip) {
    const float inv_w = 1.0f / clip.w;
    return rv_vec3{clip.x * inv_w, clip.y * inv_w, clip.z * inv_w};
}

// NDC -> framebuffer pixels. Two things happen: the [-1, +1] box is stretched
// over the screen, and Y IS FLIPPED — clip space keeps the project's +y up, the
// framebuffer's y grows down. The flip keeps the picture upright; what it does
// change is the SIGN of every signed area computed downstream, which is why the
// culling THEOREM is stated in screen space and not in world space.
inline rv_vec2 rv_xform_to_screen(rv_vec3 ndc, float screen_width, float screen_height) {
    return rv_vec2{(ndc.x * 0.5f + 0.5f) * screen_width, (0.5f - ndc.y * 0.5f) * screen_height};
}

// Round to the nearest pixel and SATURATE into int16. Saturation, not wrap: a
// vertex far off-screen is legal (rv_pdk::rv_vertex is signed precisely so a
// clipped corner can be expressed), but a wrapped coordinate would teleport it to
// the opposite edge and drag the whole polygon with it.
inline int16_t rv_xform_saturate(float value) {
    if (!(value > -32768.0f)) return -32768;  // also catches NaN
    if (value >= 32767.0f) return 32767;
    return static_cast<int16_t>(std::floor(value + 0.5f));
}

inline rv_pdk::rv_vertex rv_xform_vertex_make(rv_vec2 screen, rv_pdk::rv_color color,
                                              rv_pdk::rv_uv uv) {
    rv_pdk::rv_vertex vertex{};
    vertex.x = rv_xform_saturate(screen.x);
    vertex.y = rv_xform_saturate(screen.y);
    vertex.color = color;
    vertex.uv = uv;
    return vertex;
}

// --- stage 5: back-face culling -----------------------------------------------

// THEOREM: back-face culling by the sign of the SCREEN-SPACE signed area. After
// projection, the cross product of two edge vectors of the triangle has only a z
// component, and its sign is the orientation of the vertex loop as drawn:
//
//     area2 = cross(b - a, c - a)      // the 2D cross of pdklib/rv_math/rv_math.hpp
//
// With the framebuffer's y pointing DOWN, area2 > 0 means the loop a -> b -> c
// runs CLOCKWISE on the display. A closed model consistently wound flips that
// sign exactly when the surface turns away from the eye, so ONE cross product
// per triangle removes half the geometry — no normals, no dot with a view vector,
// no per-object bookkeeping. It also correctly handles the perspective case,
// because the sign is evaluated after the divide.
//
// area2 == 0 is a triangle seen edge-on (zero pixels); it is reported as culled
// for either cull mode, so the caller never files a primitive that draws nothing.
inline float rv_xform_signed_area2(rv_vec2 a, rv_vec2 b, rv_vec2 c) {
    return rv_cross(b - a, c - a);
}

inline bool rv_xform_culled(rv_vec2 a, rv_vec2 b, rv_vec2 c, uint32_t cull) {
    if (cull == RV_CULL_NONE) return false;
    const float area2 = rv_xform_signed_area2(a, b, c);
    if (area2 == 0.0f) return true;
    if (cull == RV_CULL_SCREEN_CW) return area2 > 0.0f;
    return area2 < 0.0f;
}

// --- stage 6: the ordering-table key ------------------------------------------

// THEOREM: depth key = the polygon's AVERAGE view-space z (the mean of the clip
// w's, which this projection makes equal to view z), mapped linearly onto the
// disc's chosen [depth_min, depth_max] and inverted, because the console's
// contract is "larger = nearer".
//
// This is the PSX ordering table, faithfully — including its defect. A single key
// per polygon means the whole polygon goes in front of or behind the whole of
// another one. Two polygons that INTERSECT cannot both be right, and two large
// polygons whose averages are close swap order as the camera moves, so the pair
// flickers frame to frame. That is not a bug to fix here; it is the look. A disc
// that needs the pair to be correct must split the geometry (the era's answer) or
// ask the console for the per-pixel Z test on top of the table
// (RV_PIPELINE_BUFFER_CONFIG_TYPE_Z), which orders pixels but never reorders the
// table itself.
//
// The mean is used rather than the nearest or farthest vertex because it is the
// only choice that is stable under the vertex ORDER of the polygon; min/max jump
// when a long polygon rotates.
inline int32_t rv_xform_depth_key(const rv_vec4* clip, int count, const rv_xform_conf& conf) {
    float sum = 0.0f;
    for (int i = 0; i < count; ++i) sum += clip[i].w;
    const float mean_z = sum / static_cast<float>(count);

    const float range = conf.far_plane - conf.near_plane;
    float t = (range > 0.0f) ? (mean_z - conf.near_plane) / range : 0.0f;
    if (!(t > 0.0f)) t = 0.0f;  // NaN-safe
    if (t > 1.0f) t = 1.0f;

    const float near_key = static_cast<float>(conf.depth_max);
    const float far_key = static_cast<float>(conf.depth_min);
    return static_cast<int32_t>(std::floor(near_key + (far_key - near_key) * t + 0.5f));
}

// --- the whole chain ----------------------------------------------------------

// Run stages 1-6 over 3 or 4 vertices and, if anything survives, fill `out` as a
// polygon primitive: geometry, vertex colours, uv and the depth key.
//
// The caller still owns every DRAWING attribute (fill_mode, addr_texture,
// addr_palette, mapping) — pdklib/ transforms geometry, it does not decide how a
// surface looks. Fill those on `out.data.polygon` after a true return.
//
// A quad's four vertices must already be in the PDK's Z ORDER: the console splits
// it into triangles (1,2,3) and (2,3,4), not around the rim. Culling and the
// depth key use that same order, so a quad handed in rim order is both wound
// wrongly and split wrongly — the mistake shows up as an hourglass.
//
// Returns false when the polygon was rejected (behind the near plane, culled, or
// a bad vertex count); `out` is then untouched and nothing should be filed.
inline bool rv_xform_polygon(const rv_xform_conf& conf, const rv_xform_vertex* vertexes, int count,
                             rv_pdk::rv_primitive& out) {
    if (count != 3 && count != 4) return false;

    rv_vec4 clip[4];
    rv_vec2 screen[4];
    for (int i = 0; i < count; ++i) clip[i] = rv_world_to_clip(conf.mvp, vertexes[i].position);

    if (rv_xform_near_reject(clip, count, conf.near_plane)) return false;

    for (int i = 0; i < count; ++i) {
        screen[i] =
            rv_xform_to_screen(rv_xform_divide(clip[i]), conf.screen_width, conf.screen_height);
    }

    if (rv_xform_culled(screen[0], screen[1], screen[2], conf.cull)) return false;

    out = rv_pdk::rv_primitive{};
    out.type = rv_pdk::RV_PRIMITIVE_POLYGON;
    out.depth = rv_xform_depth_key(clip, count, conf);

    rv_pdk::rv_polygon& polygon = out.data.polygon;
    polygon.fill_mode = rv_pdk::RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;  // caller may override
    polygon.addr_texture = 0;
    polygon.addr_palette = 0;
    polygon.mapping = rv_pdk::RV_TEXWRAP_CLAMP;
    polygon.vertex_count = static_cast<uint32_t>(count);
    for (int i = 0; i < count; ++i) {
        polygon.vertexes[i] = rv_xform_vertex_make(screen[i], vertexes[i].color, vertexes[i].uv);
    }
    // vertexes[3] is ignored at vertex_count == 3, but no byte of a submitted
    // primitive may be indeterminate (it is a union member).
    for (int i = count; i < 4; ++i) polygon.vertexes[i] = rv_pdk::rv_vertex{};
    return true;
}

inline bool rv_xform_triangle(const rv_xform_conf& conf, const rv_xform_vertex* vertexes,
                              rv_pdk::rv_primitive& out) {
    return rv_xform_polygon(conf, vertexes, 3, out);
}

inline bool rv_xform_quad(const rv_xform_conf& conf, const rv_xform_vertex* vertexes,
                          rv_pdk::rv_primitive& out) {
    return rv_xform_polygon(conf, vertexes, 4, out);
}

// One world point to one screen point, for the cases that are not polygons at all
// — a billboard's corner, a HUD marker pinned to an object, a debug cross.
// Returns false if the point is behind the near plane.
inline bool rv_xform_point(const rv_xform_conf& conf, rv_vec3 world, rv_vec2& out_screen,
                           int32_t& out_depth) {
    const rv_vec4 clip = rv_world_to_clip(conf.mvp, world);
    if (rv_xform_near_reject(&clip, 1, conf.near_plane)) return false;
    out_screen = rv_xform_to_screen(rv_xform_divide(clip), conf.screen_width, conf.screen_height);
    out_depth = rv_xform_depth_key(&clip, 1, conf);
    return true;
}

}  // namespace rv_pdklib
