// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — mppcburner command line: the build and inspect subcommands.
// ──────────────────────────────────────────────────────────────────────────────
//
// mppcburner — the developer's side of the disc medium. A prepared directory
// goes in (sources, a disc.toml, artwork) and one .mppcdisc comes out, which is
// the only thing the console ever knows how to load.
//
// Two subcommands, because they are two different jobs with two different
// contracts: `build` writes a file and talks to a human, `inspect` writes
// nothing and talks to a script.
//
// STDOUT IS DATA, STDERR IS TALK. `inspect` puts the manifest and the entry
// listing on stdout and nothing else, so `mppcburner inspect x.mppcdisc | grep
// tex` is a sentence with one meaning. `build` puts its whole [n/4] ladder on
// stderr, including the successful lines: its product is a FILE, not a stream,
// and a build that printed progress into a pipe would corrupt whatever the pipe
// was for. Every refusal, anywhere, exits non-zero.

// ─── ПЛАН: ТАБЛИЧНЫЙ РАЗБОР АРГУМЕНТОВ ────────────────────────────────────────
// ВНИМАНИЕ: код ниже это ЕЩЁ НЕ делает. Это целевая форма, к которой идём.
//
// Требование: main не ветвится по именам команд, help проверяется ровно один
// раз, цикл getopt один на все подкоманды. Всё, что различается между
// подкомандами, живёт в данных, а не в коде.
//
// ── 1. Данные: два массива, единственный источник правды ─────────────────────
//
//   OPTIONS[]   буква  длинное      арность    справка   маска команд
//               'h'    help         no         "..."     BUILD|INSPECT
//               'o'    output       required   "..."     BUILD
//               'p'    pdk          required   "..."     BUILD
//               'l'    pdklib       required   "..."     BUILD
//               'b'    baker        required   "..."     BUILD
//               'j'    jobs         required   "..."     BUILD
//               'k'    keep-build   optional   "..."     BUILD
//
//   COMMANDS[]  имя        маска      операндов  обработчик
//               "build"    BUILD      1          rv_build_run
//               "inspect"  INSPECT    1          rv_inspect_run
//               "help"     —          0          показать справку
//               "-h"       —          0          показать справку
//               "--help"   —          0          показать справку
//
// Буквы опций глобально уникальны — это условие, при котором дальше хватает
// одного switch на весь инструмент.
//
// ── 2. main: диспетчер, без ветвлений по именам ──────────────────────────────
//
//   main(argc, argv)
//    ├─ [1] argc < 2 ................. usage(stderr) → 1
//    ├─ [2] cmd = поиск argv[1] в COMMANDS   ← проход по таблице, не if-цепочка
//    ├─ [3] cmd == nullptr ........... error + usage(stderr) → 1
//    └─ [4] return parse_and_run(cmd, argc - 1, argv + 1)
//
// Сдвиг argv + 1, а не + 2: getopt никогда не разбирает нулевой элемент, считая
// его именем программы. Жертвой становится слово подкоманды, которое уже
// отработало. При + 2 съеденной оказалась бы директория диска.
//
// ── 3. parse_and_run: один цикл на все команды ───────────────────────────────
//
//   parse_and_run(cmd, argc, argv)
//    ├─ [1] из OPTIONS по cmd.mask собрать:
//    │        struct option table[]   ← только строки, где маска совпала
//    │        char optstring[]        ← буквы + ':' по арности
//    │
//    ├─ [2] цикл
//    │      ╭────────────────────────────────────────────────╮
//    │      │ c = getopt_long(argc, argv, optstring, table)  │
//    │      │                                                │
//    │      │  -1     ─────► break                           │
//    │      │  '?'    ─────► usage(stderr) → 1               │
//    │      │  'h'    ─────► usage(stdout) → 0   ← help ЗДЕСЬ │
//    │      │  буква  ─────► store(c, optarg, options)       │
//    │      ╰────────────────────────────────────────────────╯
//    │
//    ├─ [3] n = argc - optind
//    │        n != cmd.operands ....... error + usage(stderr) → 1
//    │        иначе .................. operand = argv[optind]
//    │
//    └─ [4] return cmd.handler(options, operand)
//
// -1 — не ошибка, а штатный сигнал «опции кончились». '?' — ошибка, и getopt
// уже напечатал про неё в stderr сам (opterr == 1), своё сообщение писать не
// надо. Операнды getopt переставляет в хвост argv, поэтому их диапазон —
// argv[optind] .. argv[argc-1], и читать argv[optind] можно только после
// проверки количества: при n == 0 там лежит терминирующий nullptr.
//
// ── 4. store: один switch вместо двух ────────────────────────────────────────
//
//   store(c, optarg, options)
//      'o' → output      = optarg
//      'p' → pdk_dir     = optarg
//      'l' → pdklib_dir  = optarg
//      'b' → baker       = optarg
//      'j' → jobs        = strtol(optarg), с проверкой конца строки
//      'k' → keep_build  = true; build_dir = optarg, если он есть
//
// Арность обязана быть required у p/l/b/j: у optional_argument значение
// принимается ТОЛЬКО слитно (--pdk=/path), а форма --pdk /path из usage() ушла
// бы во вторые операнды. Тогда же optarg в этих ветках гарантированно не
// nullptr. atoi не годится: он возвращает 0 и на "abc", и на "0".
//
// ── 5. Что исчезает при переходе ─────────────────────────────────────────────
//
//   run_build / run_inspect как парсеры → только rv_build_run / rv_inspect_run
//   два цикла getopt                    → один
//   два switch                          → один store
//   две проверки help                   → одна
//   цепочка if в main                   → строки COMMANDS
//   usage() руками                      → генерируется из OPTIONS + COMMANDS
//   take_value, digit_optind, positionals, option_index → удаляются
// ──────────────────────────────────────────────────────────────────────────────

#include <cstdio>
#include <cstdlib>
#include <string>
#include <string_view>
#include <vector>

#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>

#include "rv_build.hpp"

// Where a generated disc project looks for the contract and the disc-side SDK.
// Normally baked in by pdk/tools/mppcburner/CMakeLists.txt; the fallbacks keep this
// file compilable on its own, and are wrong often enough that --pdk / --pdklib
// exist.
#ifndef RV_BURNER_DEFAULT_PDK
#define RV_BURNER_DEFAULT_PDK "pdk/include"
#endif
#ifndef RV_BURNER_DEFAULT_PDKLIB
#define RV_BURNER_DEFAULT_PDKLIB "pdklib/include"
#endif

namespace rv_pdktools
{
namespace
{

void usage(std::FILE *stream)
{
	std::fprintf(stream,
		"usage: mppcburner build <disc-directory> -o <output.mppcdisc>\n"
		"                        [--pdk PATH] [--pdklib PATH] [--baker PATH]\n"
		"                        [--jobs N] [--keep-build[=PATH]]\n"
		"       mppcburner inspect <file.mppcdisc>\n"
		"\n"
		"build   compile a disc directory and burn it into one .mppcdisc.\n"
		"        Progress and diagnostics go to stderr; nothing to stdout.\n"
		"\n"
		"  -o, --output PATH   the .mppcdisc to write (required)\n"
		"  --pdk PATH          include directory of the PDK the disc compiles\n"
		"                      against (default: " RV_BURNER_DEFAULT_PDK
		")\n"
		"  --pdklib PATH          include directory of the disc-side SDK\n"
		"                      (default: " RV_BURNER_DEFAULT_PDKLIB
		")\n"
		"  --baker PATH        mppcbaker to bake textures with (default: next to\n"
		"                      mppcburner, then $PATH)\n"
		"  --jobs N            parallel compile jobs (default: cmake decides)\n"
		"  --keep-build[=PATH] keep the generated CMake project instead of\n"
		"                      deleting it, optionally somewhere of your choosing\n"
		"\n"
		"inspect print the manifest, the entries and their sizes to stdout.\n"
		"        Nothing is unpacked and nothing is written to disk.\n");
}

void say_error(const std::string &message)
{
	std::fprintf(stderr, "mppcburner: error: %s\n", message.c_str());
}

int run_build(int argc, char **argv)
{
	rv_burn_options options;
	options.pdk_dir = RV_BURNER_DEFAULT_PDK;
	options.pdklib_dir = RV_BURNER_DEFAULT_PDKLIB;

	int c;
	for (;;) {
		static struct option long_burn_opts[] = {
			{ "help", no_argument, 0, 'h' },
			{ "output", required_argument, 0, 'o' },
			{ "pdk", optional_argument, 0, 'p' },
			{ "pdklib", optional_argument, 0, 'l' },
			{ "baker", optional_argument, 0, 'b' },
			{ "jobs", optional_argument, 0, 'j' },
			{ "keep-build", optional_argument, 0, 'k' },
			{ 0, 0, 0, 0 }
		};

		c = getopt_long(argc, argv, "ho:p::l::b::j::k::", long_burn_opts, nullptr);

		if (c < 0) {
			break;
		}

		switch (c) {
		case 'h': {
			rv_pdktools::usage(stdout);
			return 0;
		}
		case 'o': {
			options.output = optarg;
			break;
		}
		case 'p': {
			if (nullptr != optarg) {
				options.pdk_dir = optarg;
			}
			break;
		}
		case 'l': {
			if (nullptr != optarg) {
				options.pdklib_dir = optarg;
			}
			break;
		}
		case 'b': {
			if (nullptr != optarg) {
				options.baker = optarg;
			}
			break;
		}
		case 'j': {
			if (nullptr != optarg) {
				options.jobs = std::atoi(optarg);
			}

			if (options.jobs <= 0) {
				say_error("--jobs wants a positive number, got '" + std::string(optarg) + "'");
				return 1;
			}
			break;
		}
		case 'k': {
			options.keep_build = true;

			if (nullptr != optarg) {
				options.build_dir = optarg;
			}
			break;
		}
		case '?':
		default: {
			say_error("unknown option '" + std::string(argv[optind]) + "'");
			usage(stderr);
			return 1;
		}
		}
	}

	if (options.output.empty()) {
		say_error("build needs an output file (-o <output.mppcdisc>)");
		usage(stderr);
		return 1;
	}
	options.disc_dir = "";
	return rv_build_run(options);
}; // run_build

int run_inspect(int argc, char **argv)
{
	static struct option long_insp_opts[] = {
		{ "help", no_argument, 0, 'h' },
		{ 0, 0, 0, 0 }
	};

	int c;
	for (;;) {
		c = getopt_long(argc, argv, "h", long_insp_opts, nullptr);

		if (c < 0) {
			break;
		}

		switch (c) {
		case 'h': {
			usage(stdout);
			return 0;
		}
		case '?':
		default: {
			say_error("unknown option '" + std::string(argv[optind]) + "'");
			usage(stderr);
			return 1;
		}
		}
	}

	return rv_inspect_run(rv_insp_options{ .archive_path = positionals.front() });
} // run_inspect

} // namespace
} // namespace rv_pdktools

int main(int argc, char **argv)
{
	if (argc < 2) {
		rv_pdktools::usage(stderr);
		return 1;
	}
	const std::string_view command = argv[1];
	if (command == "-h" || command == "--help" || command == "help") {
		rv_pdktools::usage(stdout);
		return 0;
	}

	if (command == "build") {
		return rv_pdktools::run_build(argc - 1, argv + 1);
	}
	if (command == "inspect") {
		return rv_pdktools::run_inspect(argc - 1, argv + 1);
	}
	rv_pdktools::say_error("unknown subcommand '" + std::string(command) + "'");
	rv_pdktools::usage(stderr);
	return 1;
}
