// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — mppcburner command line: the build and inspect subcommands.
// ──────────────────────────────────────────────────────────────────────────────
//
// mppcburner — the developer's side of the disc medium. A prepared directory
// goes in (sources, a disc.toml, artwork) and one .mppcdisc comes out, which is
// the only thing the console ever knows how to load.
//
// Two subcommands, because they are two different jobs with two different
// contracts: `build` writes a file and talks to a human, `inspect` writes
// nothing and talks to a script.
//
// STDOUT IS DATA, STDERR IS TALK. `inspect` puts the manifest and the entry
// listing on stdout and nothing else, so `mppcburner inspect x.mppcdisc | grep
// tex` is a sentence with one meaning. `build` puts its whole [n/4] ladder on
// stderr, including the successful lines: its product is a FILE, not a stream,
// and a build that printed progress into a pipe would corrupt whatever the pipe
// was for. Every refusal, anywhere, exits non-zero.

#include <cstdio>
#include <cstdlib>
#include <string>
#include <string_view>
#include <vector>

#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>

#include "rv_build.hpp"

// Where a generated disc project looks for the contract and the disc-side SDK.
// Normally baked in by pdk/tools/mppcburner/CMakeLists.txt; the fallbacks keep this
// file compilable on its own, and are wrong often enough that --pdk / --pdklib
// exist.
#ifndef RV_BURNER_DEFAULT_PDK
#define RV_BURNER_DEFAULT_PDK "pdk/include"
#endif
#ifndef RV_BURNER_DEFAULT_PDKLIB
#define RV_BURNER_DEFAULT_PDKLIB "pdklib/include"
#endif

namespace rv_pdktools
{
namespace
{

void usage(std::FILE *stream)
{
	std::fprintf(stream,
		"usage: mppcburner build <disc-directory> -o <output.mppcdisc>\n"
		"                        [--pdk PATH] [--pdklib PATH] [--baker PATH]\n"
		"                        [--jobs N] [--keep-build[=PATH]]\n"
		"       mppcburner inspect <file.mppcdisc>\n"
		"\n"
		"build   compile a disc directory and burn it into one .mppcdisc.\n"
		"        Progress and diagnostics go to stderr; nothing to stdout.\n"
		"\n"
		"  -o, --output PATH   the .mppcdisc to write (required)\n"
		"  --pdk PATH          include directory of the PDK the disc compiles\n"
		"                      against (default: " RV_BURNER_DEFAULT_PDK
		")\n"
		"  --pdklib PATH          include directory of the disc-side SDK\n"
		"                      (default: " RV_BURNER_DEFAULT_PDKLIB
		")\n"
		"  --baker PATH        mppcbaker to bake textures with (default: next to\n"
		"                      mppcburner, then $PATH)\n"
		"  --jobs N            parallel compile jobs (default: cmake decides)\n"
		"  --keep-build[=PATH] keep the generated CMake project instead of\n"
		"                      deleting it, optionally somewhere of your choosing\n"
		"\n"
		"inspect print the manifest, the entries and their sizes to stdout.\n"
		"        Nothing is unpacked and nothing is written to disk.\n");
}

void say_error(const std::string &message)
{
	std::fprintf(stderr, "mppcburner: error: %s\n", message.c_str());
}

// Take the value of an option that needs one, or refuse. `index` points at the
// option itself and is advanced onto the value.
bool take_value(int argc, char **argv, int &index, const char *option, std::string &out)
{
	if (index + 1 >= argc) {
		say_error(std::string(option) + " needs a value");
		return false;
	}
	++index;
	out = argv[index];
	return true;
}

int run_build(int argc, char **argv)
{
	rv_burn_options options;
	options.pdk_dir = RV_BURNER_DEFAULT_PDK;
	options.pdklib_dir = RV_BURNER_DEFAULT_PDKLIB;

	int c;
	int digit_optind = 0;
	std::vector<std::string> positionals;

	for (;;) {
		int this_option_optind = optind ? optind : 1;
		int option_index = 0;

		static struct option long_burn_opts[] = {
			{ "help", no_argument, 0, 'h' },
			{ "output", required_argument, 0, 'o' },
			{ "pdk", optional_argument, 0, 'p' },
			{ "pdklib", optional_argument, 0, 'l' },
			{ "baker", optional_argument, 0, 'b' },
			{ "jobs", optional_argument, 0, 'j' },
			{ "keep-build", optional_argument, 0, 'k' },
			{ 0, 0, 0, 0 }
		};

		// [getopt] НЕДОВЕРИЕ №1: ручное чтение argv. option_index — это номер
		// строки в массиве long_burn_opts, а НЕ индекс в argv, так что
		// argv[option_index] читает не то слово. Но главное — сама переменная
		// `argument` не нужна: всё, что getopt разобрал, он отдаёт через
		// возврат (c) и через optarg. Руками в argv во время цикла не лезут.
		const std::string_view argument = argv[option_index];
		c = getopt_long(argc, argv, "ho:p::l::b::j::k::", long_burn_opts, &option_index);

		// [getopt] НЕДОВЕРИЕ №2: -1 — это не ошибка. Это штатный сигнал
		// «опции кончились, дальше только позиционные». Правильная реакция —
		// выйти из цикла (break) и продолжить функцию. Ошибку getopt сообщает
		// иначе: возвращает '?' (и сам печатает ругань в stderr) — вот для
		// '?' и нужна отдельная ветка с return 1.
		if (c < 0) {
			say_error("unknown option '" + std::string(argument) + "'");
			usage(stderr);
			return 1;
		}

		switch (c) {
		// [getopt] Сюда мы попали ПОТОМУ, что getopt увидел -h или --help —
		// это уже установленный факт. Ветка должна делать то, что значит
		// help: usage(stdout) и return 0. «unknown option» здесь — копипаста.
		case 'h': {
			say_error("unknown option '" + std::string(argument) + "'");
			usage(stderr);
			return 1;
		}
		// [getopt] НЕДОВЕРИЕ №3: take_value заново ищет значение в argv.
		// getopt его уже нашёл: раз опция объявлена как required_argument
		// (и как "o:" в короткой строке), значение лежит в optarg. Вся ветка —
		// одно присваивание options.output = optarg. Если значения не было,
		// сюда бы вообще не попали: getopt вернул бы '?'. take_value после
		// этого не нужен никому — удалить целиком.
		// [getopt] И про C++: фигурные скобки дали переменным область
		// видимости, но провал (fallthrough) они НЕ останавливают. Выполнив
		// case 'o', управление проваливается в 'p', 'l', 'b'... до конца
		// switch. Каждый case обязан заканчиваться break.
		case 'o': {
			if (!take_value(argc, argv, option_index, "-o", options.output)) {
				return 1;
			}
		}
		case 'p': {
			if (!take_value(argc, argv, option_index, "--pdk", options.pdk_dir)) {
				return 1;
			}
		}
		case 'l': {
			if (!take_value(argc, argv, option_index, "--pdklib", options.pdklib_dir)) {
				return 1;
			}
		}
		case 'b': {
			if (!take_value(argc, argv, option_index, "--baker", options.baker)) {
				return 1;
			}
		}
		case 'j': {
			std::string value;
			if (!take_value(argc, argv, option_index, "--jobs", value)) {
				return 1;
			}
			options.jobs = std::atoi(value.c_str());
			if (options.jobs <= 0) {
				say_error("--jobs wants a positive number, got '" + value + "'");
				return 1;
			}
		}
		// [getopt] НЕДОВЕРИЕ №4: ручной разбор «--keep-build=...» через
		// substr. Случай optional_argument getopt тоже берёт на себя:
		// если пользователь написал --keep-build=path, в optarg лежит "path";
		// если написал просто --keep-build, optarg == nullptr. Проверка
		// «optarg есть или нет» заменяет всю возню со срезанием префикса.
		case 'k': {
			options.keep_build = true;
			options.build_dir =
				std::string(argument.substr(std::string_view("--keep-build=").size()));
			if (options.build_dir.empty()) {
				say_error("--keep-build= needs a directory after the '='");
				return 1;
			}
		}
		// [getopt] НЕДОВЕРИЕ №5: позиционные аргументы не приходят в switch
		// вообще — getopt их переставляет в конец argv и до них цикл не
		// доходит. Собирать их надо ПОСЛЕ цикла: всё от argv[optind] до
		// argv[argc-1] и есть positionals. В default сюда попадёт разве что
		// '?' (см. НЕДОВЕРИЕ №2).
		default:
			positionals.push_back(std::string(argument));
		}
	}

	if (positionals.size() != 1) {
		say_error(positionals.empty() ? "build needs a disc directory" : "build takes exactly one disc directory");
		usage(stderr);
		return 1;
	}
	if (options.output.empty()) {
		say_error("build needs an output file (-o <output.mppcdisc>)");
		usage(stderr);
		return 1;
	}
	options.disc_dir = positionals.front();
	return rv_build_run(options);
}

int run_inspect(int argc, char **argv)
{
	int c;
	int digit_optind = 0;
	std::vector<std::string> positionals;

	static struct option long_insp_opts[] = {
		{ "help", no_argument, 0, 'h' },
		{ 0, 0, 0, 0 }
	};

	for (;;) {
		int this_option_optind = optind ? optind : 1;
		int option_index = 0;

		// [getopt] Те же недоверия №1, №2, №5, что и в run_build: ручное
		// чтение argv, -1 как «ошибка» вместо выхода из цикла, positionals
		// внутри switch вместо argv[optind..argc) после него.
		const std::string_view argument = argv[option_index];
		c = getopt_long(argc, argv, "h", long_insp_opts, &option_index);

		if (c < 0) {
			say_error("unknown option '" + std::string(argument) + "'");
			usage(stderr);
			return 1;
		}

		switch (c) {
		// [getopt] НЕДОВЕРИЕ №6: перепроверка за getopt. c == 'h' УЖЕ значит,
		// что пользователь написал -h или --help — иначе сюда не попасть.
		// Внутренний if всегда истинен (а если бы argument читался неверно —
		// молча падал бы в default). Телу case хватает двух строк:
		// usage(stdout); return 0.
		case 'h':
			if (argument == "-h" || argument == "--help") {
				usage(stdout);
				return 0;
			}
		default:
			if (!argument.empty() && argument.front() == '-') {
				say_error("unknown option '" + std::string(argument) + "'");
				usage(stderr);
				return 1;
			} else {
				positionals.push_back(std::string(argument));
			}
		}
	}

	if (positionals.size() != 1) {
		say_error(positionals.empty() ? "inspect needs a .mppcdisc file" : "inspect takes exactly one .mppcdisc file");
		usage(stderr);
		return 1;
	}

	return rv_inspect_run(rv_insp_options{ .archive_path = positionals.front() });
}

} // namespace
} // namespace rv_pdktools

int main(int argc, char **argv)
{
	if (argc < 2) {
		rv_pdktools::usage(stderr);
		return 1;
	}
	const std::string_view command = argv[1];
	if (command == "-h" || command == "--help" || command == "help") {
		rv_pdktools::usage(stdout);
		return 0;
	}
	// [getopt] Сдвиг argv: getopt всегда пропускает argv[0], считая его
	// именем программы. При «argv + 2» нулевым элементом станет ПЕРВЫЙ
	// НАСТОЯЩИЙ аргумент (например, сама директория диска) — и getopt его
	// молча съест. Сдвигать надо на 1, чтобы argv[0] == "build" играл роль
	// имени программы: run_build(argc - 1, argv + 1).
	if (command == "build") {
		return rv_pdktools::run_build(argc - 2, argv + 2);
	}
	if (command == "inspect") {
		return rv_pdktools::run_inspect(argc - 2, argv + 2);
	}
	rv_pdktools::say_error("unknown subcommand '" + std::string(command) + "'");
	rv_pdktools::usage(stderr);
	return 1;
}
