#include "rv_burner_cmake.hpp"

#include <filesystem>
#include <fstream>
#include <ios>
#include <string>
#include <vector>

#include "rv_burner_common/rv_burner_process.hpp"
#include "pdklib/rv_manifest/rv_manifest.hpp"

namespace fs = std::filesystem;

namespace rv_pdktools
{

// The extra translation unit added to every generated project. It carries only
// RV_MPPC_DISC_VERSION_DEF, which stamps the ABI version the disc was built
// against into the module. The long name is deliberate: it shares a directory
// with the author's own sources and must not collide with any of them.
static constexpr const char *k_version_unit_name =
    "custom_version_plus_hash_for_evade_collisions.cpp";

// --- quoting ---

// CMake string quoting, which is NOT shell quoting: cmake reads double-quoted
// arguments and expands `${...}` inside them, so a backslash, a quote and a
// dollar each need an escape. shell_quote() solves a different problem for a
// different reader, which is why both exist and neither can stand in for the
// other. Static because only this file writes cmake syntax.
static std::string cmake_quote(const std::string &text)
{
    std::string out = "\"";
    for (const char c : text) {
        if (c == '\\' || c == '"' || c == '$') {
            out += '\\';
        }
        out += c;
    }
    out += "\"";
    return out;
}

} // namespace rv_pdktools

// The project is assembled as text rather than through a cmake-file-writing
// library because there is no such library worth a dependency, and because the
// output is meant to be READ: `--keep-build` leaves it for a developer to run
// `ninja -v` in. Raw string literals keep each block looking like the cmake it
// produces; the loops between them are where the manifest's own lists arrive.
std::string rv_pdktools::cmake_project_text(
    const rv_pdklib::rv_manifest &manifest,
    const std::string &pdk_dir,
    const std::string &pdklib_dir,
    const std::vector<std::string> &absolute_includes,
    const std::vector<std::string> &absolute_sources)
{
    std::string text;

    // --- preamble ---

    text += R"cmake(# Generated by mppcburner. Do not edit: every build overwrites this file.
# It exists so a disc is compiled by cmake+ninja rather than by a compiler
# driver written inside the burner. See rv_burner_cmake.hpp for the reasoning.
cmake_minimum_required(VERSION 3.20)
set(CMAKE_CXX_COMPILER clang++)
project(mppcdisc_)cmake" +
        manifest.disc_id + R"cmake( CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

)cmake";

    // --- the module target ---
    //
    // MODULE, not SHARED. A SHARED library is something other targets link
    // against, so cmake maintains a link interface for it. A MODULE is a plugin,
    // loaded at run time with dlopen and never linked by anybody — which is
    // exactly what a disc is. Saying MODULE makes the relationship unlinkable by
    // construction: nothing can add `disc` to a target_link_libraries and start
    // depending on its symbols.
    text += "add_library(disc MODULE\n";
    for (const std::string &source : absolute_sources) {
        text += "  " + cmake_quote(source) + "\n";
    }
    text += "  " + cmake_quote(k_version_unit_name) + "\n";
    text += ")\n\n";

    // PREFIX "" with OUTPUT_NAME "disc" produce exactly `disc.so`, the name the
    // loader looks for inside the archive. Without PREFIX "" cmake writes
    // `libdisc.so` and the disc is unloadable for a reason that looks like
    // nothing at all.
    text += R"cmake(set_target_properties(disc PROPERTIES
  PREFIX ""
  SUFFIX ".so"
  OUTPUT_NAME "disc"
  POSITION_INDEPENDENT_CODE ON
  CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN ON
)

# The contract, and only the contract. Nothing from src/ is reachable from
# here, which is what turns "a disc cannot see the console" from a promise
# into a compile error.
target_include_directories(disc PRIVATE
)cmake";
    text += "  " + cmake_quote(pdk_dir) + "\n";
    text += "  " + cmake_quote(pdklib_dir) + "\n";
    for (const std::string &include : absolute_includes) {
        text += "  " + cmake_quote(include) + "\n";
    }
    text += ")\n\n";

    // --- definitions ---
    //
    // RV_LOG_ORIGIN is not optional and not the manifest's to set: it stamps
    // every line pdklib/rv_logs/rv_logs.hpp emits as coming from a disc rather than from
    // the console or a tool. A disc that had to declare it could get it wrong.
    text += R"cmake(target_compile_definitions(disc PRIVATE
  "RV_LOG_ORIGIN=\"disc\""
)cmake";
    for (const std::string &define : manifest.build_defines) {
        text += "  " + cmake_quote(define) + "\n";
    }
    text += ")\n\n";

    // --- options ---
    //
    // -fPIC because the result is dlopen'd and must be position independent.
    // -fvisibility=hidden because a disc exports exactly two symbols —
    // mppc_disc_create and mppc_disc_destroy, marked default by RV_DISC_EXPORT —
    // and everything else is its own business. Default visibility would put the
    // whole game's symbol table into the console's process, where it can collide,
    // be interposed, or be found by a dlsym that meant something else.
    text += R"cmake(target_compile_options(disc PRIVATE
  -fPIC
  -fvisibility=hidden
  -Wall
  -Wextra
)
)cmake";

    return text;
}

int rv_pdktools::create_cmakelists(
    const rv_burner_options &options,
    const rv_pdklib::rv_manifest &manifest,
    const fs::path &project_dir,
    const std::vector<std::string> &absolute_includes,
    const std::vector<std::string> &absolute_sources,
    std::string &error)
{
    // --- CMakeLists.txt ---

    const fs::path cmakelists_path = project_dir / "CMakeLists.txt";
    const std::string project_text = cmake_project_text(
        manifest,
        options.pdk_dir,
        options.pdklib_dir,
        absolute_includes,
        absolute_sources);

    {
        std::ofstream out(cmakelists_path, std::ios::binary | std::ios::trunc);
        if (!out) {
            error = "cannot write '" + cmakelists_path.string() + "'";
            return 1;
        }
        out.write(project_text.data(), static_cast<std::streamsize>(project_text.size()));
        if (!out) {
            error = "short write on '" + cmakelists_path.string() + "'";
            return 1;
        }
    }

    // --- the version translation unit ---
    //
    // Written here and not shipped as a file in the repository, because it must
    // land inside the generated project where the disc's own include path
    // applies.
    const fs::path version_unit_path = project_dir / k_version_unit_name;
    const std::string version_unit_text{
        "#include \"pdk/de/rv_dv.hpp\"\n"
        "#include \"pdklib/rv_disc_version/rv_disc_version.hpp\"\n"
        "\n"
        "RV_MPPC_DISC_VERSION_DEF;"
    };

    {
        std::ofstream out(version_unit_path, std::ios::binary | std::ios::trunc);
        if (!out) {
            error = "cannot write '" + version_unit_path.string() + "'";
            return 1;
        }
        out.write(version_unit_text.data(), static_cast<std::streamsize>(version_unit_text.size()));
        if (!out) {
            error = "short write on '" + version_unit_path.string() + "'";
            return 1;
        }
    }

    return 0;
}

int rv_pdktools::configure_cmake(
    const fs::path &binary_dir,
    const fs::path &project_dir,
    std::string &error)
{
    const std::string configure = "cmake -G Ninja -S " + shell_quote(project_dir.string()) +
        " -B " + shell_quote(binary_dir.string()) +
        " -DCMAKE_BUILD_TYPE=RelWithDebInfo";

    std::string child_output;
    const int status = run_capture(configure, child_output);
    if (status != 0) {
        dump_child_output(child_output);
        error = "cmake failed to configure the generated disc project (exit " +
            std::to_string(status) +
            "). cmake and ninja are run-time dependencies of mppcburner.";
        return 1;
    }

    return 0;
}
