#include "rv_burner_cmake.hpp"

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "rv_burner_compile/rv_burner_common_helpers.hpp"
#include "rv_burner_manifest/rv_burner_manifest.hpp"

namespace fs = std::filesystem;

namespace
{

// A quoted CMake argument: backslash, double quote and `$` all have meaning
// inside one, so all three are escaped. Paths come from a manifest and from the
// command line, and neither is under our control.
std::string cmake_quote(const std::string &text)
{
	std::string out = "\"";
	for (const char c : text) {
		if (c == '\\' || c == '"' || c == '$') {
			out += '\\';
		}
		out += c;
	}
	out += "\"";
	return out;
}

} // namespace

std::string rv_pdktools::rv_cmake_project_text(
	const rv_burner_manifest &manifest,
	const std::string &pdk_dir,
	const std::string &pdklib_dir,
	const std::vector<std::string> &absolute_includes,
	const std::vector<std::string> &absolute_sources)
{
	std::string text;
	text += R"cmake(# Generated by mppcburner. Do not edit: every build overwrites this file.
# It exists so a disc is compiled by cmake+ninja rather than by a compiler
# driver written inside the burner. See rv_build.cpp for the reasoning.
cmake_minimum_required(VERSION 3.20)
set(CMAKE_CXX_COMPILER clang++)
project(mppcdisc_)cmake" + manifest.disc_id + R"cmake( CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

)cmake";

	// MODULE, not SHARED. In CMake the two differ in intent and in what the
	// build is allowed to assume: a SHARED library is something other targets
	// link against, so CMake maintains an import/link interface for it. A
	// MODULE is a plugin — loaded at run time with dlopen, NEVER linked by
	// anybody — and that is exactly what a disc is. Saying MODULE makes the
	// relationship unlinkable by construction: nothing in this project or any
	// other can accidentally add `disc` to a target_link_libraries and start
	// depending on its symbols. The console reaches it through dlopen/dlsym and
	// through no other door.
	text += "add_library(disc MODULE\n";
	for (const std::string &source : absolute_sources) {
		text += "  " + cmake_quote(source) + "\n";
	}
	text += "	" + cmake_quote("custom_version_plus_hash_for_evade_collisions.cpp") + "\n";
	text += ")\n\n";

	// PREFIX "" + OUTPUT_NAME "disc" produce exactly `disc.so`, which is the
	// name the loader looks for inside the archive. Without PREFIX "" CMake
	// would write `libdisc.so` and the disc would be unloadable for a reason
	// that looks like nothing at all.
	text += R"cmake(set_target_properties(disc PROPERTIES
  PREFIX ""
  SUFFIX ".so"
  OUTPUT_NAME "disc"
  POSITION_INDEPENDENT_CODE ON
  CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN ON
)

# The contract, and only the contract. Nothing from src/ is reachable from
# here, which is what turns "a disc cannot see the console" from a promise
# into a compile error.
target_include_directories(disc PRIVATE
)cmake";
	text += "  " + cmake_quote(pdk_dir) + "\n";
	text += "  " + cmake_quote(pdklib_dir) + "\n";
	for (const std::string &include : absolute_includes) {
		text += "  " + cmake_quote(include) + "\n";
	}
	text += ")\n\n";

	// RV_LOG_ORIGIN is not optional and not the manifest's to set: it is what
	// stamps every line pdklib/rv_logs.hpp emits as coming from a disc rather
	// than from the console or from a tool. A disc that had to declare it would
	// be a disc that could get it wrong.
	text += R"cmake(target_compile_definitions(disc PRIVATE
  "RV_LOG_ORIGIN=\"disc\""
)cmake";
	for (const std::string &define : manifest.build_defines) {
		text += "  " + cmake_quote(define) + "\n";
	}
	text += ")\n\n";

	// -fPIC because the result is dlopen'd and must be position independent.
	// -fvisibility=hidden because a disc exports exactly TWO symbols —
	// mppc_disc_create and mppc_disc_destroy, marked default by RV_DISC_EXPORT
	// in pdk/rv_abi.hpp — and everything else it contains is its own business.
	// Default visibility would put the whole game's symbol table into the
	// console's process, where it can collide with the console's own names, be
	// interposed, or be found by a dlsym that meant to find something else. The
	// two exported names are a door; hidden visibility is the wall the door is
	// set into.
	text += R"cmake(target_compile_options(disc PRIVATE
  -fPIC
  -fvisibility=hidden
  -Wall
  -Wextra
)
)cmake";
	return text;
}

int rv_pdktools::rv_burner_create_cmakelists(
	const rv_burner_options &options,
	const rv_burner_manifest &manifest,
	const fs::path &project_dir,
	const std::vector<std::string> &absolute_includes,
	const std::vector<std::string> &absolute_sources,
	std::string &error)
{
	const std::string project_text = rv_pdktools::rv_cmake_project_text(
		manifest,
		options.pdk_dir,
		options.pdklib_dir,
		absolute_includes,
		absolute_sources);

	{
		std::ofstream out(project_dir / "CMakeLists.txt", std::ios::binary | std::ios::trunc);
		if (!out) {
			error = "cannot write '" + (project_dir / "CMakeLists.txt").string() + "'";
			return 1;
		}
		out.write(project_text.data(), static_cast<std::streamsize>(project_text.size()));
		if (!out) {
			error = "short write on '" + (project_dir / "CMakeLists.txt").string() + "'";
			return 1;
		}
	}

	const std::string version_cpp_file_text{
		"#include \"pdk/de/rv_dv.hpp\"\n"
		"#include \"pdklib/rv_disc_version.hpp\"\n"
		"\n"
		"RV_MPPC_DISC_VERSION_DEF;"
	};

	{
		std::ofstream out((project_dir / "custom_version_plus_hash_for_evade_collisions.cpp"),
			std::ios::binary | std::ios::trunc);
		if (!out) {
			error = "cannot write `" +
				(project_dir / "custom_version_plus_hash_for_evade_collisions.cpp").string() + "'";
			return 1;
		}

		out.write(version_cpp_file_text.data(),
			static_cast<std::streamsize>(version_cpp_file_text.size()));
		if (!out) {
			error = "short write on '" +
				(project_dir / "custom_version_plus_hash_for_evade_collisions.cpp").string() + "'";
			return 1;
		}
	}

	return 0;
}

int rv_pdktools::rv_burner_prepare_build_configure_cmake(
	const fs::path &binary_dir,
	const fs::path &project_dir,
	std::string &error)
{
	std::string child_output;
	const std::string configure = "cmake -G Ninja -S " + rv_pdktools::shell_quote(project_dir.string()) +
		" -B " + rv_pdktools::shell_quote(binary_dir.string()) +
		" -DCMAKE_BUILD_TYPE=RelWithDebInfo";
	int status = rv_pdktools::run_capture(configure, child_output);
	if (status != 0) {
		rv_pdktools::dump_child_output(child_output);
		error = "cmake failed to configure the generated disc project (exit " +
			std::to_string(status) +
			"). cmake and ninja are run-time dependencies of mppcburner.";
		return 1;
	}
	return 0;
}
