// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — the skeleton disc as the console's service test.
// ──────────────────────────────────────────────────────────────────────────────
//
// The skeleton disc, grown into the console's SERVICE TEST. It is still not a
// game: it is the smallest thing that touches every subsystem the machine
// claims to have, so a broken one shows up on screen or in the speakers rather
// than staying buried in a log.
//
//   rv_cv  — a spinning textured cube, plus three sprites showing the wrap
//            modes and the cut-out transparency rule
//   rv_cd  — reads an asset off the mounted medium and proves it arrived
//   rv_cm  — a boot counter that survives a restart
//   rv_ca  — a synthesized beep on the south button
//   rv_cio — everything above is driven from port 0
//
// BOUNDARY: this translation unit includes pdk/ (the contract) and pdklib/ (the
// disc-side conveniences) and NOTHING else. No console header, no console
// logger, no SDL — the disc plays ON the console, it does not link INTO it
// (pdk/README.md). The build enforces it: the disc target links 3dmppc_pdk and
// 3dmppc_pdklib and never sees the console's include path.
#pragma once

#include <cstdint>
#include <vector>

#include "pdk/de/rv_de.hpp"

// NAMESPACE: `rv_service`, not `rv_3dmppc` — this is a DISC, not part of the
// machine, and a game declared inside the console's namespace reads as part of
// the console.
//
// It carries the project's `rv_` prefix while a packaged disc (see
// mppcdiscs/hello, which is simply `hello`) does not, and the difference is not
// taste. A packaged disc is compiled with -fvisibility=hidden and loaded with
// RTLD_LOCAL, so nothing but its two extern "C" entry points is visible outside
// it: two discs could both pick `namespace hello` and never meet. This one is
// STATICALLY LINKED INTO THE CONSOLE, so it shares that binary's namespace, and
// an unprefixed common word there is a collision waiting for the first C++
// dependency the console acquires.
namespace rv_service {

class rv_dmain : public rv_pdk::rv_de {
   public:
    rv_dmain() = default;
    ~rv_dmain() override = default;

    int64_t disc_initialize(rv_pdk::rv_pdko& pdk) override;
    void frame_update(float dt) override;
    void frame_render() override;
    bool disc_release() const override { return release_; }
    void disc_shutdown() override;
    const char* disc_title() const override;

   private:
    // What the disc persists. Tiny on purpose — the point is that it survives a
    // restart, not what is in it. The magic guards against reading a slot some
    // other game wrote.
    struct rv_dmain_save {
        uint32_t magic;
        uint32_t boot_count;
    };

    void build_texture();
    void build_idx4_texture();
    void build_font();
    void probe_drive();
    void load_save();
    void build_beep();
    void draw_post();
    void draw_test_grid();

    // One cell of the test card. `index` picks the cell; each draws exactly one
    // of the console's drawing capabilities, labelled with what it proves.
    void draw_cell(int index);
    void draw_cube_cell(int x, int y, int w, int h);

    // A textured sprite filling the given rect. `addr_palette` is 0 for the
    // direct format, which carries its colour in the texel.
    void draw_textured(int x, int y, int w, int h, int64_t addr_texture, int64_t addr_palette,
                       rv_pdk::rv_texture_mapping_type mapping);

    // One line of the POST list: a label, what was found, and whether it
    // answered. Drawn by draw_post().
    void draw_post_row(int row, const char* label, const char* detail, const char* status,
                       bool good);

    // Borrowed facade — the console owns it and it stays valid until the disc
    // is torn down. Never deleted here.
    rv_pdk::rv_pdko* pdk_ = nullptr;

    // Everything the POST list reports. Queried once and kept, because that is
    // what the contract says these are — session-stable answers — and because
    // printing them IS the test: a number on screen proves the query answered.
    int64_t screen_width_ = 0;
    int64_t screen_height_ = 0;
    int64_t frame_capacity_ = 0;
    int64_t iport_count_ = 0;
    int64_t video_memory_size_ = 0;
    int64_t voice_count_ = 0;
    int64_t sound_memory_size_ = 0;
    int64_t card_slots_ = 0;
    int64_t card_slot_size_ = 0;

    // --- video ---
    std::vector<uint16_t> texels_;  // the procedural DIRECT15 test texture
    int64_t addr_texture_ = 0;      // 0 reads as "not uploaded" by design

    // A second texture in the INDEXED format, because DIRECT15 alone leaves the
    // palette path — half of the contract's texel formats — untested.
    std::vector<uint8_t> texels_idx4_;
    std::vector<uint16_t> palette_idx4_;
    int64_t addr_idx4_ = 0;
    int64_t addr_idx4_palette_ = 0;

    // The font, so the screen can say what it is. Text is not a console feature
    // and never will be: on the machine this imitates, a font was an asset the
    // game shipped, not something the GPU knew about. So it comes from pdklib/,
    // like any other disc-side convenience.
    int64_t addr_font_ = 0;

    // Two palettes over ONE atlas: the console has no vertex-colour modulation
    // yet, so a second colour of text means a second palette and a different
    // addr_palette — 32 bytes, not another 3 KiB of glyphs. Red is worth it: a
    // status column where failure looks like success is not a status column.
    int64_t addr_font_palette_ = 0;
    int64_t addr_font_palette_bad_ = 0;
    float spin_ = 0.0f;
    float hue_ = 0.0f;

    // --- drive ---
    int64_t asset_bytes_ = 0;           // what we read off the medium, 0 = nothing
    bool asset_ok_ = false;             // the read round-tripped and looked like itself
    bool drive_rejects_paths_ = false;  // the traversal probe answered correctly

    // --- memory card ---
    uint32_t boot_count_ = 0;
    bool card_ok_ = false;

    // --- input ---
    // Ports that report a device. Counted once: the contract calls the port
    // count session-stable, and a pad plugged in later shows up in abilities
    // rather than in a new slot.
    int64_t pads_connected_ = 0;

    // --- audio ---
    int64_t addr_beep_ = 0;
    bool beep_ok_ = false;

    // Previous frame's live button mask, one entry per port. The contract hands
    // out LEVELS only, so a disc that wants edges keeps the previous snapshot
    // itself — see the THEOREM in frame_update.
    std::vector<uint64_t> prev_buttons_;

    bool release_ = false;
};

}  // namespace rv_service
