// ─── NEUROSLOP ────────────────────────────────────────────────────────────────
// Generated by Claude (claude-opus-5). Not reviewed by a human.
// Revision: stage 10 — service test: a card of every drawing capability.
// ──────────────────────────────────────────────────────────────────────────────
#include "rv_dmain.hpp"

#include <cmath>
#include <cstdio>

#include "pdk/ca/rv_ca.hpp"
#include "pdk/cd/rv_cd.hpp"
#include "pdk/cio/rv_cio.hpp"
#include "pdk/cm/rv_cm.hpp"
#include "pdk/cv/rv_cv.hpp"
#include "pdk/rv_err.hpp"
#include "pdklib/rv_camera/rv_camera.hpp"
#include "pdklib/rv_color/rv_color.hpp"
#include "pdklib/rv_math/rv_math.hpp"
#include "pdklib/rv_text/rv_text.hpp"
#include "pdklib/rv_math/rv_xform.hpp"

namespace rv_service {

// The contract's vocabulary, unqualified for the bodies below only — never in a
// header, where a using-directive would leak into everything that includes it.
// The disc-side library (rv_pdklib) is NOT pulled in this way: it is a separate
// tree from the contract and stays visibly spelled out at every call.
using namespace rv_pdk;

namespace {

// --- baked assumptions, validated against the machine in disc_initialize ---

constexpr int64_t RV_DMAIN_MIN_SCREEN = 64;
constexpr int64_t RV_DMAIN_MIN_FRAME_CAPACITY = 16;
constexpr int64_t RV_DMAIN_MIN_PORTS = 1;

// --- the test texture ---

// 16x16 DIRECT15. Small enough to build by hand, big enough that TILE and
// STRETCH look different from CLAMP at a glance.
constexpr int64_t RV_DMAIN_TEX_SIZE = 16;

// Remember the contract's rule: 0000h is a HOLE, not black (opaque black is
// 8000h). The fourth quadrant is deliberately holes so the cut-out path is
// visible, and the border is white so edge behaviour is unmistakable.
constexpr uint16_t RV_DMAIN_TEXEL_RED = 0x001F;
constexpr uint16_t RV_DMAIN_TEXEL_GREEN = 0x03E0;
constexpr uint16_t RV_DMAIN_TEXEL_BLUE = 0x7C00;
constexpr uint16_t RV_DMAIN_TEXEL_WHITE = 0x7FFF;
constexpr uint16_t RV_DMAIN_TEXEL_HOLE = 0x0000;

// --- the beep ---

constexpr int64_t RV_DMAIN_BEEP_RATE = 44100;    // the console's fixed sample rate
constexpr int64_t RV_DMAIN_BEEP_FRAMES = 22050;  // half a second
constexpr float RV_DMAIN_BEEP_HZ = 440.0f;
constexpr int16_t RV_DMAIN_BEEP_PEAK = 20000;

// --- the show ---

constexpr float RV_DMAIN_HUE_RATE = 0.05f;
constexpr float RV_DMAIN_SPIN_RATE = 0.7f;
constexpr uint32_t RV_DMAIN_SAVE_MAGIC = 0x524D4149;  // 'RMAI'

// Ordering-table probes. Larger depth = nearer, so the wrap row sits behind
// the cube and the status bars sit in front of it.
constexpr int32_t RV_DMAIN_DEPTH_ART_LO = -400;
constexpr int32_t RV_DMAIN_DEPTH_ART_HI = 400;
constexpr int32_t RV_DMAIN_DEPTH_PANEL = 880;  // the slab text sits on
constexpr int32_t RV_DMAIN_DEPTH_TEXT = 900;   // over everything, it explains it

// The screen is a POST: it reports WHAT THE MACHINE IS and whether each part
// answered — not a caption for what is drawn below it.
//
// The first version of this screen labelled the picture ("textures", "cube",
// "ticks", "bar", "south") and was useless: those are the names of THIS FILE's
// implementation details, and nobody outside it can know that "south" is what
// the input contract calls the bottom face button. Every number below instead
// comes from a real query — screen_width(), voice_count(), card_slots() — so
// the fact that it is on screen at all is itself the proof that the query
// answers.
constexpr const char* RV_DMAIN_TITLE = "3DMPPC";
constexpr const char* RV_DMAIN_NO_DISC = "NO DISC INSERTED";
// Named by the KEY a person can press. "south" is what the input contract calls
// the bottom face button, and nobody outside that header knows it.
constexpr const char* RV_DMAIN_HINTS = "Z sound   ESC power off";

// Pixels between the tops of consecutive text lines. MORE than the font's own
// cell height: a 7-pixel glyph on an 8-pixel pitch leaves one pixel between
// rows, which is legible in isolation and mush in a list.
constexpr int RV_DMAIN_LEADING = 10;

// Where the POST list sits, and where its three columns start.
constexpr int RV_DMAIN_POST_TOP = 20;
constexpr int RV_DMAIN_POST_ROWS = 6;
constexpr int RV_DMAIN_COL_LABEL = 6;
constexpr int RV_DMAIN_COL_DETAIL = 6 + 8 * 8;

// The cube is rendered into a VIEWPORT rather than the whole screen: the pdklib
// transform maps normalized coordinates onto the width and height it is handed,
// anchored at the upper left. A smaller pair confines the cube to a box, and
// the offset below moves that box under the POST list.
constexpr float RV_DMAIN_CUBE_VIEW_W = 132.0f;
constexpr float RV_DMAIN_CUBE_VIEW_H = 110.0f;
constexpr int16_t RV_DMAIN_CUBE_OFFSET_X = 10;
constexpr int16_t RV_DMAIN_CUBE_OFFSET_Y = 98;

// Human sizes. 1048576 reads as "1 MB", 524288 as "512 KB" — a service screen
// that prints raw byte counts makes the reader do arithmetic to learn something
// the machine already knows.
void format_bytes(char* out, std::size_t cap, int64_t bytes) {
    // The buffer must fit the widest int64 plus a unit; snprintf truncating a
    // diagnostic silently is the last thing a diagnostic screen should do.
    if (bytes >= 1024 * 1024 && bytes % (1024 * 1024) == 0) {
        std::snprintf(out, cap, "%lld MB", static_cast<long long>(bytes / (1024 * 1024)));
    } else if (bytes >= 1024) {
        std::snprintf(out, cap, "%lld KB", static_cast<long long>(bytes / 1024));
    } else {
        std::snprintf(out, cap, "%lld B", static_cast<long long>(bytes));
    }
}

// The unit cube: six quads, each in the PDK's Z ORDER, because the console
// splits a quad into triangles (1,2,3) and (2,3,4) rather than walking the rim.
// Wound counter-clockwise as seen from OUTSIDE, which is what
// RV_CULL_SCREEN_CW keeps.
struct rv_dmain_face {
    rv_pdklib::rv_vec3 corner[4];
    rv_pdklib::rv_vec3 normal;
};

constexpr rv_dmain_face RV_DMAIN_CUBE[6] = {
    {{{-1, -1, -1}, {1, -1, -1}, {-1, 1, -1}, {1, 1, -1}}, {0, 0, -1}},
    {{{1, -1, 1}, {-1, -1, 1}, {1, 1, 1}, {-1, 1, 1}}, {0, 0, 1}},
    {{{1, -1, -1}, {1, -1, 1}, {1, 1, -1}, {1, 1, 1}}, {1, 0, 0}},
    {{{-1, -1, 1}, {-1, -1, -1}, {-1, 1, 1}, {-1, 1, -1}}, {-1, 0, 0}},
    {{{-1, 1, -1}, {1, 1, -1}, {-1, 1, 1}, {1, 1, 1}}, {0, 1, 0}},
    {{{-1, -1, 1}, {1, -1, 1}, {-1, -1, -1}, {1, -1, -1}}, {0, -1, 0}},
};

int16_t to_screen(float value) {
    const float rounded = std::floor(value + 0.5f);
    if (rounded <= -32768.0f) return -32768;
    if (rounded >= 32767.0f) return 32767;
    return static_cast<int16_t>(rounded);
}

// A flat rectangle, filled in completely so no byte of the union is left
// indeterminate. PATTERN: factory method — rv_primitive is a tagged union of
// constructor-less structs, and an "almost filled" literal leaves live fields
// holding whatever the stack had.
rv_primitive make_bar(float x, float y, float w, float h, rv_color color, int32_t depth) {
    rv_primitive primitive{};
    primitive.type = RV_PRIMITIVE_SPRITE;
    primitive.depth = depth;

    rv_sprite& sprite = primitive.data.sprite;
    sprite.fill_mode = RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;
    sprite.addr_texture = 0;
    sprite.addr_palette = 0;
    sprite.color = color;
    sprite.mapping = RV_TEXWRAP_CLAMP;
    sprite.x = to_screen(x);
    sprite.y = to_screen(y);
    sprite.width = static_cast<uint16_t>(w < 0.0f ? 0.0f : w);
    sprite.height = static_cast<uint16_t>(h < 0.0f ? 0.0f : h);
    return primitive;
}

// Screen-space vertex, filled completely — rv_vertex is a plain struct and an
// "almost filled" literal leaves live fields holding whatever the stack had.
rv_vertex make_vertex(int x, int y, rv_color color) {
    rv_vertex vertex{};
    vertex.x = to_screen(static_cast<float>(x));
    vertex.y = to_screen(static_cast<float>(y));
    vertex.color = color;
    vertex.uv = rv_uv{0, 0};  // read only when fill_mode samples a texture
    return vertex;
}

}  // namespace

// --- initialization ----------------------------------------------------------

int64_t rv_dmain::disc_initialize(rv_pdko& pdk) {
    pdk_ = &pdk;

    rv_cv* cv = pdk_->cv();
    rv_cio* cio = pdk_->cio();
    if (!cv || !cio) return RV_ERR_INVAL;

    screen_width_ = cv->screen_width();
    screen_height_ = cv->screen_height();
    frame_capacity_ = cv->frame_capacity();
    iport_count_ = cio->iport_count();
    video_memory_size_ = cv->video_memory_size();

    rv_ca* ca = pdk_->ca();
    if (ca) {
        voice_count_ = ca->voice_count();
        sound_memory_size_ = ca->sound_memory_size();
    }

    rv_cm* cm = pdk_->cm();
    if (cm) {
        card_slots_ = cm->card_slots();
        card_slot_size_ = cm->card_slot_size();
    }

    // A populated slot advertises what it can report; an empty one answers 0.
    for (int64_t port = 0; port < iport_count_; ++port) {
        if (cio->iport_abilities(port) != 0) ++pads_connected_;
    }

    // The point of this hook: the disc bakes assumptions, the machine answers,
    // and a mismatch is refused HERE rather than discovered as garbage on
    // screen half a second in. The console reports the negative code and stops.
    if (screen_width_ < RV_DMAIN_MIN_SCREEN || screen_height_ < RV_DMAIN_MIN_SCREEN) {
        return RV_ERR_INVAL;
    }
    if (frame_capacity_ < RV_DMAIN_MIN_FRAME_CAPACITY) return RV_ERR_INVAL;
    if (iport_count_ < RV_DMAIN_MIN_PORTS) return RV_ERR_INVAL;

    // One previous-mask slot per port, allocated once: frame_update must not
    // allocate, and the port count is session-stable.
    prev_buttons_.assign(static_cast<std::size_t>(iport_count_), 0ULL);

    build_texture();
    build_idx4_texture();
    build_font();
    probe_drive();
    load_save();
    build_beep();

    return RV_OK;
}

void rv_dmain::build_font() {
    rv_cv* cv = pdk_->cv();

    // The atlas is expanded into a buffer the DISC owns and uploaded; the buffer
    // dies at the end of this function because video_asset_write copies during
    // the call. 128x48 IDX4 is 3 KiB — cheap enough to keep resident forever.
    std::vector<uint8_t> atlas(rv_pdklib::rv_text_atlas_size, 0);
    if (!rv_pdklib::rv_text_build_atlas(atlas.data(), atlas.size())) return;

    const int64_t atlas_addr =
        cv->video_asset_malloc(static_cast<int64_t>(rv_pdklib::rv_text_atlas_size));
    if (atlas_addr < 0) return;
    if (cv->video_asset_write(atlas_addr, rv_pdklib::rv_text_atlas_texture(atlas.data())) < 0) {
        cv->video_asset_free(atlas_addr);
        return;
    }

    // One palette is one colour of text. There is no vertex-colour modulation in
    // the contract yet, so recolouring means uploading another palette and
    // pointing addr_palette at it — which is exactly how the machine this
    // imitates recoloured its fonts.
    std::vector<uint16_t> palette(rv_pdklib::rv_text_palette_entries, 0);
    rv_pdklib::rv_text_build_palette(rv_color{220, 226, 240}, palette.data(), palette.size());

    const int64_t palette_addr =
        cv->video_asset_malloc(static_cast<int64_t>(rv_pdklib::rv_text_palette_size));
    if (palette_addr < 0) {
        cv->video_asset_free(atlas_addr);
        return;
    }
    if (cv->video_asset_write(palette_addr, rv_pdklib::rv_text_palette_texture(palette.data())) <
        0) {
        cv->video_asset_free(palette_addr);
        cv->video_asset_free(atlas_addr);
        return;
    }

    // The failure colour, over the same atlas. Two palettes, one set of glyphs.
    std::vector<uint16_t> bad(rv_pdklib::rv_text_palette_entries, 0);
    rv_pdklib::rv_text_build_palette(rv_color{240, 90, 80}, bad.data(), bad.size());

    const int64_t bad_addr =
        cv->video_asset_malloc(static_cast<int64_t>(rv_pdklib::rv_text_palette_size));
    if (bad_addr >= 0 &&
        cv->video_asset_write(bad_addr, rv_pdklib::rv_text_palette_texture(bad.data())) < 0) {
        cv->video_asset_free(bad_addr);
        addr_font_palette_bad_ = 0;
    } else if (bad_addr >= 0) {
        addr_font_palette_bad_ = bad_addr;
    }

    addr_font_ = atlas_addr;
    addr_font_palette_ = palette_addr;
}

void rv_dmain::build_texture() {
    rv_cv* cv = pdk_->cv();

    if (RV_DMAIN_TEX_SIZE > cv->texture_max_width() ||
        RV_DMAIN_TEX_SIZE > cv->texture_max_height()) {
        return;  // the machine is smaller than this disc assumed; skip, do not lie
    }

    texels_.assign(static_cast<std::size_t>(RV_DMAIN_TEX_SIZE * RV_DMAIN_TEX_SIZE),
                   RV_DMAIN_TEXEL_HOLE);

    const int64_t half = RV_DMAIN_TEX_SIZE / 2;
    for (int64_t y = 0; y < RV_DMAIN_TEX_SIZE; ++y) {
        for (int64_t x = 0; x < RV_DMAIN_TEX_SIZE; ++x) {
            uint16_t texel;
            if (x < half && y < half) {
                texel = RV_DMAIN_TEXEL_RED;
            } else if (x >= half && y < half) {
                texel = RV_DMAIN_TEXEL_GREEN;
            } else if (x < half && y >= half) {
                texel = RV_DMAIN_TEXEL_BLUE;
            } else {
                texel = RV_DMAIN_TEXEL_HOLE;  // the cut-out quadrant
            }

            const bool border =
                x == 0 || y == 0 || x == RV_DMAIN_TEX_SIZE - 1 || y == RV_DMAIN_TEX_SIZE - 1;
            if (border) texel = RV_DMAIN_TEXEL_WHITE;

            texels_[static_cast<std::size_t>(y * RV_DMAIN_TEX_SIZE + x)] = texel;
        }
    }

    const int64_t bytes = static_cast<int64_t>(texels_.size() * sizeof(uint16_t));
    const int64_t addr = cv->video_asset_malloc(bytes);
    if (addr < 0) return;

    rv_texture texture{};
    texture.format = RV_TEXFMT_DIRECT15;
    texture.data = texels_.data();
    texture.size = static_cast<uint64_t>(bytes);
    texture.width = static_cast<uint64_t>(RV_DMAIN_TEX_SIZE);
    texture.height = static_cast<uint64_t>(RV_DMAIN_TEX_SIZE);

    if (cv->video_asset_write(addr, texture) < 0) {
        cv->video_asset_free(addr);
        return;
    }
    addr_texture_ = addr;
}

// A second texture in the INDEXED family: 8x8, IDX4, with a palette whose entry
// 0 is 0000h. DIRECT15 alone leaves the palette path untested, and that path is
// where the transparency rule is genuinely non-obvious — the hole is decided
// AFTER the lookup, so an opaque index can become a hole by palette alone.
void rv_dmain::build_idx4_texture() {
    rv_cv* cv = pdk_->cv();
    constexpr int64_t size = 8;

    // THEOREM: IDX4 packing. Two texels share a byte, LOW nibble first, and rows
    // are padded to whole bytes — so the stride is (width + 1) / 2, not width/2.
    texels_idx4_.assign(static_cast<std::size_t>(((size + 1) / 2) * size), 0);
    for (int64_t y = 0; y < size; ++y) {
        for (int64_t x = 0; x < size; ++x) {
            // A ring: index 0 (transparent) in the middle, colours around it.
            const bool edge = x == 0 || y == 0 || x == size - 1 || y == size - 1;
            const uint8_t index = edge ? static_cast<uint8_t>(1 + ((x + y) % 3)) : 0;

            const std::size_t byte = static_cast<std::size_t>(y * ((size + 1) / 2) + x / 2);
            if ((x & 1) == 0) {
                texels_idx4_[byte] = static_cast<uint8_t>((texels_idx4_[byte] & 0xF0) | index);
            } else {
                texels_idx4_[byte] =
                    static_cast<uint8_t>((texels_idx4_[byte] & 0x0F) | (index << 4));
            }
        }
    }

    palette_idx4_.assign(16, 0x0000);  // entry 0 stays 0000h: the hole
    palette_idx4_[1] = 0x001F;         // red
    palette_idx4_[2] = 0x03E0;         // green
    palette_idx4_[3] = 0x7FFF;         // white

    const int64_t texel_addr = cv->video_asset_malloc(static_cast<int64_t>(texels_idx4_.size()));
    if (texel_addr < 0) return;

    rv_texture texels{};
    texels.format = RV_TEXFMT_IDX4;
    texels.data = texels_idx4_.data();
    texels.size = texels_idx4_.size();
    texels.width = static_cast<uint64_t>(size);
    texels.height = static_cast<uint64_t>(size);
    if (cv->video_asset_write(texel_addr, texels) < 0) {
        cv->video_asset_free(texel_addr);
        return;
    }

    const int64_t palette_addr =
        cv->video_asset_malloc(static_cast<int64_t>(palette_idx4_.size() * sizeof(uint16_t)));
    if (palette_addr < 0) {
        cv->video_asset_free(texel_addr);
        return;
    }

    // A palette is uploaded as a texture of its own: DIRECT15, width = entry
    // count, height = 1. That convention is in rv_texture.hpp, and it is why no
    // separate palette-upload call exists.
    rv_texture palette{};
    palette.format = RV_TEXFMT_DIRECT15;
    palette.data = palette_idx4_.data();
    palette.size = palette_idx4_.size() * sizeof(uint16_t);
    palette.width = palette_idx4_.size();
    palette.height = 1;
    if (cv->video_asset_write(palette_addr, palette) < 0) {
        cv->video_asset_free(palette_addr);
        cv->video_asset_free(texel_addr);
        return;
    }

    addr_idx4_ = texel_addr;
    addr_idx4_palette_ = palette_addr;
}

void rv_dmain::probe_drive() {
    rv_cd* cd = pdk_->cd();
    if (!cd) return;

    // A name carrying path separators must be refused before anything touches
    // the medium — it is an attempt to leave the disc, not a spelling mistake.
    // This probe asserts the drive answers INVAL rather than merely NOENT.
    drive_rejects_paths_ = cd->asset_open("../../etc/passwd") == RV_ERR_INVAL &&
                           cd->asset_open("assets/thing.obj") == RV_ERR_INVAL;

    const int64_t handle = cd->asset_open("protagonist.obj");
    if (handle < 0) return;  // no medium inserted is a legal, quiet outcome

    const int64_t size = cd->asset_size(handle);
    if (size <= 0) return;

    std::vector<uint8_t> buffer(static_cast<std::size_t>(size));
    // AUTHORITATIVE is what asset_read returns, not what asset_size promised:
    // the contract calls the size a hint that may go stale between the calls.
    const int64_t read = cd->asset_read(handle, buffer.data(), size);
    if (read < 0) return;

    asset_bytes_ = read;
    asset_ok_ = read > 0 && buffer[0] == '#';  // a Wavefront .obj opens with a comment

    // The same name must resolve to the same handle, forever.
    if (cd->asset_open("protagonist.obj") != handle) asset_ok_ = false;
}

void rv_dmain::load_save() {
    rv_cm* cm = pdk_->cm();
    if (!cm) return;

    if (cm->card_slot_size() < static_cast<int64_t>(sizeof(rv_dmain_save))) {
        return;  // this machine's slots cannot hold our blob
    }

    rv_dmain_save blob{RV_DMAIN_SAVE_MAGIC, 0};

    const int64_t size = cm->card_size(0);
    if (size >= 0) {
        rv_dmain_save stored{};
        if (cm->card_read(0, &stored, static_cast<int64_t>(sizeof(stored))) >= 0 &&
            stored.magic == RV_DMAIN_SAVE_MAGIC) {
            blob.boot_count = stored.boot_count;
        }
    } else if (size != RV_ERR_NOENT) {
        // A real medium failure. NOT the same as "no save yet": overwriting now
        // would destroy a save that may well be there, so play without one.
        return;
    }

    ++blob.boot_count;
    if (cm->card_write(0, &blob, static_cast<int64_t>(sizeof(blob))) == RV_OK) {
        boot_count_ = blob.boot_count;
        card_ok_ = true;
    }
}

void rv_dmain::build_beep() {
    rv_ca* ca = pdk_->ca();
    if (!ca || ca->voice_count() < 1) return;

    // THEOREM: an exponentially decaying sine. The console has no pitch control,
    // so a sample plays at exactly the rate it was recorded for — the frequency
    // is baked in here, against RV_DMAIN_BEEP_RATE, and nothing downstream can
    // bend it. The decay lives in the SAMPLE rather than the envelope so the
    // beep stays recognisable even with an ADSR nobody has tuned.
    std::vector<int16_t> pcm(static_cast<std::size_t>(RV_DMAIN_BEEP_FRAMES));
    for (int64_t i = 0; i < RV_DMAIN_BEEP_FRAMES; ++i) {
        const float t = static_cast<float>(i) / static_cast<float>(RV_DMAIN_BEEP_RATE);
        const float envelope = std::exp(-6.0f * t);
        const float wave = std::sin(6.28318531f * RV_DMAIN_BEEP_HZ * t);
        pcm[static_cast<std::size_t>(i)] =
            static_cast<int16_t>(wave * envelope * static_cast<float>(RV_DMAIN_BEEP_PEAK));
    }

    const int64_t bytes = static_cast<int64_t>(pcm.size() * sizeof(int16_t));
    const int64_t addr = ca->sound_asset_malloc(bytes);
    if (addr < 0) return;

    rv_sample sample{};
    sample.data = pcm.data();
    sample.size = bytes;
    if (ca->sound_asset_write(addr, &sample) < 0) {
        ca->sound_asset_free(addr);
        return;
    }

    rv_voice_conf conf{};
    conf.voice = 1;  // voice 0
    conf.loop_type = rv_loop::none;
    conf.sample_address = addr;
    conf.ar = 5;
    conf.dr = 40;
    conf.sr = 0;
    conf.rr = 120;
    conf.sl = 26000;
    conf.volume = 32767;
    conf.volume_l = 32767;
    conf.volume_r = 32767;
    if (ca->voice_setup(&conf) < 0) return;

    addr_beep_ = addr;
    beep_ok_ = true;
}

// --- simulation --------------------------------------------------------------

void rv_dmain::frame_update(float dt) {
    if (!pdk_) return;
    if (dt < 0.0f) dt = 0.0f;  // a non-monotonic clock must not run the show backwards

    hue_ += dt * RV_DMAIN_HUE_RATE;
    hue_ -= std::floor(hue_);
    spin_ += dt * RV_DMAIN_SPIN_RATE;

    rv_cio* cio = pdk_->cio();
    rv_ca* ca = pdk_->ca();

    // THEOREM: edge detection by snapshot diff. rv_cio reports the CURRENT level
    // of every source and never a press/release event, so "was it pressed THIS
    // frame" is (now & ~was) — set now, clear a frame ago. Acting on the level
    // would fire the beep sixty times a second for as long as the key is held;
    // only the rising edge is an intent.
    for (int64_t port = 0; port < iport_count_; ++port) {
        const uint64_t now = cio->iport_state(port).buttons;
        uint64_t& was = prev_buttons_[static_cast<std::size_t>(port)];
        const uint64_t pressed = now & ~was;
        was = now;

        // Esc on the keyboard, Option/Start on a pad — any port may ask.
        if (pressed & RV_ISOURCE_MENU_BTTN_MENU) release_ = true;

        if ((pressed & RV_ISOURCE_FRONT_BTTN_SOUTH) && beep_ok_ && ca) {
            ca->voice_play(1);
        }
    }
}

// --- the frame ---------------------------------------------------------------

void rv_dmain::frame_render() {
    if (!pdk_) return;

    // No simulation lives here: a headless run never calls frame_render(), and
    // the show must advance identically either way (rv_de::frame_render).
    rv_cv* cv = pdk_->cv();

    // The Z flag is on because the cut-out row depends on it: a hole must write
    // neither colour nor depth, and that is only observable when per-pixel depth
    // resolves primitives sharing an ordering-table bucket.
    cv->frame_configure(RV_PIPELINE_BUFFER_CONFIG_TYPE_Z,
                        rv_pdklib::rv_hsv_to_rgb(hue_, 0.5f, 0.35f));

    draw_test_grid();
    draw_post();

    // The console does NOT flush for the disc (rv_de::frame_render). Nothing
    // filed above reaches the screen without this call.
    cv->frame_flush();
}

// --- the test card -----------------------------------------------------------

// PATTERN: test card. Every cell exercises exactly ONE thing the console can
// draw, and says which. That is what makes it a test rather than a demo: a
// broken feature shows up as one wrong cell with a name on it, instead of a
// picture that is subtly off in a way nobody can localise.
//
// The set below is the console's whole drawing vocabulary, from
// pdk/cv/rv_primitives.hpp: three primitive kinds, three fill modes, three wrap
// modes, both texel families, the cut-out rule, and the ordering table.
namespace {

constexpr int RV_DMAIN_GRID_COLS = 4;
constexpr int RV_DMAIN_GRID_ROWS = 3;
constexpr int RV_DMAIN_GRID_TOP = 28;
constexpr int RV_DMAIN_CELL_W = 78;
constexpr int RV_DMAIN_CELL_H = 60;
constexpr int RV_DMAIN_CELL_ART_TOP = 11;  // below the cell's label

constexpr const char* RV_DMAIN_CELL_LABEL[] = {
    "LINE", "TRI",  "QUAD",   "WIRE",  "SPRITE",  "DIRECT15",
    "TILE", "IDX4", "CUTOUT", "DEPTH", "STRETCH", "3D",
};

}  // namespace

void rv_dmain::draw_test_grid() {
    for (int i = 0; i < RV_DMAIN_GRID_COLS * RV_DMAIN_GRID_ROWS; ++i) draw_cell(i);
}

void rv_dmain::draw_cube_cell(int x, int y, int w, int h) {
    rv_cv* cv = pdk_->cv();

    // The viewport is the CELL, not the screen: the transform maps normalized
    // coordinates onto the width and height it is handed, anchored at the upper
    // left. A cell-sized pair confines the cube to a box; the offset below then
    // moves that box into place, because the transform offers no offset of its
    // own and the finished vertices are plain int16 screen coordinates.
    const float vw = static_cast<float>(w);
    const float vh = static_cast<float>(h);

    const rv_pdklib::rv_camera camera =
        rv_pdklib::rv_camera_make(rv_pdklib::rv_vec3{0.0f, 1.1f, -4.4f},  // eye
                                  rv_pdklib::rv_vec3{0.0f, 0.0f, 0.0f},   // target
                                  rv_pdklib::rv_vec3{0.0f, 1.0f, 0.0f},   // up
                                  1.0472f,                                // 60 deg vertical fov
                                  vw / vh, 0.1f, 100.0f);

    const rv_pdklib::rv_mat4 model = rv_pdklib::rv_mat4_mul(
        rv_pdklib::rv_mat4_rotate_y(spin_), rv_pdklib::rv_mat4_rotate_x(spin_ * 0.6f));

    const rv_pdklib::rv_xform_conf conf = rv_pdklib::rv_xform_conf_make(
        rv_pdklib::rv_camera_mvp(camera, model), camera, vw, vh, RV_DMAIN_DEPTH_ART_LO,
        RV_DMAIN_DEPTH_ART_HI, rv_pdklib::RV_CULL_SCREEN_CW);

    const rv_pdklib::rv_vec3 to_light{-0.4f, 0.8f, -0.5f};

    for (const rv_dmain_face& face : RV_DMAIN_CUBE) {
        // Lighting is in WORLD space, so the normal takes the model matrix. The
        // positions do NOT: rv_camera_mvp already carries it, and transforming
        // them here as well would spin the cube twice.
        const rv_color shade = rv_pdklib::rv_shade_lambert(
            rv_pdklib::rv_hsv_to_rgb(hue_ + 0.5f, 0.45f, 1.0f),
            rv_pdklib::rv_mat4_mul_direction(model, face.normal), to_light, 0.25f);

        rv_pdklib::rv_xform_vertex vertexes[4];
        for (int i = 0; i < 4; ++i) {
            vertexes[i].position = face.corner[i];
            vertexes[i].color = shade;
            vertexes[i].uv = rv_uv{0, 0};
        }

        rv_primitive primitive{};
        if (!rv_pdklib::rv_xform_quad(conf, vertexes, primitive)) continue;  // culled or clipped
        primitive.data.polygon.fill_mode = RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;

        for (uint32_t i = 0; i < primitive.data.polygon.vertex_count; ++i) {
            primitive.data.polygon.vertexes[i].x =
                to_screen(static_cast<float>(primitive.data.polygon.vertexes[i].x + x));
            primitive.data.polygon.vertexes[i].y =
                to_screen(static_cast<float>(primitive.data.polygon.vertexes[i].y + y));
        }
        cv->frame_put(primitive);
    }
}

void rv_dmain::draw_cell(int index) {
    rv_cv* cv = pdk_->cv();

    const int col = index % RV_DMAIN_GRID_COLS;
    const int row = index / RV_DMAIN_GRID_COLS;
    const int cx = 4 + col * RV_DMAIN_CELL_W;
    const int cy = RV_DMAIN_GRID_TOP + row * RV_DMAIN_CELL_H;

    // The art area: the cell minus its label strip and a pixel of breathing room.
    const int ax = cx + 3;
    const int ay = cy + RV_DMAIN_CELL_ART_TOP;
    const int aw = RV_DMAIN_CELL_W - 8;
    const int ah = RV_DMAIN_CELL_H - RV_DMAIN_CELL_ART_TOP - 5;

    if (addr_font_ != 0) {
        const rv_pdklib::rv_text_style ink =
            rv_pdklib::rv_text_style_make(addr_font_, addr_font_palette_, RV_DMAIN_DEPTH_TEXT, 1);
        rv_pdklib::rv_text_draw(ink, cx + 2, cy + 1, RV_DMAIN_CELL_LABEL[index],
                                [cv](const rv_primitive& p) { cv->frame_put(p); });
    }

    const rv_color hot = rv_pdklib::rv_hsv_to_rgb(hue_, 0.85f, 1.0f);
    const rv_color cold = rv_pdklib::rv_hsv_to_rgb(hue_ + 0.4f, 0.85f, 1.0f);
    const rv_color mid = rv_pdklib::rv_hsv_to_rgb(hue_ + 0.7f, 0.85f, 1.0f);

    switch (index) {
        case 0: {  // LINE — the 1D case of colour interpolation
            rv_primitive primitive{};
            primitive.type = RV_PRIMITIVE_LINE;
            primitive.depth = RV_DMAIN_DEPTH_ART_HI;
            primitive.data.line.vertexes[0] = make_vertex(ax, ay + ah, hot);
            primitive.data.line.vertexes[1] = make_vertex(ax + aw, ay, cold);
            cv->frame_put(primitive);
            break;
        }
        case 1: {  // TRI — gouraud across three different vertex colours
            rv_primitive primitive{};
            primitive.type = RV_PRIMITIVE_POLYGON;
            primitive.depth = RV_DMAIN_DEPTH_ART_HI;
            rv_polygon& t = primitive.data.polygon;
            t.fill_mode = RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;
            t.addr_texture = 0;
            t.addr_palette = 0;
            t.mapping = RV_TEXWRAP_CLAMP;
            t.vertex_count = 3;
            t.vertexes[0] = make_vertex(ax + aw / 2, ay, hot);
            t.vertexes[1] = make_vertex(ax, ay + ah, cold);
            t.vertexes[2] = make_vertex(ax + aw, ay + ah, mid);
            t.vertexes[3] = make_vertex(0, 0, hot);  // ignored at vertex_count 3
            cv->frame_put(primitive);
            break;
        }
        case 2: {  // QUAD — the same fill across the (1,2,3)/(2,3,4) split
            rv_primitive primitive{};
            primitive.type = RV_PRIMITIVE_POLYGON;
            primitive.depth = RV_DMAIN_DEPTH_ART_HI;
            rv_polygon& q = primitive.data.polygon;
            q.fill_mode = RV_PRIMITIVE_FILL_MODE_FLAT_COLOURED;
            q.addr_texture = 0;
            q.addr_palette = 0;
            q.mapping = RV_TEXWRAP_CLAMP;
            q.vertex_count = 4;
            // Z ORDER, not around the rim: the console splits a quad into
            // (1,2,3) and (2,3,4).
            q.vertexes[0] = make_vertex(ax, ay, hot);
            q.vertexes[1] = make_vertex(ax + aw, ay, cold);
            q.vertexes[2] = make_vertex(ax, ay + ah, mid);
            q.vertexes[3] = make_vertex(ax + aw, ay + ah, hot);
            cv->frame_put(primitive);
            break;
        }
        case 3: {  // WIRE — edges only, so the interior must stay background
            rv_primitive primitive{};
            primitive.type = RV_PRIMITIVE_POLYGON;
            primitive.depth = RV_DMAIN_DEPTH_ART_HI;
            rv_polygon& q = primitive.data.polygon;
            q.fill_mode = RV_PRIMITIVE_FILL_MODE_WIREFRAME;
            q.addr_texture = 0;
            q.addr_palette = 0;
            q.mapping = RV_TEXWRAP_CLAMP;
            q.vertex_count = 4;
            q.vertexes[0] = make_vertex(ax, ay, hot);
            q.vertexes[1] = make_vertex(ax + aw, ay, hot);
            q.vertexes[2] = make_vertex(ax, ay + ah, cold);
            q.vertexes[3] = make_vertex(ax + aw, ay + ah, cold);
            cv->frame_put(primitive);
            break;
        }
        case 4:  // SPRITE — the axis-aligned fast path, one flat colour
            cv->frame_put(make_bar(static_cast<float>(ax), static_cast<float>(ay),
                                   static_cast<float>(aw), static_cast<float>(ah), hot,
                                   RV_DMAIN_DEPTH_ART_HI));
            break;

        case 5:  // DIRECT15 — a texel that carries its own colour, CLAMP
            draw_textured(ax, ay, aw, ah, addr_texture_, 0, RV_TEXWRAP_CLAMP);
            break;

        case 6:  // TILE — the same texture, repeated
            draw_textured(ax, ay, aw, ah, addr_texture_, 0, RV_TEXWRAP_TILE);
            break;

        case 7:  // IDX4 — an indexed texel resolved through a palette
            draw_textured(ax, ay, aw, ah, addr_idx4_, addr_idx4_palette_, RV_TEXWRAP_STRETCH);
            break;

        case 8: {  // CUTOUT — 0000h writes neither colour nor depth
            // The backdrop is filed FIRST and NEARER-behind: what shows through
            // the holes is this magenta, and if the hole wrote depth it would
            // not.
            cv->frame_put(make_bar(static_cast<float>(ax), static_cast<float>(ay),
                                   static_cast<float>(aw), static_cast<float>(ah),
                                   rv_color{220, 60, 200}, RV_DMAIN_DEPTH_ART_LO));
            draw_textured(ax, ay, aw, ah, addr_texture_, 0, RV_TEXWRAP_STRETCH);
            break;
        }
        case 9: {  // DEPTH — the ordering table sorts, submission order does not
            // Filed nearest FIRST. If the console honoured submission order
            // instead of the depth key, the stack would come out inverted.
            const rv_color tint[3] = {hot, cold, mid};
            const int32_t depth[3] = {RV_DMAIN_DEPTH_ART_HI, RV_DMAIN_DEPTH_ART_HI - 40,
                                      RV_DMAIN_DEPTH_ART_LO};
            for (int i = 0; i < 3; ++i) {
                cv->frame_put(make_bar(static_cast<float>(ax + i * 12),
                                       static_cast<float>(ay + i * 8), static_cast<float>(aw - 24),
                                       static_cast<float>(ah - 16), tint[i], depth[i]));
            }
            break;
        }
        case 10:  // STRETCH — uv ignored, the texture scaled to the primitive
            draw_textured(ax, ay, aw, ah, addr_texture_, 0, RV_TEXWRAP_STRETCH);
            break;

        default:  // 3D — pdklib's transform feeding the console screen-space quads
            draw_cube_cell(ax, ay, aw, ah);
            break;
    }
}
void rv_dmain::draw_textured(int x, int y, int w, int h, int64_t addr_texture, int64_t addr_palette,
                             rv_texture_mapping_type mapping) {
    if (addr_texture == 0) return;

    rv_primitive primitive{};
    primitive.type = RV_PRIMITIVE_SPRITE;
    primitive.depth = RV_DMAIN_DEPTH_ART_HI;

    rv_sprite& sprite = primitive.data.sprite;
    sprite.fill_mode = RV_PRIMITIVE_FILL_MODE_SAMPLE_TEXTURE;
    sprite.addr_texture = addr_texture;
    sprite.addr_palette = addr_palette;
    sprite.color = rv_color{255, 255, 255};
    sprite.mapping = mapping;
    sprite.x = to_screen(static_cast<float>(x));
    sprite.y = to_screen(static_cast<float>(y));
    sprite.width = static_cast<uint16_t>(w);
    sprite.height = static_cast<uint16_t>(h);

    pdk_->cv()->frame_put(primitive);
}

// PATTERN: POST header. Two lines that say what this machine IS — the virtual
// budget it imposes on itself — and one bottom line saying whether each
// subsystem answered. The numbers come straight from the contract's geometry
// queries, so a line that prints at all is a query that worked.
//
// An earlier version of this screen captioned the picture instead ("textures",
// "cube", "ticks", "bar", "south") and was useless: those are the names of THIS
// file's internals, and nobody outside it can know that "south" is what the
// input contract calls the bottom face button.
void rv_dmain::draw_post_row(int, const char*, const char*, const char*, bool) {}

void rv_dmain::draw_post() {
    if (addr_font_ == 0) return;

    rv_cv* cv = pdk_->cv();
    auto file = [cv](const rv_primitive& primitive) { cv->frame_put(primitive); };

    const int width = static_cast<int>(screen_width_);
    const int height = static_cast<int>(screen_height_);
    const rv_color slab{12, 14, 22};
    const rv_pdklib::rv_text_style ink =
        rv_pdklib::rv_text_style_make(addr_font_, addr_font_palette_, RV_DMAIN_DEPTH_TEXT, 1);
    const rv_pdklib::rv_text_style bad =
        rv_pdklib::rv_text_style_make(addr_font_, addr_font_palette_bad_, RV_DMAIN_DEPTH_TEXT, 1);

    // Opaque slabs, not a dim overlay: the console has no blending, and light
    // ink over lit geometry is exactly what made the first version unreadable.
    cv->frame_put(
        make_bar(0.0f, 0.0f, static_cast<float>(width), 24.0f, slab, RV_DMAIN_DEPTH_PANEL));
    rv_pdklib::rv_text_draw(ink, 4, 2, RV_DMAIN_TITLE, file);
    rv_pdklib::rv_text_draw(ink, width - 4 - rv_pdklib::rv_text_measure_width(RV_DMAIN_NO_DISC, 1),
                            2, RV_DMAIN_NO_DISC, file);

    // The budget line. Saying VIRTUAL out loud matters: none of this is what the
    // host has, all of it is what the fantasy machine is defined to have, and
    // the pools really do refuse past the line.
    char budget[96];
    char vram[24];
    char sram[24];
    format_bytes(vram, sizeof(vram), video_memory_size_);
    format_bytes(sram, sizeof(sram), sound_memory_size_);
    std::snprintf(budget, sizeof(budget), "VIRTUAL %lldx%lld %s %lldv %s",
                  static_cast<long long>(screen_width_), static_cast<long long>(screen_height_),
                  vram, static_cast<long long>(voice_count_), sram);
    rv_pdklib::rv_text_draw(ink, 4, 13, budget, file);

    // The bottom slab: one word per subsystem, and the word is the whole report.
    cv->frame_put(make_bar(0.0f, static_cast<float>(height) - 24.0f, static_cast<float>(width),
                           24.0f, slab, RV_DMAIN_DEPTH_PANEL));

    struct rv_dmain_probe {
        const char* label;
        bool ok;
        bool absent;  // legal "nothing there", which is not a failure
    };
    const rv_dmain_probe probes[4] = {
        {"AUDIO", beep_ok_, false},
        {"DRIVE", asset_ok_, asset_bytes_ == 0},
        {"CARD", card_ok_, false},
        {"PATHS", drive_rejects_paths_, false},
    };

    int pen = 4;
    for (const rv_dmain_probe& probe : probes) {
        rv_pdklib::rv_text_draw(ink, pen, static_cast<int>(height) - 21, probe.label, file);
        pen += rv_pdklib::rv_text_measure_width(probe.label, 1) + 8;

        const char* mark = probe.absent ? "-" : (probe.ok ? "OK" : "FAIL");
        rv_pdklib::rv_text_draw(probe.ok || probe.absent ? ink : bad, pen,
                                static_cast<int>(height) - 21, mark, file);
        pen += rv_pdklib::rv_text_measure_width(mark, 1) + 10;
    }

    // The probe row owns its whole line: four labels and four verdicts already
    // fill 40 columns, and anything sharing the row lands on top of them.
    char pads[32];
    std::snprintf(pads, sizeof(pads), "%lld pad(s) boot %lu",
                  static_cast<long long>(pads_connected_), static_cast<unsigned long>(boot_count_));
    rv_pdklib::rv_text_draw(ink, 4, height - 11, pads, file);
    rv_pdklib::rv_text_draw(ink, width - 4 - rv_pdklib::rv_text_measure_width(RV_DMAIN_HINTS, 1),
                            height - 11, RV_DMAIN_HINTS, file);
}

void rv_dmain::disc_shutdown() {
    // The facade is still valid here and this is the LAST moment it is. Whatever
    // disc_initialize took is given back now, not in a destructor: once this
    // returns the console may unload the disc's code, and a destructor belonging
    // to unmapped code cannot run.
    if (!pdk_) return;

    rv_cv* cv = pdk_->cv();
    if (addr_texture_ != 0) cv->video_asset_free(addr_texture_);
    if (addr_font_ != 0) cv->video_asset_free(addr_font_);
    if (addr_font_palette_ != 0) cv->video_asset_free(addr_font_palette_);
    if (addr_font_palette_bad_ != 0) cv->video_asset_free(addr_font_palette_bad_);
    if (addr_idx4_ != 0) cv->video_asset_free(addr_idx4_);
    if (addr_idx4_palette_ != 0) cv->video_asset_free(addr_idx4_palette_);
    addr_texture_ = 0;
    addr_font_ = 0;
    addr_font_palette_ = 0;
    addr_font_palette_bad_ = 0;
    addr_idx4_ = 0;
    addr_idx4_palette_ = 0;

    rv_ca* ca = pdk_->ca();
    if (ca && addr_beep_ != 0) {
        // Stop first: the contract makes sound_asset_free() answer RV_ERR_BUSY
        // while a voice is still reading out of the region.
        ca->voice_stop(1);
        ca->sound_asset_free(addr_beep_);
        addr_beep_ = 0;
    }
}

const char* rv_dmain::disc_title() const { return "rv_dmain - service test"; }

}  // namespace rv_service
